In [1]:
import pandas as pd
from haversine import haversine
import sqlite3
import datetime
from bs4 import BeautifulSoup
sqlite_db = '/home/llevin/Desktop/capstone2/databases/database.sqlite'
conn = sqlite3.connect(sqlite_db) 
c = conn.cursor()

In [23]:
epl_path = []
for i in range(25,9,-1):
    if i < 9:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/199'+str(i)+'-199'+str(i+1)+'/Premier.csv')
    elif i == 9:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/199'+str(i)+'-2000/Premier.csv')
    elif i < 19:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/200'+str(i-10)+'-200'+str(i-9)+'/Premier.csv')
    elif i == 19:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/200'+str(i-10)+'-20'+str(i-9)+'/Premier.csv')
    else:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/20'+str(i-10)+'-20'+str(i-9)+'/Premier.csv')

In [24]:
epl_path

['/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2015-2016/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2014-2015/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2013-2014/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2012-2013/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2011-2012/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2010-2011/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2009-2010/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2008-2009/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2007-2008/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2006-2007/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2005-2006/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2004-2005/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2003-2004/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2002-2003/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2001-2002/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2000-2001/Premier.csv']

In [96]:
premier_data = pd.DataFrame()
for path in epl_path:
    try:
        temp_df = pd.read_csv(path)
        sequence = [premier_data,temp_df]
        premier_data = pd.concat(sequence)
    except:
        print path

/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2015-2016/Premier.csv
/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2004-2005/Premier.csv
/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2003-2004/Premier.csv
/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2002-2003/Premier.csv

In [101]:
temp = pd.read_csv('/home/llevin/Desktop/capstone2/databases/football-data.co.uk/england/2002-2003/Premier.csv')
sequence = [premier_data,temp]
premier_data = pd.concat(sequence)

In [102]:
premier_data.shape

(5700, 100)

In [103]:
premier_data.rename(columns={'FTHG':'full_time_home_goals','FTAG':'full_time_away_goals','FTR':'result','HTHG':'half_time_home_goals',
                       'HTAG':'half_time_away_goals','HTR':'half_time_result','HS':'home_shots','AS':'away_shots','HST':'home_shots_target',
                       'AST':'away_shots_target','HHW':'home_post','AHW':'away_post','HC':'home_corners','AC':'away_corners','HF':'home_fouls',
                       'AF':'away_fouls','HO':'home_offside','AO':'away_offside','HY':'home_yellow_cards','AY':'away_yellow_cards',
                       'HR':'home_red_cards','AR':'away_red_cards','HBP':'home_booking_pts','ABP':'away_booking_pts',
                            'Attendance':'attendance','HomeTeam':'home_team','AwayTeam':'away_team'},inplace=True)

In [104]:
premier_data.head()

,away_booking_pts,away_corners,away_fouls,away_post,away_offside,away_red_cards,away_shots,away_shots_target,away_yellow_cards,attendance,...,SOH,SYA,SYD,SYH,VCA,VCD,VCH,WHA,WHD,WHH
0,NaN,3,19,NaN,NaN,1,4,2,2,NaN,...,NaN,NaN,NaN,NaN,10.50,6.25,1.25,12.0,5.5,1.25
1,NaN,6,10,NaN,NaN,0,13,3,1,NaN,...,NaN,NaN,NaN,NaN,2.40,3.40,3.20,2.4,3.1,3.10
2,NaN,0,20,NaN,NaN,0,5,4,4,NaN,...,NaN,NaN,NaN,NaN,10.00,5.20,1.36,9.0,4.5,1.36
3,NaN,9,10,NaN,NaN,0,11,4,2,NaN,...,NaN,NaN,NaN,NaN,3.12,3.20,2.55,2.9,3.0,2.60
4,NaN,8,9,NaN,NaN,0,7,2,3,NaN,...,NaN,NaN,NaN,NaN,4.75,3.30,1.95,4.2,3.2,1.95

In [33]:
for col in premier_data.columns:
    print col, premier_data[col].isnull().sum()

away_booking_pts 4940
away_corners 0
away_fouls 0
away_post 4940
away_offside 4940
away_red_cards 0
away_shots 0
away_shots_target 0
away_yellow_cards 0
attendance 4941
away_team 0
B365<2.5 4696
B365>2.5 4696
B365A 760
B365AH 4962
B365AHA 4962
B365AHH 4962
B365D 760
B365H 760
BSA 3420
BSD 3420
BSH 3420
BWA 1520
BWD 1520
BWH 1520
Bb1X2 1900
BbAH 1910
BbAHh 1910
BbAv<2.5 1900
BbAv>2.5 1900
BbAvA 1900
BbAvAHA 1910
BbAvAHH 1910
BbAvD 1900
BbAvH 1900
BbMx<2.5 1900
BbMx>2.5 1900
BbMxA 1900
BbMxAHA 1910
BbMxAHH 1910
BbMxD 1900
BbMxH 1900
BbOU 1900
Date 0
Div 0
full_time_away_goals 0
full_time_home_goals 0
result 0
GB<2.5 4563
GB>2.5 4563
GBA 844
GBAH 4951
GBAHA 4951
GBAHH 4942
GBD 844
GBH 844
home_booking_pts 4940
home_corners 0
home_fouls 0
home_post 4940
home_offside 4940
home_red_cards 0
home_shots 0
home_shots_target 0
half_time_away_goals 0
half_time_home_goals 0
half_time_result 0
home_yellow_cards 0
home_team 0
IWA 18
IWD 18
IWH 18
LBA 62
LBAH 4979
LBAHA 4979
LBAHH 4979
LBD 62
LBH 62
PSA 4561
PSD 4561
PSH 4561
Referee 380
SBA 1196
SBD 1196
SBH 1196
SJA 2241
SJD 2241
SJH 2241
SOA 4940
SOD 4940
SOH 4940
SYA 5327
SYD 5327
SYH 5327
VCA 1900
VCD 1900
VCH 1900
WHA 114
WHD 114
WHH 114

In [105]:
premier_data = premier_data[['away_corners','away_fouls','away_shots','away_shots_target','away_yellow_cards',
                            'away_red_cards','away_team','Date','full_time_away_goals','full_time_home_goals',
                            'home_corners','home_fouls','home_red_cards','home_yellow_cards','home_shots','home_shots_target',
                            'half_time_away_goals','half_time_home_goals','half_time_result','home_team','Referee','result']]

In [106]:
premier_data.head(3).T

                                   0          1           2
away_corners                       3          6           0
away_fouls                        19         10          20
away_shots                         4         13           5
away_shots_target                  2          3           4
away_yellow_cards                  2          1           4
away_red_cards                     1          0           0
away_team             Crystal Palace    Everton     Swansea
Date                        16/08/14   16/08/14    16/08/14
full_time_away_goals               1          2           2
full_time_home_goals               2          2           1
home_corners                       9          3           4
home_fouls                        13         16          14
home_red_cards                     0          0           0
home_yellow_cards                  2          1           2
home_shots                        14         11          14
home_shots_target                  6          3           5
half_time_away_goals               1          2           1
half_time_home_goals               1          1           0
half_time_result                   D          A           A
home_team                    Arsenal  Leicester  Man United
Referee                       J Moss    M Jones      M Dean
result                             H          D           A

In [116]:
premier_data.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
away_team                 0
Date                      0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 380
result                    0
dtype: int64

In [117]:
premier_data[premier_data['Referee'].isnull()]

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_red_cards,home_yellow_cards,home_shots,home_shots_target,half_time_away_goals,half_time_home_goals,half_time_result,home_team,Referee,result
0,0,8,3,2,0,0,Sunderland,18/08/12,0,0,...,0,0,14,4,0,0,D,Arsenal,NaN,D
1,3,11,4,2,0,0,Norwich,18/08/12,0,5,...,0,0,11,9,0,2,H,Fulham,NaN,H
2,5,8,12,6,2,0,Tottenham,18/08/12,1,2,...,0,2,6,4,0,0,D,Newcastle,NaN,H
3,3,14,12,8,2,0,Swansea,18/08/12,5,0,...,0,2,20,11,1,0,A,QPR,NaN,A
4,3,14,6,3,4,1,Stoke,18/08/12,1,1,...,0,2,9,3,1,0,A,Reading,NaN,D
5,3,11,14,7,4,1,Liverpool,18/08/12,0,3,...,0,1,15,10,0,1,H,West Brom,NaN,H
6,4,8,10,6,1,0,Aston Villa,18/08/12,0,1,...,0,0,8,4,0,1,H,West Ham,NaN,H
7,3,6,9,6,2,0,Southampton,19/08/12,2,3,...,0,1,20,15,0,1,H,Man City,NaN,H
8,1,11,5,3,2,0,Chelsea,19/08/12,2,0,...,0,2,12,4,2,0,A,Wigan,NaN,A
9,8,11,12,7,2,0,Man United,20/08/12,0,1,...,0,1,16,7,0,0,D,Everton,NaN,H
10,5,14,7,5,2,0,Reading,22/08/12,2,4,...,0,0,23,11,2,1,A,Chelsea,NaN,H
11,9,7,19,11,0,0,Everton,25/08/12,3,1,...,1,1,7,3,3,0,A,Aston Villa,NaN,A
12,3,10,11,5,0,0,Newcastle,25/08/12,0,2,...,0,1,11,6,0,2,H,Chelsea,NaN,H
13,8,7,14,11,1,0,Fulham,25/08/12,2,3,...,0,0,20,11,1,3,H,Man United,NaN,H
14,2,14,6,4,2,0,QPR,25/08/12,1,1,...,0,0,13,4,1,1,D,Norwich,NaN,D
15,3,9,12,8,0,0,Wigan,25/08/12,2,0,...,0,0,14,9,0,0,D,Southampton,NaN,A
16,4,17,7,6,4,0,West Ham,25/08/12,0,3,...,0,2,10,7,0,2,H,Swansea,NaN,H
17,5,7,10,5,2,0,West Brom,25/08/12,1,1,...,0,1,18,10,0,0,D,Tottenham,NaN,D
18,4,7,11,5,0,0,Man City,26/08/12,2,2,...,0,1,15,8,0,1,H,Liverpool,NaN,D
19,11,9,16,6,0,0,Arsenal,26/08/12,0,0,...,0,2,7,4,0,0,D,Stoke,NaN,D
20,3,3,9,5,1,0,QPR,01/09/12,1,3,...,0,2,19,12,0,1,H,Man City,NaN,H
21,0,7,4,3,1,0,Sunderland,01/09/12,2,2,...,1,1,14,10,2,1,A,Swansea,NaN,D
22,2,12,10,4,0,0,Norwich,01/09/12,1,1,...,1,1,15,9,0,0,D,Tottenham,NaN,D
23,3,15,12,5,4,0,Everton,01/09/12,0,2,...,0,1,14,8,0,0,D,West Brom,NaN,H
24,6,5,14,13,0,0,Fulham,01/09/12,0,3,...,0,0,17,12,0,3,H,West Ham,NaN,H
25,1,11,16,8,2,0,Stoke,01/09/12,2,2,...,0,1,9,5,1,1,D,Wigan,NaN,D
26,2,7,11,7,2,0,Arsenal,02/09/12,2,0,...,0,2,17,8,1,0,A,Liverpool,NaN,A
27,6,20,13,9,4,0,Aston Villa,02/09/12,1,1,...,0,1,16,6,1,0,A,Newcastle,NaN,D
28,7,4,18,9,0,0,Man United,02/09/12,3,2,...,0,1,15,8,1,1,D,Southampton,NaN,A
29,3,7,9,4,0,0,Southampton,15/09/12,1,6,...,0,0,20,12,1,4,H,Arsenal,NaN,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,4,10,12,8,0,0,Man City,04/05/13,0,0,...,0,0,7,1,0,0,D,Swansea,NaN,D
351,5,9,10,6,1,0,Southampton,04/05/13,0,1,...,0,1,7,4,0,0,D,Tottenham,NaN,H
352,5,7,13,8,3,0,Wigan,04/05/13,3,2,...,0,4,17,11,1,1,D,West Brom,NaN,A
353,3,12,11,6,1,0,Newcastle,04/05/13,0,0,...,0,1,9,3,0,0,D,West Ham,NaN,D
354,5,10,11,4,2,0,Everton,05/05/13,0,0,...,0,1,16,8,0,0,D,Liverpool,NaN,D
355,7,9,15,6,1,0,Chelsea,05/05/13,1,0,...,1,2,10,4,0,0,D,Man United,NaN,A
356,6,12,11,7,2,0,Stoke,06/05/13,1,1,...,1,2,14,7,1,0,A,Sunderland,NaN,D
357,8,9,20,11,1,0,West Brom,07/05/13,0,1,...,0,2,21,9,0,1,H,Man City,NaN,H
358,4,13,10,6,2,0,Swansea,07/05/13,3,2,...,0,2,14,11,0,1,H,Wigan,NaN,A
359,5,16,13,6,2,0,Tottenham,08/05/13,2,2,...,0,1,15,8,1,2,H,Chelsea,NaN,D
360,7,8,11,8,3,1,Chelsea,11/05/13,2,1,...,1,2,12,7,0,1,H,Aston Villa,NaN,A
361,1,11,7,2,2,0,West Ham,12/05/13,0,2,...,0,1,23,13,0,1,H,Everton,NaN,H
362,8,10,20,14,1,0,Liverpool,12/05/13,3,1,...,0,0,10,8,1,1,D,Fulham,NaN,A
363,5,6,5,2,0,0,Swansea,12/05/13,1,2,...,0,0,16,9,0,1,H,Man United,NaN,H
364,2,7,8,5,1,0,West Brom,12/05/13,0,4,...,0,2,11,8,0,1,H,Norwich,NaN,H
365,2,8,10,7,3,1,Newcastle,12/05/13,2,1,...,0,1,8,3,2,1,A,QPR,NaN,A
366,11,5,23,15,1,0,Tottenham,12/05/13,2,1,...,1,4,6,3,1,1,D,Stoke,NaN,A
367,10,10,15,10,2,0,Southampton,12/05/13,1,1,...,0,0,5,5,0,0,D,Sunderland,NaN,D
368,4,11,10,5,2,0,Wigan,14/05/13,1,4,...,0,0,19,12,1,1,D,Arsenal,NaN,H
369,10,7,27,20,1,0,Man City,14/05/13,2,0,...,0,0,11,7,1,0,A,Reading,NaN,A
370,4,8,16,9,2,0,Everton,19/05/13,1,2,...,0,2,20,10,1,1,D,Chelsea,NaN,H
371,0,3,10,3,3,0,QPR,19/05/13,0,1,...,0,1,27,20,0,1,H,Liverpool,NaN,H
372,7,8,12,7,0,0,Norwich,19/05/13,3,2,...,0,1,12,5,1,1,D,Man City,NaN,A
373,4,10,9,3,2,0,Arsenal,19/05/13,1,0,...,0,1,7,2,0,0,D,Newcastle,NaN,A
374,4,7,7,3,2,0,Stoke,19/05/13,1,1,...,0,0,11,7,0,0,D,Southampton,NaN,D
375,0,9,8,6,1,0,Fulham,19/05/13,3,0,...,0,2,19,11,1,0,A,Swansea,NaN,A
376,1,12,6,4,3,1,Sunderland,19/05/13,0,1,...,0,1,23,19,0,0,D,Tottenham,NaN,H
377,5,6,12,8,1,0,Man United,19/05/13,5,5,...,0,0,15,8,3,1,A,West Brom,NaN,D
378,4,8,17,7,1,0,Reading,19/05/13,2,4,...,0,2,21,12,0,2,H,West Ham,NaN,H
379,2,12,5,2,1,0,Aston Villa,19/05/13,2,2,...,0,2,12,6,1,2,H,Wigan,NaN,D

In [39]:
stad = pd.read_csv('/home/llevin/Desktop/capstone2/databases/other/stadiums-with-GPS-coordinates.csv')

In [40]:
stad.head()

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England

In [37]:
weather = pd.read_table('/home/llevin/Desktop/capstone2/weather_data/raw_weather.txt')

In [38]:
weather.head()

                      #DEBUG: Format Typ    -> comma
0  #DEBUG: Time Period   -> 2000-01-01 00:00:00+0...
1                   #DEBUG: Time Zone     -> Etc/UTC
2  #DEBUG: Data Contact   -> daryl herzmann akrhe...
3                        #DEBUG: Entries Found -> -1
4  station,valid,lon,lat, tmpf ,  dwpf ,  relh , ...

In [39]:
weather_clean = weather.iloc[4:]

In [40]:
weather_clean.head()

                      #DEBUG: Format Typ    -> comma
4  station,valid,lon,lat, tmpf ,  dwpf ,  relh , ...
5  EGLC,2000-01-01 10:20,0.0553,51.5053,48.20,44....
6  EGLL,2000-01-01 15:20,-0.4614,51.4785,48.20,44...
7  EGKK,2000-01-01 15:20,-0.1903,51.1481,48.20,44...
8  EGLL,2000-01-01 15:50,-0.4614,51.4785,48.20,44...

In [41]:
weather.columns

Index([u'#DEBUG: Format Typ    -> comma'], dtype='object')

In [42]:
len(weather_clean)

6659639

In [ ]:
weather_cl = pd.DataFrame(map(lambda x: x.split(','),weather_clean['#DEBUG: Format Typ    -> comma']),
                          columns=['station','date','long','lat','temp (F)','dew (F)','humidity','wind direction',
                                  'wind speed (mph)','prec (in)','visibility (mi)'])

In [ ]:
weather_cl.drop(0,inplace=True)
weather_cl.head()

In [ ]:
len(weather_cl)

In [ ]:
weather_cl.to_csv('/home/llevin/Desktop/capstone/weather_data/weather_df.csv')

In [41]:
weather_cl = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/weather_df.csv')

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (5,6,7,9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [42]:
weather_cl['prec (in)'].value_counts()

0.0      5273665
M        1327853
0.00       47694
24.0        3739
0.01        2213
0.02         967
0.03         556
0.04         406
0.01         290
0.05         281
0.06         226
0.07         161
0.02         138
0.08         120
0.09          99
0.1           91
0.03          84
0.12          62
0.11          57
0.04          55
0.13          41
0.15          37
0.05          33
0.14          31
0.16          28
0.06          23
0.07          21
0.09          17
24.2          15
0.18          15
          ...
8.8            1
5.92           1
0.48           1
14.59          1
15.8           1
13.49          1
18.05          1
22.59          1
4.58           1
22.52          1
12.59          1
0.94           1
13.94          1
13.82          1
27.2           1
16.69          1
7.76           1
15.99          1
2.96           1
11.33          1
1.77           1
16.4           1
7.22           1
0.78           1
4.77           1
8.52           1
8.21           1
15.08          1
0.16           1
23.54          1
Name: prec (in), dtype: int64

In [43]:
stations = weather_cl[['station','long','lat']]
print len(stations)
stations.drop_duplicates(inplace=True)
print len(stations)
stations.reset_index(inplace=True,drop=True)
stations.head()

6659638
107

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/pandas/util/decorators.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)

  station    long      lat
0    EGLC  0.0553  51.5053
1    EGLL -0.4614  51.4785
2    EGKK -0.1903  51.1481
3    EGDL -1.9924  51.5032
4    EGDM -1.7546  51.1618

In [44]:
def weather_merge(stadiums, stations):
    #for each lat/long stadium, find the minimum haversine distance and append that weather station
    for index1 in stadiums.index:
        haversines = []
        for index2 in stations.index:
            h = haversine([stadiums.ix[index1,'Latitude'],stadiums.ix[index1,'Longitude']],
                                       [stations.ix[index2,'lat'],stations.ix[index2,'long']])
            haversines.append([h, index2])
        haversines = sorted(haversines, key=lambda x: x[0])
        min_hav = haversines[0]
        min_station = stations.ix[min_hav[1],'station']
        stadiums.ix[index1,'closest_station'] = min_station
    return stadiums

In [56]:
stadiums = weather_merge(stad,stations)
stadiums.head()

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England,EGLC
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England,EGBB
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England,EGNO
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England,EGNO
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England,EGLC

In [121]:
premier_data['home_team'][premier_data['home_team']=='Middlesboro']='Middlesbrough'

In [122]:
premier_data[premier_data['home_team']=='Middlesbrough']

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_red_cards,home_yellow_cards,home_shots,home_shots_target,half_time_away_goals,half_time_home_goals,half_time_result,home_team,Referee,result
4,9,12,8,5,2,0,Tottenham,16/08/08,1,2,...,0,1,14,10,0,0,D,Middlesbrough,M Atkinson,H
24,5,18,7,2,4,1,Stoke,30/08/08,1,2,...,0,2,21,12,0,1,H,Middlesbrough,M Dean,H
54,8,13,14,9,4,0,West Brom,27/09/08,1,0,...,0,2,22,13,0,0,D,Middlesbrough,C Foy,A
75,7,9,21,14,0,0,Chelsea,18/10/08,5,0,...,0,2,7,4,1,0,A,Middlesbrough,P Dowd,A
97,3,15,13,8,3,0,Man City,29/10/08,0,2,...,0,1,5,3,0,0,D,Middlesbrough,L Mason,H
102,4,14,13,8,4,0,West Ham,01/11/08,1,1,...,0,3,11,7,1,0,A,Middlesbrough,A Marriner,D
133,0,15,11,5,5,0,Bolton,22/11/08,3,1,...,0,2,18,5,2,0,A,Middlesbrough,M Atkinson,A
140,2,7,10,5,1,0,Newcastle,29/11/08,0,0,...,0,1,14,7,0,0,D,Middlesbrough,A Wiley,D
162,10,11,17,11,1,0,Arsenal,13/12/08,1,1,...,0,0,8,3,1,1,D,Middlesbrough,P Walton,D
182,8,14,11,6,1,0,Everton,26/12/08,1,0,...,0,5,7,5,0,0,D,Middlesbrough,M Riley,A
201,7,13,10,5,4,0,Sunderland,10/01/09,1,1,...,0,0,9,3,0,1,H,Middlesbrough,P Dowd,D
233,9,16,15,10,4,0,Blackburn,31/01/09,0,0,...,0,0,7,4,0,0,D,Middlesbrough,C Foy,D
253,1,15,12,6,4,0,Wigan,21/02/09,0,0,...,0,2,6,3,0,0,D,Middlesbrough,M Dean,D
262,9,6,16,7,0,0,Liverpool,28/02/09,0,2,...,0,2,5,3,0,1,H,Middlesbrough,R Styles,H
284,4,11,8,4,3,0,Portsmouth,14/03/09,1,1,...,1,1,16,11,1,0,A,Middlesbrough,M Atkinson,D
311,3,16,12,6,3,0,Hull,11/04/09,1,3,...,0,3,15,9,1,2,H,Middlesbrough,P Dowd,H
320,1,14,11,6,1,0,Fulham,18/04/09,0,0,...,0,3,18,14,0,0,D,Middlesbrough,P Walton,D
341,3,7,13,4,1,0,Man United,02/05/09,2,0,...,0,1,11,5,1,0,A,Middlesbrough,M Halsey,A
363,8,16,8,6,2,0,Aston Villa,16/05/09,1,1,...,0,0,10,6,0,1,H,Middlesbrough,M Riley,D
4,3,16,4,4,4,0,Blackburn,11/08/07,2,1,...,0,3,10,6,0,1,H,Middlesbrough,A Marriner,A
36,2,10,5,3,3,0,Newcastle,26/08/07,2,2,...,0,6,11,7,1,1,D,Middlesbrough,M Dean,D
41,5,12,9,4,3,0,Birmingham,01/09/07,0,2,...,0,1,13,7,0,2,H,Middlesbrough,R Styles,H
60,2,11,11,6,4,0,Sunderland,22/09/07,2,2,...,0,3,16,5,1,1,D,Middlesbrough,H Webb,D
93,6,9,9,6,1,0,Chelsea,20/10/07,2,0,...,0,1,7,4,1,0,A,Middlesbrough,M Halsey,A
112,7,8,9,4,0,0,Tottenham,03/11/07,1,1,...,0,1,5,3,1,0,A,Middlesbrough,M Dean,D
133,6,17,11,8,1,0,Aston Villa,24/11/07,3,0,...,0,2,15,8,1,0,A,Middlesbrough,K Stroud,A
157,4,13,7,4,2,0,Arsenal,09/12/07,1,2,...,0,2,13,7,0,1,H,Middlesbrough,H Webb,H
174,4,12,8,4,3,0,West Ham,22/12/07,2,1,...,0,2,7,2,1,1,D,Middlesbrough,M Atkinson,A
203,6,11,5,3,1,0,Everton,01/01/08,2,0,...,0,0,7,4,0,0,D,Middlesbrough,M Riley,A
215,9,11,14,7,1,0,Liverpool,12/01/08,1,1,...,0,1,8,3,0,1,H,Middlesbrough,A Marriner,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,7,11,10,3,1,0,Charlton,13/12/03,0,0,...,0,1,12,6,0,0,D,Middlesbrough,H Webb,D
183,2,15,10,6,2,1,Man United,28/12/03,1,0,...,0,3,11,2,1,0,A,Middlesbrough,M Messias,A
193,1,17,9,4,2,0,Fulham,07/01/04,1,2,...,0,1,10,5,0,1,H,Middlesbrough,P Durkin,H
211,6,12,14,8,5,0,Leicester,17/01/04,3,3,...,0,2,13,7,0,1,H,Middlesbrough,B Knight,D
232,3,12,6,2,1,0,Blackburn,07/02/04,1,0,...,0,0,15,7,1,0,A,Middlesbrough,R Styles,A
268,5,15,10,2,1,0,Tottenham,09/03/04,0,1,...,0,1,10,6,0,0,D,Middlesbrough,A D'Urso,H
286,4,13,18,12,0,0,Birmingham,20/03/04,3,5,...,0,2,13,9,2,4,H,Middlesbrough,U Rennie,H
301,8,15,13,8,2,0,Bolton,03/04/04,0,2,...,0,2,10,6,0,1,H,Middlesbrough,N Barry,H
321,3,14,16,8,0,0,Southampton,12/04/04,1,3,...,0,0,25,18,0,2,H,Middlesbrough,D Gallagher,H
342,8,15,12,9,1,1,Aston Villa,24/04/04,2,1,...,0,0,31,21,1,1,D,Middlesbrough,G Barber,A
364,4,14,14,6,1,0,Man City,08/05/04,1,2,...,0,1,12,7,1,2,H,Middlesbrough,M Riley,H
15,11,7,10,4,2,0,Fulham,24/08/2002,2,2,...,0,4,6,3,0,1,H,Middlesbrough,M Dean,D
29,6,16,10,7,3,0,Blackburn,31/08/2002,0,1,...,0,3,7,3,0,0,D,Middlesbrough,M Halsey,H
39,8,12,8,6,3,0,Sunderland,10/09/2002,0,3,...,0,3,9,7,0,2,H,Middlesbrough,A Wiley,H
61,3,13,12,3,4,0,Birmingham,21/09/2002,0,1,...,0,3,9,4,0,1,H,Middlesbrough,A D'Urso,H
78,5,10,11,4,3,0,Bolton,05/10/2002,0,2,...,0,0,13,2,0,1,H,Middlesbrough,C Wilkes,H
104,2,17,7,7,2,1,Leeds,26/10/2002,2,2,...,1,3,16,7,1,1,D,Middlesbrough,R Styles,D
125,2,8,13,7,0,0,Liverpool,09/11/2002,0,1,...,0,1,11,3,0,0,D,Middlesbrough,M Halsey,H
144,6,12,9,5,3,1,Man City,23/11/2002,1,3,...,0,0,18,7,0,0,D,Middlesbrough,N Barry,H
165,7,13,14,8,1,0,West Ham,07/12/2002,2,2,...,0,1,12,5,0,0,D,Middlesbrough,G Poll,D
173,8,14,16,11,1,0,Chelsea,14/12/2002,1,1,...,0,0,9,6,1,1,D,Middlesbrough,M Messias,D
194,8,12,14,6,1,0,Man United,26/12/2002,1,3,...,0,1,13,5,0,1,H,Middlesbrough,G Barber,H
221,4,10,17,8,2,0,Southampton,11/01/2003,2,2,...,0,0,12,4,1,0,A,Middlesbrough,D Elleray,D
241,3,11,15,9,2,0,Aston Villa,28/01/2003,5,2,...,0,1,13,8,2,2,D,Middlesbrough,D Gallagher,A
281,2,8,11,5,0,0,Everton,01/03/2003,1,1,...,0,0,6,2,1,0,A,Middlesbrough,U Rennie,D
288,9,16,11,0,3,0,Newcastle,05/03/2003,0,1,...,0,0,10,4,0,0,D,Middlesbrough,A D'Urso,H
303,4,10,6,4,2,0,Charlton,22/03/2003,1,1,...,0,1,15,6,1,0,A,Middlesbrough,M Dean,D
314,5,15,12,6,1,0,West Brom,05/04/2003,0,3,...,0,0,22,12,0,1,H,Middlesbrough,M Halsey,H
337,5,12,6,2,1,0,Arsenal,19/04/2003,2,0,...,0,0,7,3,0,0,D,Middlesbrough,D Elleray,A
364,3,9,6,4,2,1,Tottenham,03/05/2003,1,5,...,0,0,26,16,0,3,H,Middlesbrough,U Rennie,H

In [123]:
premier_data['home_team'].value_counts()

Arsenal             285
Liverpool           285
Tottenham           285
Aston Villa         285
Man United          285
Chelsea             285
Everton             285
Newcastle           266
Man City            266
Fulham              247
Sunderland          228
West Ham            228
Blackburn           209
Bolton              209
West Brom           171
Middlesbrough       171
Wigan               152
Southampton         152
Birmingham          133
Portsmouth          133
Charlton            133
Stoke               133
Swansea              76
Norwich              76
Wolves               76
Leeds                76
Hull                 76
Leicester            76
QPR                  57
Crystal Palace       57
Reading              57
Derby                57
Ipswich              38
Burnley              38
Watford              19
Sheffield United     19
Blackpool            19
Bradford             19
Coventry             19
Cardiff              19
Name: home_team, dtype: int64

In [124]:
premier_stad = premier_data.merge(stadiums.iloc[:,1:10],how='left',left_on='home_team',right_on='FDCOUK')

In [125]:
premier_stad.head()

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,Referee,result,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,3,19,4,2,2,1,Crystal Palace,16/08/14,1,2,...,J Moss,H,Arsenal,London,Emirates Stadium,60361.0,51.555000,-0.108611,England,EGLC
1,6,10,13,3,1,0,Everton,16/08/14,2,2,...,M Jones,D,Leicester,Leicester,King Power Stadium,32500.0,52.620278,-1.142222,England,EGNX
2,0,20,5,4,4,0,Swansea,16/08/14,2,1,...,M Dean,A,Man United,Stretford,Old Trafford,75811.0,53.463056,-2.291389,England,EGCC
3,9,10,11,4,2,0,Hull,16/08/14,1,0,...,C Pawson,A,QPR,London,Loftus Road,18439.0,51.509167,-0.232222,England,EGWU
4,8,9,7,2,3,0,Aston Villa,16/08/14,1,0,...,A Taylor,A,Stoke,Stoke-on-Trent,Britannia Stadium,27740.0,52.988333,-2.175556,England,EGOS

In [61]:
pd.set_option('display.max_rows',60)
premier_stad[['home_team','FDCOUK']]

           home_team          FDCOUK
0            Arsenal         Arsenal
1          Leicester       Leicester
2         Man United      Man United
3                QPR             QPR
4              Stoke           Stoke
5          West Brom       West Brom
6           West Ham        West Ham
7          Liverpool       Liverpool
8          Newcastle       Newcastle
9            Burnley         Burnley
10       Aston Villa     Aston Villa
11           Chelsea         Chelsea
12    Crystal Palace  Crystal Palace
13           Everton         Everton
14       Southampton     Southampton
15           Swansea         Swansea
16              Hull            Hull
17        Sunderland      Sunderland
18         Tottenham       Tottenham
19          Man City        Man City
20           Burnley         Burnley
21           Everton         Everton
22          Man City        Man City
23         Newcastle       Newcastle
24               QPR             QPR
25           Swansea         Swansea
26          West Ham        West Ham
27       Aston Villa     Aston Villa
28         Leicester       Leicester
29         Tottenham       Tottenham
...              ...             ...
5670       Liverpool       Liverpool
5671        Man City        Man City
5672       Newcastle       Newcastle
5673     Southampton     Southampton
5674        Charlton             NaN
5675       Tottenham       Tottenham
5676       West Brom       West Brom
5677          Fulham          Fulham
5678     Aston Villa     Aston Villa
5679       Blackburn       Blackburn
5680         Chelsea         Chelsea
5681  Crystal Palace  Crystal Palace
5682         Everton         Everton
5683      Man United      Man United
5684   Middlesbrough   Middlesbrough
5685         Norwich         Norwich
5686      Portsmouth      Portsmouth
5687         Arsenal         Arsenal
5688      Man United      Man United
5689         Arsenal         Arsenal
5690      Birmingham      Birmingham
5691          Bolton          Bolton
5692        Charlton             NaN
5693          Fulham          Fulham
5694       Liverpool       Liverpool
5695        Man City        Man City
5696       Newcastle       Newcastle
5697     Southampton     Southampton
5698       Tottenham       Tottenham
5699       West Brom       West Brom

[5700 rows x 2 columns]

In [126]:
premier_stad.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
away_team                 0
Date                      0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 380
result                    0
FDCOUK                  171
City                    171
Stadium                 171
Capacity                171
Latitude                171
Longitude               171
Country                 171
closest_station         171
dtype: int64

In [127]:
premier_stad[premier_stad['FDCOUK'].isnull()].groupby('home_team').count().reset_index()

,home_team,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,...,Referee,result,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,Bradford,19,19,19,19,19,19,19,19,19,...,19,19,0,0,0,0,0,0,0,0
1,Charlton,133,133,133,133,133,133,133,133,133,...,133,133,0,0,0,0,0,0,0,0
2,Sheffield United,19,19,19,19,19,19,19,19,19,...,19,19,0,0,0,0,0,0,0,0

In [54]:
pd.set_option('display.max_rows',None)
stad.sort_values('FDCOUK')

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
56,Aberdeen and Inverness C.T.,Aberdeen,Aberdeen,Pittodrie Stadium,22199,57.159167,-2.088889,Scotland,EGPD
108,Ajaccio,Ajaccio,Ajaccio,Stade François Coty,10660,41.931081,8.776725,France,EGMD
85,Almería,Almeria,Almería,Estadio del Mediterráneo,22000,36.840000,-2.435278,Spain,EGJJ
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England,EGLC
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England,EGBB
86,Athletic Bilbao,Ath Bilbao,Bilbao,San Mamés,53332,43.264284,-2.950366,Spain,EGJJ
87,Atlético Madrid,Ath Madrid,Madrid,Vicente Calderón,54851,40.401719,-3.720606,Spain,EGJJ
62,FC Augsburg,Augsburg,Augsburg,SGL arena,30660,48.322500,10.882222,Germany,EGMH
131,Auxerre,Auxerre,Auxerre,Stade de l'Abbé-Deschamps,24493,47.786753,3.588664,France,EGMD
88,Barcelona,Barcelona,Barcelona,Camp Nou,99354,41.380870,2.122802,Spain,EGJJ
20,Barnsley,Barnsley,Barnsley,Oakwell,23009,53.552222,-1.467500,England,EGCN
109,Bastia,Bastia,Bastia,Stade Armand Cesari,16480,42.651400,9.442619,France,EGMD
64,Bayern Munich,Bayern Munich,Munich,Allianz Arena,71000,48.218775,11.624753,Germany,EGMH
89,Betis,Betis,Seville,Benito Villamarín,52500,37.356389,-5.981389,Spain,EGJJ
21,Birmingham City,Birmingham,Birmingham,St Andrew's Stadium,30079,52.475703,-1.868189,England,EGBB
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England,EGNO
22,Blackpool,Blackpool,Blackpool,Bloomfield Road,16220,53.804722,-3.048056,England,EGNH
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England,EGNO
110,Bordeaux,Bordeaux,Bordeaux,Stade Chaban-Delmas,34462,44.829167,-0.597778,France,EGJJ
67,Eintracht Braunschweig,Braunschweig,Braunschweig,Eintracht-Stadion,23325,52.290000,10.521667,Germany,EGSD
132,Brest,Brest,Brest,Stade Francis-Le Blé,16000,48.402932,-4.461694,France,EGJB
23,Brighton & Hove Albion,Brighton,Brighton,American Express Community Stadium,22374,50.861822,-0.083278,England,EGKA
24,Bristol City,Bristol City,Bristol,Ashton Gate,21497,51.440000,-2.620278,England,EGTG
25,Burnley,Burnley,Burnley,Turf Moor,22546,53.789167,-2.230278,England,EGNM
133,Caen,Caen,Caen,Stade Michel d'Ornano,21500,49.179461,-0.396767,France,EGJJ
26,Cardiff City,Cardiff,Cardiff,Cardiff City Stadium,26828,51.472778,-3.203056,England,EGFF
90,Celta de Vigo,Celta,Vigo,Balaídos,31800,42.211842,-8.739711,Spain,EGHE
46,Celtic,Celtic,Glasgow,Celtic Park,60832,55.849711,-4.205589,Scotland,EGPF
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England,EGLC
27,Coventry City,Coventry,Coventry,Ricoh Arena,32609,52.448056,-1.495556,England,EGBE
28,Crystal Palace,Crystal Palace,London,Selhurst Park,26309,51.398333,-0.085556,England,EGKB
29,Derby County,Derby,Derby,Pride Park Stadium,33597,52.915000,-1.447222,England,EGNX
129,Dijon,Dijon,Dijon,Stade Gaston Gérard,15998,47.324383,5.068342,France,EGMD
30,Doncaster Rovers,Doncaster,Doncaster,Keepmoat Stadium,15231,53.509722,-1.113889,England,EGCN
65,Borussia Dortmund,Dortmund,Dortmund,Signal Iduna Park,80645,51.492569,7.451842,Germany,EGSD
47,Dundee,Dundee,Dundee,Dens Park,12085,56.475264,-2.973194,Scotland,EGPN
59,Dundee United,Dundee United,Dundee,Tannadice Park,14209,56.474703,-2.968961,Scotland,EGPN
48,Dunfermline Athletic,Dunfermline,Dunfermline,East End Park,11380,56.075308,-3.441906,Scotland,EGPH
68,Eintracht Frankfurt,Ein Frankfurt,Frankfurt,Commerzbank-Arena,51500,50.068572,8.645458,Germany,EGMH
91,Elche,Elche,Elche,Martínez Valero,36017,38.266944,-0.663333,Spain,EGJJ
92,Espanyol,Espanol,Cornellà de Llobregat,Cornellà-El Prat,40500,41.347861,2.075667,Spain,EGJJ
5,Everton,Everton,Liverpool,Goodison Park,40157,53.438889,-2.966389,England,EGGP
111,Évian,Evian Thonon Gaillard,Annecy,Parc des Sports,15660,45.916497,6.118054,France,EGMD
83,1. FC Köln,FC Koln,Cologne,RheinEnergieStadion,50000,50.933497,6.874997,Germany,EGMH
50,Falkirk,Falkirk,Falkirk,Falkirk Stadium,9200,56.005136,-3.754269,Scotland,EGPH
80,Fortuna Düsseldorf,Fortuna Dusseldorf,Düsseldorf,Esprit Arena,54600,51.261667,6.733056,Germany,EGMH
69,SC Freiburg,Freiburg,Freiburg,MAGE SOLAR Stadion,24000,47.988889,7.893056,Germany,EGMH
6,Fulham,Fulham,London,Craven Cottage,25700,51.475000,-0.221667,England,EGWU
93,Getafe,Getafe,Getafe,Coliseum Alfonso Pérez,17700,40.325556,-3.714722,Spain,EGJJ
94,Granada,Granada,Granada,Nuevo Los Cármenes,22524,37.152967,-3.595736,Spain,EGJJ
81,SpVgg Greuther Fürth,Greuther Furth,Fürth,Trolli Arena,18000,49.486944,10.999167,Germany,EGMH
112,Guingamp,Guingamp,Guingamp,Stade du Roudourou,18126,48.566285,-3.164599,France,EGJJ
70,Hamburger SV,Hamburg,Hamburg,Imtech Arena,57000,53.587158,9.898617,Germany,EGSD
55,Hamilton Academical,Hamilton,Hamilton,New Douglas Park,6078,55.782156,-4.058503,Scotland,EGPF
71,Hannover 96,Hannover,Hanover,HDI-Arena,49000,52.360067,9.731197,Germany,EGSD
60,Heart of Midlothian,Hearts,Edinburgh,Tynecastle Stadium,17420,55.939167,-3.232222,Scotland,EGPH
72,Hertha BSC,Hertha,Berlin,Olympiastadion,74244,52.514722,13.239444,Germany,EGSD
49,Hibernian,Hibernian,Edinburgh,Easter Road,20421,55.961667,-3.165556,Scotland,EGPH
73,TSG 1899 Hoffenheim,Hoffenheim,Sinsheim,Rhein-Neckar Arena,30150,49.239008,8.888281,Germany,EGMH
31,Hull City,Hull,Kingston upon Hull,KC Stadium,25404,53.746111,-0.367778,England,EGXV
45,Inverness C.T.,Inverness C,Iverness,Caledonian Stadium,7918,57.494722,-4.217500,Scotland,EGPE
32,Ipswich Town,Ipswich,Ipswich,Portman Road,30311,52.055061,1.144831,England,EGUW
82,1. FC Kaiserslautern,Kaiserslautern,Kaiserslautern,Fritz-Walter-Stadion,49780,49.434722,7.776667,Germany,EGMH
57,Kilmarnock,Kilmarnock,Kilmarnock,Rugby Park,18128,55.604225,-4.508122,Scotland,EGPK
105,Deportivo La Coruña,La Coruna,A Coruña,Riazor,34600,43.368714,-8.417516,Spain,EGHE
33,Leeds United,Leeds,Leeds,Elland Road,39460,53.777778,-1.572222,England,EGNM
34,Leicester City,Leicester,Leicester,King Power Stadium,32500,52.620278,-1.142222,England,EGNX
95,Levante,Levante,Valencia,Ciutat de València,25534,39.494722,-0.364167,Spain,EGJJ
63,Bayer Leverkusen,Leverkusen,Leverkusen,BayArena,30210,51.038256,7.002206,Germany,EGMH
113,Lille,Lille,Villeneuve-d'Ascq,Stade Pierre-Mauroy,50186,50.611883,3.130428,France,EGMH
7,Liverpool,Liverpool,Liverpool,Anfield,45276,53.430819,-2.960828,England,EGGP
44,Livingston and Gretna,Livingston,Livingston,Almondvale Stadium,10122,55.886167,-3.522872,Scotland,EGPH
114,Lorient,Lorient,Lorient,Stade du Moustoir,18890,47.748747,-3.369367,France,EGJJ
115,Lyon,Lyon,Lyon,Stade de Gerland,41842,45.723889,4.832222,France,EGMD
66,Borussia Mönchengladbach,M'gladbach,Mönchengladbach,Borussia-Park,54010,51.174583,6.385464,Germany,EGMH
74,1. FSV Mainz 05,Mainz,Mainz,Coface Arena,34000,49.984167,8.224167,Germany,EGMH
96,Málaga,Malaga,Málaga,La Rosaleda,30044,36.734092,-4.426422,Spain,EGJJ
106,Mallorca,Mallorca,Palma,Iberostar Stadium,23142,39.590000,2.630000,Spain,EGJJ
8,Manchester City,Man City,Manchester,Etihad Stadium,47405,53.482989,-2.200292,England,EGCC
9,Manchester United,Man United,Stretford,Old Trafford,75811,53.463056,-2.291389,England,EGCC
116,Marseille,Marseille,Marseille,Stade Velodrome,48000,43.269722,5.395833,France,EGJJ
35,Middlesbrough,Middlesbrough,Middlesbrough,Riverside Stadium,34988,54.578333,-1.216944,England,EGNV
36,Millwall,Millwall,London,The Den,20146,51.485953,-0.050950,England,EGLC
117,AS Monaco,Monaco,Monaco,Stade Louis II,18500,43.727606,7.415614,France,EGMD
118,Montpellier,Montpellier,Montpellier,Stade de la Mosson,32939,43.622222,3.811944,France,EGJJ
51,Motherwell and Gretna,Motherwell,Motherwell,Fir Park,13742,55.779947,-3.980078,Scotland,EGPF
128,Nancy,Nancy,Tomblaine,Stade Marcel Picot,20085,48.695500,6.210687,France,EGMD
119,Nantes,Nantes,Nantes,Stade de la Beaujoire,38285,47.255631,-1.525375,France,EGJJ
10,Newcastle United,Newcastle,Newcastle upon Tyne,Sports Direct Arena,52409,54.975556,-1.621667,England,EGNT
120,Nice,Nice,Nice,Allianz Riviera,35624,43.723328,7.258756,France,EGMD
11,Norwich City,Norwich,Norwich,Carrow Road,27010,52.622128,1.308653,England,EGSH
37,Nottingham Forest,Nott'm Forest,Nottingham,City Ground,30576,52.940000,-1.132778,England,EGNX
75,1. FC Nürnberg,Nurnberg,Nuremberg,Grundig-Stadion,50000,49.426111,11.125833,Germany,EGMH
97,Osasuna,Osasuna,Pamplona,El Sadar,19553,42.796667,-1.636944,Spain,EGJJ
121,Paris Saint-Germain,Paris SG,Paris,Parc des Princes,48712,48.841389,2.253056,France,EGMD
52,Partick Thistle,Partick,Glasgow,Firhill Stadium,10887,55.881556,-4.269639,Scotland,EGPF
38,Peterborough United,Peterboro,Peterborough,London Road Stadium,15460,52.564697,-0.240406,England,EGXT
39,Portsmouth,Portsmouth,Portsmouth,Fratton Park,20224,50.796389,-1.063889,England,EGHI
12,Queens Park Rangers,QPR,London,Loftus Road,18439,51.509167,-0.232222,England,EGWU
53,Rangers,Rangers,Glasgow,Ibrox Stadium,51082,55.853206,-4.309258,Scotland,EGPF
40,Reading,Reading,Reading,Madejski Stadium,24224,51.422222,-0.982778,England,EGVO
99,Real Madrid,Real Madrid,Madrid,Santiago Bernabéu,85454,40.453060,-3.688350,Spain,EGJJ
122,Reims,Reims,Reims,Stade Auguste-Delaune II,21684,49.246667,4.025000,France,EGMD
123,Rennes,Rennes,Rennes,Stade de la Route de Lorient,31127,48.107458,-1.712839,France,EGJJ
61,Ross County,Ross County,Dingvall,Victoria Park,6310,57.595947,-4.418914,Scotland,EGPE
135,Racing de Santander,Santander,Santander,Campos de Sport de El Sardinero,22222,43.476389,-3.793333,Spain,EGJJ
76,Schalke 04,Schalke 04,Gelsenkirchen,Veltins-Arena,61673,51.554503,7.067589,Germany,EGSD
101,Sevilla,Sevilla,Seville,Ramón Sánchez Pizjuán,45500,37.384000,-5.970500,Spain,EGJJ
125,Sochaux,Sochaux,Montbéliard,Stade Auguste Bonal,20005,47.512417,6.811200,France,EGMD
100,Real Sociedad,Sociedad,San Sebastián,Anoeta,32076,43.301378,-1.973617,Spain,EGJJ
41,Southampton,Southampton,Southampton,St Mary's Stadium,32689,50.905833,-1.391111,England,EGHI
134,Sporting de Gijón,Sp Gijon,Gijón,El Molinón,30000,43.536111,-5.637222,Spain,EGJJ
124,Saint-Étienne,St Etienne,Saint-Étienne,Stade Geoffroy-Guichard,26747,45.460833,4.390278,France,EGJJ
54,St. Johnstone,St Johnstone,Perth,McDiarmid Park,10673,56.409686,-3.476928,Scotland,EGPN
58,St. Mirren,St Mirren,Paisley,St. Mirren Park,8016,55.850556,-4.443889,Scotland,EGPF
84,FC St. Pauli,St Pauli,Hamburg,Millerntor-Stadion,24487,53.554444,9.967778,Germany,EGSD
13,Stoke City,Stoke,Stoke-on-Trent,Britannia Stadium,27740,52.988333,-2.175556,England,EGOS
77,VfB Stuttgart,Stuttgart,Stuttgart,Mercedes-Benz Arena,60441,48.792269,9.232031,Germany,EGMH
14,Sunderland,Sunderland,Sunderland,Stadium of Light,48707,54.914400,-1.388200,England,EGNT
15,Swansea City,Swansea,Swansea,Liberty Stadium,20520,51.642200,-3.935100,England,EGOP
16,Tottenham Hotspur,Tottenham,London,White Hart Lane,36230,51.603333,-0.065833,England,EGLC
126,Toulouse,Toulouse,Toulouse,Stadium Municipal,35470,43.583056,1.434167,France,EGJJ
130,Troyes,Troyes,Troyes,Stade de l'Aube,21877,48.307561,4.098458,France,EGMD
102,Valencia,Valencia,Valencia,Mestalla,55000,39.474656,-0.358361,Spain,EGJJ
127,Valenciennes,Valenciennes,Valenciennes,Stade du Hainaut,25172,50.348131,3.533027,France,EGMH
103,Valladolid,Valladolid,Valladolid,Nuevo José Zorrilla,26512,41.644444,-4.761111,Spain,EGJJ
98,Rayo Vallecano,Vallecano,Madrid,Campo de Vallecas,15489,40.391944,-3.658961,Spain,EGJJ
104,Villarreal,Villarreal,Villarreal,El Madrigal,24890,39.944167,-0.103611,Spain,EGJJ
42,Watford,Watford,Watford,Vicarage Road,23500,51.649836,-0.401486,England,EGWU
78,Werder Bremen,Werder Bremen,Bremen,Weserstadion,42100,53.066394,8.837628,Germany,EGSD
17,West Bromwich Albion,West Brom,West Bromwich,The Hawthorns,27877,52.509167,-1.963889,England,EGBB
43,West Ham United,West Ham,London,Boleyn Ground,35303,51.531944,0.039444,England,EGLC
18,Wigan Athletic,Wigan,Wigan,DW Stadium,25133,53.547778,-2.653889,England,EGNO
79,VfL Wolfsburg,Wolfsburg,Wolfsburg,Volkswagen Arena,30000,52.431944,10.803889,Germany,EGSD
19,Wolverhampton Wanderers,Wolves,Wolverhampton,Molineux Stadium,27828,52.590278,-2.130278,England,EGWC
107,Zaragoza,Zaragoza,Zaragoza,La Romareda,34596,41.636592,-0.901822,Spain,EGJJ

In [128]:
premier_stad = premier_stad[~premier_stad['FDCOUK'].isnull()]

In [129]:
premier_stad.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
away_team                 0
Date                      0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 380
result                    0
FDCOUK                    0
City                      0
Stadium                   0
Capacity                  0
Latitude                  0
Longitude                 0
Country                   0
closest_station           0
dtype: int64

In [130]:
premier_stad.columns

Index([u'away_corners', u'away_fouls', u'away_shots', u'away_shots_target',
       u'away_yellow_cards', u'away_red_cards', u'away_team', u'Date',
       u'full_time_away_goals', u'full_time_home_goals', u'home_corners',
       u'home_fouls', u'home_red_cards', u'home_yellow_cards', u'home_shots',
       u'home_shots_target', u'half_time_away_goals', u'half_time_home_goals',
       u'half_time_result', u'home_team', u'Referee', u'result', u'FDCOUK',
       u'City', u'Stadium', u'Capacity', u'Latitude', u'Longitude', u'Country',
       u'closest_station'],
      dtype='object')

In [131]:
premier_stad.head()

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,Referee,result,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,3,19,4,2,2,1,Crystal Palace,16/08/14,1,2,...,J Moss,H,Arsenal,London,Emirates Stadium,60361.0,51.555000,-0.108611,England,EGLC
1,6,10,13,3,1,0,Everton,16/08/14,2,2,...,M Jones,D,Leicester,Leicester,King Power Stadium,32500.0,52.620278,-1.142222,England,EGNX
2,0,20,5,4,4,0,Swansea,16/08/14,2,1,...,M Dean,A,Man United,Stretford,Old Trafford,75811.0,53.463056,-2.291389,England,EGCC
3,9,10,11,4,2,0,Hull,16/08/14,1,0,...,C Pawson,A,QPR,London,Loftus Road,18439.0,51.509167,-0.232222,England,EGWU
4,8,9,7,2,3,0,Aston Villa,16/08/14,1,0,...,A Taylor,A,Stoke,Stoke-on-Trent,Britannia Stadium,27740.0,52.988333,-2.175556,England,EGOS

In [132]:
premier_stad.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v1.csv',index=False)

In [32]:
pd.read_sql('SELECT * FROM Match LIMIT 10', con=conn)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00

In [2]:
match_data = pd.read_sql('Select * from Match', con=conn)

In [3]:
match_data = match_data[match_data['league_id']==1729]

In [4]:
match_data['season'].value_counts()

2009/2010    380
2013/2014    380
2010/2011    380
2012/2013    380
2014/2015    380
2008/2009    380
2015/2016    380
2011/2012    346
Name: season, dtype: int64

In [5]:
match_data.head(3).T

,1728,1729,1730
id,1729,1730,1731
country_id,1729,1729,1729
league_id,1729,1729,1729
season,2008/2009,2008/2009,2008/2009
stage,1,1,1
date,2008-08-17 00:00:00,2008-08-16 00:00:00,2008-08-16 00:00:00
match_api_id,489042,489043,489044
home_team_api_id,10260,9825,8472
away_team_api_id,10261,8659,8650
home_team_goal,1,1,0
away_team_goal,1,0,1
home_player_X1,1,1,1
home_player_X2,2,2,2
home_player_X3,4,4,4
home_player_X4,6,6,6
home_player_X5,8,8,8
home_player_X6,2,2,2
home_player_X7,4,4,4
home_player_X8,6,6,6
home_player_X9,8,8,8
home_player_X10,4,4,4
home_player_X11,6,6,6
away_player_X1,1,1,1
away_player_X2,2,2,2
away_player_X3,4,4,4
away_player_X4,6,6,6
away_player_X5,8,8,8
away_player_X6,2,5,2
away_player_X7,4,7,4
away_player_X8,6,9,6
...,...,...,...
B365H,1.29,NaN,5.5
B365D,5.5,NaN,3.6
B365A,11,NaN,1.67
BWH,1.3,NaN,5
BWD,4.75,NaN,3.35
BWA,8.25,NaN,1.67
IWH,1.3,NaN,4.5
IWD,4.4,NaN,3.5
IWA,8.5,NaN,1.65
LBH,1.25,NaN,4.5
LBD,4.5,NaN,3.3
LBA,10,NaN,1.67
PSH,NaN,NaN,NaN
PSD,NaN,NaN,NaN
PSA,NaN,NaN,NaN
WHH,1.25,NaN,5.5
WHD,4.5,NaN,3.3
WHA,10,NaN,1.57
SJH,1.25,NaN,4.33
SJD,5,NaN,3.4
SJA,10,NaN,1.73
VCH,1.28,NaN,5.5
VCD,5.5,NaN,3.8
VCA,12,NaN,1.65
GBH,1.3,NaN,5
GBD,4.75,NaN,3.4
GBA,10,NaN,1.7
BSH,1.29,NaN,4.5
BSD,4.5,NaN,3.4
BSA,11,NaN,1.73

In [37]:
for column in match_data.columns:
    print column

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
away_player_5
away_player_6
away_player_7
away_player_8
away_player_9
away_player_10
away_player_11
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
B365H
B365D
B365A
BWH
BWD
BWA
IWH
IWD
IWA
LBH
LBD
LBA
PSH
PSD
PSA
WHH
WHD
WHA
SJH
SJD
SJA
VCH
VCD
VCA
GBH
GBD
GBA
BSH
BSD
BSA

In [8]:
match_data.to_csv('/home/llevin/Desktop/capstone2/raw_data/kaggle_data.csv',index=False)

In [6]:
team_data = pd.read_sql('Select * from Team', con=conn)

In [7]:
team_data.head()

   id  team_api_id team_long_name team_short_name
0   1         9987           Genk             GEN
1   2         9993   Beerschot AC             BAC
2   3        10000  Zulte-Waregem             ZUL
3   4         9994        Lokeren             LOK
4   5         9984  Cercle Bruges             CEB

In [8]:
match_team = match_data.merge(team_data[['team_api_id','team_long_name']],how='inner',\
                                                           left_on='home_team_api_id',right_on='team_api_id')

In [9]:
match_team.rename(columns={'team_long_name':'home_team'},inplace=True)

In [10]:
match_team = match_team.merge(team_data[['team_api_id','team_long_name']],how='inner',\
                                                           left_on='away_team_api_id',right_on='team_api_id')

In [11]:
match_team.rename(columns={'team_long_name':'away_team'},inplace=True)

In [12]:
match_team.isnull().sum()

id                     0
country_id             0
league_id              0
season                 0
stage                  0
date                   0
match_api_id           0
home_team_api_id       0
away_team_api_id       0
home_team_goal         0
away_team_goal         0
home_player_X1         0
home_player_X2         0
home_player_X3         0
home_player_X4         0
home_player_X5         0
home_player_X6         0
home_player_X7         0
home_player_X8         0
home_player_X9         0
home_player_X10        0
home_player_X11        0
away_player_X1         0
away_player_X2         0
away_player_X3         0
away_player_X4         0
away_player_X5         0
away_player_X6         0
away_player_X7         0
away_player_X8         0
                    ...
BWD                    9
BWA                    9
IWH                   10
IWD                   10
IWA                   10
LBH                    9
LBD                    9
LBA                    9
PSH                 1491
PSD                 1491
PSA                 1491
WHH                    8
WHD                    8
WHA                    8
SJH                  727
SJD                  727
SJA                  727
VCH                    8
VCD                    8
VCA                    8
GBH                 1146
GBD                 1146
GBA                 1146
BSH                 1145
BSD                 1145
BSA                 1145
team_api_id_x          0
home_team              0
team_api_id_y          0
away_team              0
dtype: int64

In [13]:
match_team['date'].head()

0    2008-08-17 00:00:00
1    2010-08-16 00:00:00
2    2011-11-26 00:00:00
3    2012-12-26 00:00:00
4    2013-12-07 00:00:00
Name: date, dtype: object

In [14]:
match_team['date'] = pd.to_datetime(match_team['date'])

In [15]:
match_team = match_team[['season','date','home_team_api_id','away_team_api_id','goal','shoton',\
                         'shotoff','foulcommit','card','cross','corner','possession','home_team','away_team']]

In [16]:
match_team.isnull().sum()

season              0
date                0
home_team_api_id    0
away_team_api_id    0
goal                0
shoton              0
shotoff             0
foulcommit          0
card                0
cross               0
corner              0
possession          0
home_team           0
away_team           0
dtype: int64

In [198]:
input_data = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v1.csv')

In [184]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5529 entries, 0 to 5528
Data columns (total 30 columns):
away_corners            5529 non-null int64
away_fouls              5529 non-null int64
away_shots              5529 non-null int64
away_shots_target       5529 non-null int64
away_yellow_cards       5529 non-null int64
away_red_cards          5529 non-null int64
away_team               5529 non-null object
Date                    5529 non-null object
full_time_away_goals    5529 non-null int64
full_time_home_goals    5529 non-null int64
home_corners            5529 non-null int64
home_fouls              5529 non-null int64
home_red_cards          5529 non-null int64
home_yellow_cards       5529 non-null int64
home_shots              5529 non-null int64
home_shots_target       5529 non-null int64
half_time_away_goals    5529 non-null int64
half_time_home_goals    5529 non-null int64
half_time_result        5529 non-null object
home_team               5529 non-null object
Referee                 5149 non-null object
result                  5529 non-null object
FDCOUK                  5529 non-null object
City                    5529 non-null object
Stadium                 5529 non-null object
Capacity                5529 non-null float64
Latitude                5529 non-null float64
Longitude               5529 non-null float64
Country                 5529 non-null object
closest_station         5529 non-null object
dtypes: float64(3), int64(16), object(11)
memory usage: 1.3+ MB

In [19]:
input_data['Date'].value_counts()

01/01/15      10
11/05/02      10
26/12/14      10
09/05/10      10
26/12/13      10
26/12/01      10
19/05/13      10
26/12/2002    10
13/05/12      10
26/12/04      10
01/01/14      10
24/05/15      10
26/12/08      10
11/05/14      10
23/12/06      10
07/05/06      10
22/05/11      10
24/05/09      10
11/05/08      10
11/05/2003     9
19/05/01       9
03/05/2003     9
13/05/07       9
12/04/2003     9
20/04/02       9
29/10/08       9
28/04/01       9
07/05/05       9
29/12/01       9
04/12/13       9
              ..
15/09/03       1
16/02/10       1
15/09/08       1
23/08/2002     1
29/12/08       1
30/01/01       1
29/03/10       1
13/02/11       1
17/03/04       1
24/04/12       1
22/12/00       1
12/02/01       1
20/09/04       1
14/04/06       1
17/12/12       1
16/01/12       1
16/01/13       1
28/02/05       1
24/01/05       1
23/08/10       1
10/03/10       1
07/03/11       1
11/01/12       1
11/01/10       1
16/03/15       1
16/03/10       1
09/03/02       1
17/03/08       1
26/08/13       1
05/05/08       1
Name: Date, dtype: int64

In [199]:
input_data['Date'] = pd.to_datetime(input_data['Date'])

In [200]:
print match_team['home_team'].sort_values().unique()
print input_data['home_team'].sort_values().unique()

[u'Arsenal' u'Aston Villa' u'Birmingham' u'Blackburn' u'Blackpool'
 u'Bolton' u'Bournemouth' u'Burnley' u'Cardiff' u'Chelsea'
 u'Crystal Palace' u'Everton' u'Fulham' u'Hull' u'Leicester' u'Liverpool'
 u'Manchester City' u'Manchester United' u'Middlesbrough'
 u'Newcastle United' u'Norwich' u'Portsmouth' u'Queens Park Rangers'
 u'Reading' u'Southampton' u'Stoke' u'Sunderland' u'Swansea' u'Tottenham'
 u'Watford' u'West Bromwich Albion' u'West Ham' u'Wigan'
 u'Wolverhampton Wanderers']
['Arsenal' 'Aston Villa' 'Birmingham' 'Blackburn' 'Blackpool' 'Bolton'
 'Burnley' 'Cardiff' 'Chelsea' 'Coventry' 'Crystal Palace' 'Derby'
 'Everton' 'Fulham' 'Hull' 'Ipswich' 'Leeds' 'Leicester' 'Liverpool'
 'Man City' 'Man United' 'Middlesbrough' 'Newcastle' 'Norwich' 'Portsmouth'
 'QPR' 'Reading' 'Southampton' 'Stoke' 'Sunderland' 'Swansea' 'Tottenham'
 'Watford' 'West Brom' 'West Ham' 'Wigan' 'Wolves']

In [201]:
input_data['home_team'][input_data['home_team']=='Man United']='Manchester United'
input_data['away_team'][input_data['away_team']=='Man United']='Manchester United'
input_data['home_team'][input_data['home_team']=='Man City']='Manchester City'
input_data['away_team'][input_data['away_team']=='Man City']='Manchester City'
input_data['home_team'][input_data['home_team']=='Newcastle']='Newcastle United'
input_data['away_team'][input_data['away_team']=='Newcastle']='Newcastle United'
input_data['home_team'][input_data['home_team']=='QPR']='Queens Park Rangers'
input_data['away_team'][input_data['away_team']=='QPR']='Queens Park Rangers'
input_data['home_team'][input_data['home_team']=='West Brom']='West Bromwich Albion'
input_data['away_team'][input_data['away_team']=='West Brom']='West Bromwich Albion'
input_data['home_team'][input_data['home_team']=='Wolves']='Wolverhampton Wanderers'
input_data['away_team'][input_data['away_team']=='Wolves']='Wolverhampton Wanderers'

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [202]:
print match_team['home_team'].sort_values().unique()
print input_data['home_team'].sort_values().unique()

[u'Arsenal' u'Aston Villa' u'Birmingham' u'Blackburn' u'Blackpool'
 u'Bolton' u'Bournemouth' u'Burnley' u'Cardiff' u'Chelsea'
 u'Crystal Palace' u'Everton' u'Fulham' u'Hull' u'Leicester' u'Liverpool'
 u'Manchester City' u'Manchester United' u'Middlesbrough'
 u'Newcastle United' u'Norwich' u'Portsmouth' u'Queens Park Rangers'
 u'Reading' u'Southampton' u'Stoke' u'Sunderland' u'Swansea' u'Tottenham'
 u'Watford' u'West Bromwich Albion' u'West Ham' u'Wigan'
 u'Wolverhampton Wanderers']
['Arsenal' 'Aston Villa' 'Birmingham' 'Blackburn' 'Blackpool' 'Bolton'
 'Burnley' 'Cardiff' 'Chelsea' 'Coventry' 'Crystal Palace' 'Derby'
 'Everton' 'Fulham' 'Hull' 'Ipswich' 'Leeds' 'Leicester' 'Liverpool'
 'Manchester City' 'Manchester United' 'Middlesbrough' 'Newcastle United'
 'Norwich' 'Portsmouth' 'Queens Park Rangers' 'Reading' 'Southampton'
 'Stoke' 'Sunderland' 'Swansea' 'Tottenham' 'Watford'
 'West Bromwich Albion' 'West Ham' 'Wigan' 'Wolverhampton Wanderers']

In [189]:
def date_flip(element):
    month = element.month
    day = element.day
    if day<13 and month<13:
        return datetime.datetime(year=element.year,month=day,day=month)
    else:
        return element

match_team['date_flip'] = match_team['date'].map(date_flip)

In [203]:
match_team[['date','date_flip']].head()

        date  date_flip
0 2008-08-17 2008-08-17
1 2010-08-16 2010-08-16
2 2011-11-26 2011-11-26
3 2012-12-26 2012-12-26
4 2013-12-07 2013-07-12

In [247]:
final_input = input_data.merge(match_team,how='inner',left_on=['home_team','away_team','Date'],\
                               right_on=['home_team','away_team','date_flip'])

In [248]:
final_input.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2626 entries, 0 to 2625
Data columns (total 43 columns):
away_corners            2626 non-null int64
away_fouls              2626 non-null int64
away_shots              2626 non-null int64
away_shots_target       2626 non-null int64
away_yellow_cards       2626 non-null int64
away_red_cards          2626 non-null int64
away_team               2626 non-null object
Date                    2626 non-null datetime64[ns]
full_time_away_goals    2626 non-null int64
full_time_home_goals    2626 non-null int64
home_corners            2626 non-null int64
home_fouls              2626 non-null int64
home_red_cards          2626 non-null int64
home_yellow_cards       2626 non-null int64
home_shots              2626 non-null int64
home_shots_target       2626 non-null int64
half_time_away_goals    2626 non-null int64
half_time_home_goals    2626 non-null int64
half_time_result        2626 non-null object
home_team               2626 non-null object
Referee                 2246 non-null object
result                  2626 non-null object
FDCOUK                  2626 non-null object
City                    2626 non-null object
Stadium                 2626 non-null object
Capacity                2626 non-null float64
Latitude                2626 non-null float64
Longitude               2626 non-null float64
Country                 2626 non-null object
closest_station         2626 non-null object
season                  2626 non-null object
date                    2626 non-null datetime64[ns]
home_team_api_id        2626 non-null int64
away_team_api_id        2626 non-null int64
goal                    2626 non-null object
shoton                  2626 non-null object
shotoff                 2626 non-null object
foulcommit              2626 non-null object
card                    2626 non-null object
cross                   2626 non-null object
corner                  2626 non-null object
possession              2626 non-null object
date_flip               2626 non-null datetime64[ns]
dtypes: datetime64[ns](3), float64(3), int64(18), object(19)
memory usage: 902.7+ KB

In [249]:
final_input.head(3).T

,0,1,2
away_corners,3,6,0
away_fouls,19,10,20
away_shots,4,13,5
away_shots_target,2,3,4
away_yellow_cards,2,1,4
away_red_cards,1,0,0
away_team,Crystal Palace,Everton,Swansea
Date,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00
full_time_away_goals,1,2,2
full_time_home_goals,2,2,1
home_corners,9,3,4
home_fouls,13,16,14
home_red_cards,0,0,0
home_yellow_cards,2,1,2
home_shots,14,11,14
home_shots_target,6,3,5
half_time_away_goals,1,2,1
half_time_home_goals,1,1,0
half_time_result,D,A,A
home_team,Arsenal,Leicester,Manchester United
Referee,J Moss,M Jones,M Dean
result,H,D,A
FDCOUK,Arsenal,Leicester,Man United
City,London,Leicester,Stretford
Stadium,Emirates Stadium,King Power Stadium,Old Trafford
Capacity,60361,32500,75811
Latitude,51.555,52.6203,53.4631
Longitude,-0.108611,-1.14222,-2.29139
Country,England,England,England
closest_station,EGLC,EGNX,EGCC
season,2014/2015,2014/2015,2014/2015
date,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00
home_team_api_id,9825,8197,10260
away_team_api_id,9826,8668,10003
goal,<goal><value><comment>n</comment><stats><goals...,<goal><value><comment>n</comment><stats><goals...,<goal><value><comment>n</comment><stats><goals...
shoton,<shoton><value><stats><blocked>1</blocked></st...,<shoton><value><stats><shoton>1</shoton></stat...,<shoton><value><stats><shoton>1</shoton></stat...
shotoff,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...
foulcommit,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...
card,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...
cross,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...
corner,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...
possession,<possession><value><comment>78</comment><event...,<possession><value><comment>39</comment><event...,<possession><value><comment>60</comment><event...
date_flip,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00

In [207]:
final_input.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
away_team                 0
Date                      0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 380
result                    0
FDCOUK                    0
City                      0
Stadium                   0
Capacity                  0
Latitude                  0
Longitude                 0
Country                   0
closest_station           0
season                    0
date                      0
home_team_api_id          0
away_team_api_id          0
goal                      0
shoton                    0
shotoff                   0
foulcommit                0
card                      0
cross                     0
corner                    0
possession                0
date_flip                 0
dtype: int64

In [208]:
final_input.shape

(2626, 43)

In [209]:
final_input.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v6.csv',index=False)

In [3]:
final_input = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v2.csv')

In [253]:
weather = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/weather_df.csv')

In [254]:
weather.head()

,Unnamed: 0,station,date,long,lat,temp (F),dew (F),humidity,wind direction,wind speed (mph),prec (in),visibility (mi)
0,1,EGLC,2000-01-01 10:20,0.0553,51.5053,48.20,44.60,87.28,310.00,2.3,M,6.21
1,2,EGLL,2000-01-01 15:20,-0.4614,51.4785,48.20,44.60,87.28,180.00,5.8,M,6.21
2,3,EGKK,2000-01-01 15:20,-0.1903,51.1481,48.20,44.60,87.28,M,3.5,M,6.21
3,4,EGLL,2000-01-01 15:50,-0.4614,51.4785,48.20,44.60,87.28,190.00,3.5,M,6.21
4,5,EGKK,2000-01-01 15:50,-0.1903,51.1481,48.20,44.60,87.28,M,2.3,M,6.21

In [255]:
weather.drop(['Unnamed: 0','long','lat'],axis=1,inplace=True)

In [258]:
weather['date'] = pd.to_datetime(weather['date'])
weather['date'] = weather['date'].map(lambda x: datetime.datetime(x.year,x.month,x.day))
weather['date'].head()

0   2000-01-01
1   2000-01-01
2   2000-01-01
3   2000-01-01
4   2000-01-01
Name: date, dtype: datetime64[ns]

In [259]:
weather = weather.apply(lambda x: x.map(lambda y: 0. if (y=='M' or y==None) else y))

In [260]:
weather[['temp (F)','dew (F)','humidity','wind direction','wind speed (mph)','prec (in)','visibility (mi)']] = weather[['temp (F)','dew (F)','humidity','wind direction','wind speed (mph)','prec (in)','visibility (mi)']].apply(lambda x: x.astype(float))

In [261]:
weather = weather.groupby(['station','date']).mean().reset_index()

In [262]:
weather['date'].head()

0   2011-08-22
1   2011-08-23
2   2011-08-24
3   2011-08-25
4   2011-08-26
Name: date, dtype: datetime64[ns]

In [263]:
final_merge = final_input.merge(weather,how='inner',left_on=['date','closest_station'],right_on=['date','station'])

In [271]:
final_merge.shape

(1647, 53)

In [272]:
final_merge.drop('prec (in)',axis=1,inplace=True)

In [21]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v3.csv',index=False)

In [267]:
def clean_html_goals_shots(element):
    try:
        soup = BeautifulSoup(element)
        text = zip(soup.findAll('subtype'),soup.findAll('team'))
        output = []
        for i in text:
            output.append((i[0].get_text(),i[1].get_text()))
        return output
    except:
        return element

In [268]:
final_merge['goal'].map(clean_html_goals_shots)

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

0        [(header, 9826), (header, 9825), (tap_in, 9825)]
1                          [(missed, 8654), (shot, 8586)]
2       [(shot, 8668), (loose_ball, 8197), (shot, 8668...
3       [(distance, 10003), (bicycle_kick, 10260), (vo...
4         [(header, 8667), (saved_back_into_play, 10172)]
5                                         [(shot, 10252)]
6        [(distance, 8472), (tap_in, 8659), (shot, 8659)]
7            [(shot, 8650), (shot, 8466), (tap_in, 8650)]
8                            [(shot, 8456), (shot, 8456)]
9       [(shot, 8191), (loose_ball, 8455), (tap_in, 84...
10                                                     []
11                           [(shot, 8455), (shot, 8455)]
12      [(volley, 8654), (distance, 8654), (distance, ...
13      [(header, 8668), (shot, 8668), (tap_in, 9825),...
14                                                     []
15                                        [(shot, 10003)]
16                  [(tap_in, 8667), (loose_ball, 10194)]
17                      [(tap_in, 10260), (header, 8472)]
18      [(shot, 8586), (header, 8586), (header, 8586),...
19           [(volley, 8456), (shot, 8456), (shot, 8456)]
20                                                     []
21      [(shot, 8455), (shot, 8455), (shot, 8668), (he...
22                                        [(shot, 10194)]
23      [(loose_ball, 9826), (deflected, 10261), (voll...
24                                        [(shot, 10172)]
25        [(shot, 10003), (volley, 10003), (shot, 10003)]
26      [(deflected, 8654), (loose_ball, 8466), (tap_i...
27         [(shot, 10252), (shot, 10252), (header, 8667)]
28                         [(shot, 9825), (header, 8197)]
29                           [(shot, 8650), (shot, 8650)]
30      [(shot, 8456), (shot, 9825), (volley, 9825), (...
31      [(header, 8455), (shot, 8455), (shot, 8455), (...
32                                        [(saved, 8191)]
33                                  [(loose_ball, 10252)]
34      [(header, 8466), (tap_in, 8466), (shot, 8466),...
35                                       [(tap_in, 8197)]
36         [(tap_in, 8586), (shot, 8472), (tap_in, 8586)]
37                           [(shot, 8668), (shot, 8668)]
38      [(direct_freekick, 10260), (shot, 10260), (sho...
39      [(header, 8667), (header, 8667), (distance, 86...
40                           [(shot, 9825), (shot, 9825)]
41                                                     []
42      [(bicycle_kick, 8667), (distance, 8667), (shot...
43      [(header, 10194), (header, 10172), (shot, 1019...
44                                         [(shot, 8466)]
45      [(tap_in, 8654), (shot, 8654), (shot, 8650), (...
46           [(shot, 8668), (header, 9826), (shot, 9826)]
47      [(header, 10260), (shot, 10260), (header, 8197...
48                         [(tap_in, 8455), (shot, 8456)]
49                         [(shot, 8659), (header, 8659)]
50                           [(shot, 8586), (shot, 9825)]
51         [(shot, 8455), (header, 8455), (tap_in, 8455)]
52                       [(header, 9826), (header, 9826)]
53      [(shot, 8456), (shot, 8456), (shot, 8456), (sh...
54            [(direct_freekick, 8650), (distance, 8668)]
55      [(shot, 10260), (shot, 10260), (header, 8654),...
56      [(shot, 8466), (volley, 10172), (bicycle_kick,...
57                                                     []
58      [(header, 8659), (header, 8659), (shot, 8659),...
59                                      [(header, 10194)]
60                       [(distance, 8456), (shot, 8456)]
61                         [(header, 8667), (shot, 8667)]
62      [(shot, 8197), (shot, 8191), (header, 8197), (...
63                           [(shot, 8650), (shot, 8659)]
64      [(header, 8472), (shot, 10194), (header, 8472)...
65        [(shot, 10003), (shot, 10261), (volley, 10003)]
66                                          [(lob, 8455)]
67                                         [(shot, 8586)]
68                                      [(header, 10172)]
69      [(shot, 10260), (saved_back_into_play, 8668), ...
70      [(shot, 9825), (shot, 8667), (header, 8667), (...
71      [(header, 8654), (header, 8654), (shot, 8191),...
72      [(direct_freekick, 8455), (shot, 8455), (tap_i...
73         [(header, 8668), (shot, 8668), (tap_in, 8668)]
74      [(shot, 8456), (shot, 8586), (saved_back_into_...
75                                    [(distance, 10261)]
76      [(tap_in, 8472), (tap_in, 8466), (shot, 8466),...
77                       [(tap_in, 10172), (shot, 10172)]
78                                      [(header, 10003)]
79      [(shot, 8659), (shot, 10260), (shot, 8659), (d...
80                                                     []
81                                   [(loose_ball, 8466)]
82                            [(lob, 9825), (shot, 9825)]
83                         [(shot, 10003), (shot, 10003)]
84                         [(shot, 9826), (header, 9826)]
85         [(tap_in, 8654), (header, 8654), (shot, 8456)]
86      [(header, 8668), (shot, 8191), (shot, 8668), (...
87                  [(header, 8455), (loose_ball, 10260)]
88       [(header, 8586), (shot, 10261), (header, 10261)]
89                     [(distance, 10172), (shot, 10172)]
90           [(header, 9825), (shot, 9825), (shot, 9825)]
91                      [(shot, 8455), (backheel, 10172)]
92                                                     []
93                                     [(distance, 8466)]
94                                                     []
95                                        [(shot, 10261)]
96      [(tap_in, 10194), (header, 10194), (header, 86...
97      [(shot, 10252), (volley, 8586), (direct_freeki...
98                                         [(shot, 8456)]
99           [(header, 8472), (shot, 8472), (shot, 8472)]
100                                      [(header, 8191)]
101       [(deflected, 8650), (shot, 8455), (shot, 8455)]
102                                   [(distance, 10260)]
103           [(shot, 10172), (shot, 8456), (shot, 8456)]
104                          [(shot, 8466), (shot, 8466)]
105                                                    []
106                             [(direct_freekick, 8472)]
107     [(shot, 9825), (direct_freekick, 10003), (head...
108     [(distance, 10194), (shot, 10194), (volley, 85...
109                  [(backheel, 10261), (header, 10261)]
110                         [(shot, 9825), (shot, 10260)]
111                          [(shot, 8455), (shot, 8455)]
112       [(shot, 8668), (deflected, 8654), (shot, 8668)]
113                                                    []
114         [(shot, 10003), (tap_in, 8456), (shot, 8456)]
115                                       [(shot, 10261)]
116         [(shot, 8191), (shot, 8191), (header, 10194)]
117     [(shot, 8650), (shot, 9826), (shot, 9826), (di...
118        [(distance, 8667), (shot, 8586), (shot, 8586)]
119                         [(shot, 10252), (shot, 8466)]
120                                       [(shot, 10252)]
121                                  [(loose_ball, 8650)]
122     [(shot, 10260), (distance, 10260), (distance, ...
123     [(distance, 8197), (shot, 8197), (distance, 10...
124                                                    []
125                                       [(shot, 10003)]
126                                      [(header, 9825)]
127                                        [(shot, 8654)]
128        [(distance, 8456), (shot, 8456), (shot, 8456)]
129     [(distance, 8668), (loose_ball, 8586), (shot, ...
130                     [(distance, 8191), (shot, 10261)]
131                                       [(shot, 10252)]
132            [(shot, 8650), (shot, 8650), (shot, 8650)]
133     [(header, 10260), (distance, 10194), (direct_f...
134                    [(shot, 10003), (distance, 10003)]
135      [(header, 8659), (header, 8654), (header, 8654)]
136                                        [(shot, 9825)]
137            [(shot, 8455), (shot, 8455), (shot, 8455)]
138                          [(shot, 8668), (shot, 8667)]
139     [(shot, 8472), (shot, 8456), (shot, 8456), (lo...
140                        [(saved_back_into_play, 8659)]
141                                                    []
142                                                    []
143        [(shot, 10261), (shot, 10261), (header, 8455)]
144                   [(deflected, 10172), (shot, 10172)]
145     [(tap_in, 10194), (volley, 10194), (volley, 10...
146                                                    []
147      [(tap_in, 8197), (header, 10252), (shot, 10252)]
148     [(shot, 10003), (header, 8654), (header, 8654)...
149     [(shot, 10260), (loose_ball, 8466), (volley, 1...
150     [(header, 9825), (shot, 9825), (shot, 9825), (...
151                        [(header, 8455), (shot, 8455)]
152     [(saved_back_into_play, 8466), (deflected, 8191)]
153                     [(header, 9826), (tap_in, 10194)]
154                                        [(shot, 8456)]
155                                   [(deflected, 8472)]
156                                        [(shot, 8659)]
157       [(shot, 10260), (header, 10260), (shot, 10260)]
158         [(header, 8586), (shot, 10003), (shot, 8586)]
159     [(distance, 8668), (direct_freekick, 8668), (l...
160                      [(shot, 10252), (header, 10260)]
161                                       [(shot, 10003)]
162     [(deflected, 8456), (shot, 8456), (header, 982...
163     [(header, 8659), (shot, 8659), (tap_in, 10172)...
164                        [(shot, 8668), (header, 8466)]
165      [(header, 8586), (shot, 8191), (distance, 8586)]
166                      [(shot, 8654), (distance, 8654)]
167     [(shot, 8650), (header, 9825), (shot, 9825), (...
168                                        [(shot, 8472)]
169                        [(header, 8455), (shot, 8455)]
170     [(saved_back_into_play, 9825), (header, 9825),...
171                        [(volley, 8455), (shot, 8455)]
172                                        [(shot, 8650)]
173                                                    []
174     [(shot, 8586), (backheel, 8197), (direct_freek...
175     [(tap_in, 10260), (shot, 10260), (header, 10260)]
176     [(shot, 8472), (distance, 8667), (header, 8667...
177                            [(direct_freekick, 10003)]
178     [(bicycle_kick, 8456), (shot, 8456), (header, ...
179                                                    []
180                                    [(distance, 8197)]
181     [(shot, 8456), (distance, 8456), (shot, 8191),...
182     [(volley, 8668), (shot, 10261), (shot, 10261),...
183                                                    []
184                          [(shot, 8466), (shot, 8455)]
185                        [(shot, 10194), (shot, 10194)]
186                                     [(header, 10260)]
187          [(shot, 8654), (shot, 9825), (header, 9825)]
188     [(shot, 8650), (shot, 8650), (shot, 10003), (s...
189                                                    []
190                         [(header, 8667), (lob, 8667)]
191                        [(volley, 8650), (shot, 8650)]
192     [(distance, 8456), (backheel, 8456), (header, ...
193     [(header, 10261), (distance, 10261), (header, ...
194                    [(distance, 10172), (shot, 10003)]
195                     [(lob, 8466), (loose_ball, 8466)]
196                        [(shot, 10194), (shot, 10260)]
197     [(shot, 8455), (distance, 8586), (shot, 8586),...
198                        [(header, 8654), (shot, 8659)]
199           [(shot, 8191), (shot, 10172), (shot, 8191)]
200                          [(shot, 8455), (shot, 8455)]
201                          [(shot, 8586), (shot, 9826)]
202                      [(header, 8456), (header, 8668)]
203                                        [(shot, 8197)]
204                                        [(shot, 8650)]
205                                        [(shot, 8654)]
206                           [(indirect freekick, 8659)]
207     [(header, 9825), (shot, 9825), (direct_freekic...
208                                  [(loose_ball, 8466)]
209                          [(shot, 8650), (shot, 8650)]
210     [(header, 8191), (shot, 8191), (shot, 9826), (...
211                                       [(shot, 10194)]
212                    [(shot, 8466), (deflected, 10261)]
213                        [(shot, 10260), (shot, 10260)]
214     [(volley, 8455), (shot, 8455), (shot, 8455), (...
215     [(direct_freekick, 8472), (distance, 8472), (d...
216                                      [(header, 9825)]
217       [(loose_ball, 8654), (lob, 8654), (shot, 8654)]
218                                        [(post, 8668)]
219                          [(shot, 8455), (shot, 8456)]
220                                      [(tap_in, 8668)]
221     [(distance, 10261), (distance, 8667), (deflect...
222                          [(shot, 8650), (shot, 8650)]
223     [(shot, 10260), (loose_ball, 10260), (header, ...
224     [(shot, 10194), (shot, 10194), (loose_ball, 10...
225                      [(header, 8472), (tap_in, 8472)]
226               [(direct_freekick, 8586), (shot, 8586)]
227     [(shot, 9825), (shot, 9825), (shot, 9825), (di...
228                                   [(distance, 10003)]
229       [(shot, 8455), (header, 10252), (volley, 8455)]
230                                                    []
231                                      [(header, 9826)]
232               [(shot, 8667), (direct_freekick, 8456)]
233                                        [(shot, 8466)]
234        [(shot, 10003), (shot, 8472), (header, 10003)]
235        [(volley, 9825), (shot, 8586), (header, 8586)]
236     [(header, 8191), (header, 8191), (header, 8659...
237                      [(shot, 10261), (header, 10194)]
238                  [(deflected, 8654), (volley, 10260)]
239     [(volley, 9825), (loose_ball, 9825), (shot, 81...
240               [(deflected, 8667), (loose_ball, 8667)]
241     [(shot, 8650), (shot, 8586), (tap_in, 8650), (...
242                      [(header, 10172), (shot, 10172)]
243                 [(deflected, 8455), (distance, 8455)]
244                       [(header, 10261), (shot, 9826)]
245     [(header, 10260), (header, 8191), (header, 102...
246                                                    []
247     [(shot, 8456), (header, 10194), (header, 8456)...
248                          [(shot, 8659), (shot, 8659)]
249                    [(header, 10252), (header, 10194)]
250                        [(shot, 8455), (header, 8191)]
251                      [(tap_in, 9825), (tap_in, 9825)]
252       [(shot, 8667), (header, 10172), (header, 8667)]
253     [(shot, 8456), (shot, 8456), (shot, 8456), (sh...
254                                                    []
255       [(shot, 10260), (shot, 10003), (header, 10003)]
256      [(shot, 8668), (loose_ball, 8197), (shot, 8197)]
257                      [(distance, 8650), (shot, 8650)]
258     [(header, 8654), (shot, 8654), (shot, 8586), (...
259                                                    []
260                      [(header, 10260), (shot, 10260)]
261                        [(shot, 10261), (shot, 10252)]
262                                     [(header, 10194)]
263                                      [(volley, 8659)]
264     [(deflected, 9826), (header, 9826), (header, 9...
265                   [(volley, 9825), (deflected, 9825)]
266        [(distance, 8650), (shot, 8456), (shot, 8650)]
267                       [(shot, 10252), (header, 8659)]
268                    [(backheel, 8667), (header, 8472)]
269                                        [(shot, 8466)]
270                        [(shot, 8650), (header, 8650)]
271                      [(tap_in, 8456), (tap_in, 8456)]
272                                       [(shot, 10260)]
273           [(shot, 9825), (shot, 9825), (shot, 10172)]
274                      [(header, 10194), (shot, 10194)]
275     [(shot, 8586), (shot, 10003), (shot, 8586), (s...
276                                      [(header, 8455)]
277         [(header, 8586), (shot, 8586), (shot, 10172)]
278            [(shot, 9825), (shot, 9825), (shot, 9825)]
279                                      [(volley, 8191)]
280     [(tap_in, 9826), (tap_in, 9826), (deflected, 9...
281                                                    []
282     [(shot, 10252), (shot, 10252), (shot, 10252), ...
283                        [(header, 8659), (shot, 8659)]
284                                      [(header, 8455)]
285                          [(shot, 8668), (shot, 8668)]
286       [(shot, 10260), (header, 10260), (shot, 10260)]
287                                   [(deflected, 8650)]
288                                       [(shot, 10003)]
289     [(loose_ball, 8456), (loose_ball, 8456), (shot...
290         [(shot, 9825), (header, 9825), (shot, 10261)]
291                                      [(tap_in, 8466)]
292                         [(shot, 10194), (shot, 9826)]
293     [(tap_in, 8586), (deflected, 8586), (shot, 858...
294                                      [(volley, 8654)]
295     [(volley, 8455), (shot, 8455), (tap_in, 8667),...
296     [(shot, 10260), (bicycle_kick, 10260), (shot, ...
297     [(shot, 8668), (shot, 10172), (loose_ball, 8668)]
298     [(shot, 9825), (direct_freekick, 9825), (dista...
299                        [(lob, 8455), (tap_in, 10194)]
300                                        [(shot, 8668)]
301     [(distance, 8197), (saved_back_into_play, 8197...
302     [(shot, 10260), (shot, 10260), (shot, 10252), ...
303     [(shot, 10003), (bicycle_kick, 10003), (tap_in...
304     [(distance, 10172), (header, 10172), (shot, 10...
305                                                    []
306                                      [(volley, 8472)]
307     [(tap_in, 9826), (direct_freekick, 9826), (sho...
308     [(header, 10172), (deflected, 10252), (shot, 1...
309                                        [(shot, 9825)]
310                                        [(shot, 8466)]
311     [(header, 9826), (shot, 9826), (lob, 9826), (s...
312                                        [(shot, 8668)]
313                                     [(header, 10252)]
314              [(direct_freekick, 8654), (shot, 10194)]
315     [(header, 8659), (shot, 8197), (shot, 8659), (...
316     [(tap_in, 8456), (loose_ball, 10260), (header,...
317                                        [(shot, 8455)]
318                          [(shot, 8650), (shot, 8650)]
319                                        [(shot, 8455)]
320                    [(header, 8659), (distance, 8659)]
321                         [(saved, 8668), (shot, 8668)]
322                          [(shot, 8197), (shot, 8197)]
323     [(tap_in, 8466), (volley, 10194), (volley, 101...
324                                        [(shot, 8654)]
325     [(distance, 8586), (shot, 10261), (direct_free...
326                        [(post, 8191), (tap_in, 8197)]
327        [(tap_in, 8667), (header, 9826), (shot, 8667)]
328     [(tap_in, 8456), (direct_freekick, 8456), (dis...
329     [(shot, 10261), (header, 10003), (shot, 10003)...
330      [(saved_back_into_play, 10172), (header, 10172)]
331     [(shot, 8466), (header, 8586), (header, 8466),...
332                 [(loose_ball, 8472), (volley, 10194)]
333                                                    []
334                                                    []
335          [(shot, 8668), (header, 8668), (shot, 8668)]
336     [(shot, 8197), (shot, 8455), (loose_ball, 8455...
337     [(header, 10252), (shot, 10252), (shot, 8668),...
338                        [(header, 8197), (shot, 8197)]
339     [(shot, 8650), (shot, 10172), (saved_back_into...
340         [(shot, 8659), (saved_back_into_play, 10260)]
341                                  [(loose_ball, 8472)]
342                      [(header, 10003), (shot, 10003)]
343                                                    []

In [269]:
def split_goal_stats(df):
    goal_list = df['goal'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],goal_list):
        home_goals = []
        away_goals = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_goals.append(i[0])
                else:
                    away_goals.append(i[0])
        except:
            home_goals.append('')
            away_goals.append('')
        home_full.append(home_goals)
        away_full.append(away_goals)
    df['home_goal_types'] = home_full
    df['away_goal_types'] = away_full
    return df

In [270]:
pd.set_option('display.max_rows',60)
split_goal_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,station,temp (F),dew (F),humidity,wind direction,wind speed (mph),prec (in),visibility (mi),home_goal_types,away_goal_types
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,EGLC,62.920000,48.320000,60.205778,269.333333,12.264444,0.0,6.210000,"[header, tap_in]",[header]
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,EGLC,62.920000,48.320000,60.205778,269.333333,12.264444,0.0,6.210000,[missed],[shot]
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,EGNX,58.348936,48.429787,70.591064,248.297872,16.000000,0.0,6.210000,"[loose_ball, shot]","[shot, shot]"
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,EGCC,57.575000,49.775000,75.937708,246.041667,11.908333,0.0,6.210000,[bicycle_kick],"[distance, volley]"
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,EGWU,60.125000,47.750000,65.895833,276.250000,11.150000,0.0,6.210000,[saved_back_into_play],[header]
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,EGOS,57.575000,48.800000,73.579583,247.916667,13.200000,0.0,6.210000,[],[shot]
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,EGBB,58.662500,48.087500,68.910833,239.166667,8.700000,0.0,6.210000,"[tap_in, shot]",[distance]
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,EGGP,58.569565,50.547826,75.326957,269.782609,22.876087,0.0,6.129130,"[shot, tap_in]",[shot]
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,EGNT,55.673913,48.513043,77.494130,270.000000,20.752174,0.0,6.210000,[],"[shot, shot]"
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,EGNM,53.638298,45.595745,75.293830,302.765957,13.161702,0.0,6.210000,[shot],"[loose_ball, tap_in, tap_in]"
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,EGBB,54.087500,45.162500,72.571250,274.375000,7.472917,0.0,6.210000,[],[]
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,EGLC,59.150000,43.775000,57.807708,281.666667,10.300000,0.0,6.210000,"[shot, shot]",[]
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,EGKB,58.263636,40.427273,52.702273,278.181818,10.172727,0.0,6.210000,[distance],"[volley, distance, shot]"
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,EGGP,54.575000,47.412500,77.567500,264.375000,10.856250,0.0,6.132500,"[header, shot]","[tap_in, header]"
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,EGHI,55.657143,40.948571,60.426571,208.571429,6.365714,0.0,6.210000,[],[]
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,EGOP,52.775000,44.150000,74.493333,270.416667,9.708333,0.0,6.210000,[shot],[]
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,EGXV,53.450000,45.800000,77.648333,241.250000,5.866667,0.0,6.210000,[tap_in],[loose_ball]
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,EGNT,51.917391,44.247826,77.503478,174.565217,4.447826,0.0,6.210000,[header],[tap_in]
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,EGLC,58.700000,44.825000,61.875000,219.791667,6.845833,0.0,6.210000,"[shot, header, header, tap_in]",[]
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,EGCC,56.375000,51.912500,85.085417,100.000000,10.877083,0.0,5.955417,"[volley, shot, shot]",[]
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,EGNM,57.353191,52.259574,83.886383,268.085106,14.457447,0.0,6.210000,[],[]
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,EGGP,58.920000,55.160000,87.592444,264.888889,14.028889,0.0,6.058444,"[shot, header, shot, deflected, shot]","[shot, shot, header, shot]"
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,EGCC,57.950000,55.100000,90.805833,256.041667,10.400000,0.0,5.784792,[],[shot]
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,EGNT,58.914286,49.485714,71.879048,268.571429,15.276190,0.0,6.210000,"[deflected, header, loose_ball]","[loose_ball, volley, shot]"
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,EGWU,62.225000,52.100000,70.263750,272.500000,11.187500,0.0,6.031667,[shot],[]
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,EGOP,60.425000,54.050000,79.656667,275.833333,16.408333,0.0,6.210000,"[shot, volley, shot]",[]
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,EGLC,64.720000,52.360000,64.892000,266.000000,13.293333,0.0,6.196222,[deflected],"[loose_ball, tap_in, loose_ball]"
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,EGBB,60.462500,50.600000,71.602500,245.208333,6.008333,0.0,6.023750,"[shot, shot]",[header]
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,EGNX,60.378723,51.953191,75.115106,264.255319,10.623404,0.0,6.210000,[header],[shot]
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,EGLC,64.325000,51.087500,63.360208,275.208333,9.708333,0.0,6.210000,[],"[shot, shot]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,EGLC,42.650000,40.137500,90.794375,117.291667,4.666667,0.0,4.557083,"[saved_back_into_play, shot, loose_ball]",[]
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,EGLC,37.437500,31.025000,77.522708,78.541667,17.687500,0.0,5.460833,[],[]
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,EGLC,35.337500,28.962500,77.715625,305.000000,8.308333,0.0,6.210000,[],[]
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,EGLC,37.556522,31.021739,77.960000,215.652174,5.776087,0.0,6.129130,[],[shot]
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,EGLC,37.556522,31.021739,77.960000,215.652174,5.776087,0.0,6.129130,[],"[shot, shot]"
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,EGLC,47.712500,38.412500,70.323333,252.708333,6.660417,0.0,6.210000,[],[]
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,EGLC,46.812500,37.400000,70.004583,161.250000,4.691667,0.0,6.210000,[],[]
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,EGLC,46.812500,37.400000,70.004583,161.250000,4.691667,0.0,6.210000,"[shot, header]",[shot]
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,EGLC,45.560000,39.080000,78.639778,182.222222,4.797778,0.0,4.634222,[loose_ball],[]
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,EGLC,41.487500,34.025000,75.862292,216.250000,6.272917,0.0,6.158333,"[shot, shot, shot, shot]","[shot, header]"
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,EGLC,50.787500,40.831250,70.092500,243.750000,11.090625,0.0,6.035625,[volley],[shot]
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,EGLC,54.800000,38.975000,55.590833,127.083333,2.887500,0.0,6.210000,"[shot, shot]",[]
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,EGLC,51.612500,40.737500,68.024792,152.291667,4.231250,0.0,5.505417,[],[]
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,EGLC,51.388571,37.708571,61.020571,285.428571,7.022857,0.0,4.618571,[shot],[]
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,EGLC,53.052174,38.691304,61.745435,228.913043,8.869565,0.0,4.588043,"[header, shot]",[]
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,EGLC,53.052174,38.691304,61.745435,228.913043,8.869565,0.0,4.588043,"[shot, header]",[]
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,EGLC,52.175000,49.100000,89.423958,214.583333,3.420833,0.0,3.468333,"[shot, shot, shot, shot]","[shot, header]"
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,EGLC,52.175000,49.100000,89.423958,214.583333,3.420833,0.0,3.468333,[shot],[]
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,EGLC,50.412500,42.050000,73.967500,135.208333,6.852083,0.0,6.145417,[loose_ball],[]
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,EGLC,57.356522,40.765217,57.731522,56.086957,3.039130,0.0,6.183043,[],[]
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,EGLC,53.787500,38.750000,57.942708,162.083333,9.991667,0.0,6.042083,[saved_back_into_play],[shot]
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,EGLC,54.200000,36.125000,53.967917,144.583333,6.110417,0.0,6.210000,"[shot, shot]",[]
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,EGLC,58.362500,42.537500,58.314792,228.958333,7.500000,0.0,6.210000,"[shot, shot, shot, shot]",[shot]
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,EGLC,58.362500,42.537500,58.314792,228.958333,7.500000,0.0,6.210000,"[distance, shot]",[]
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,EGLC,54.875000,40.325000,59.913542,234.583333,7.691667,0.0,6.210000,[],"[shot, post, shot, loose_ball]"
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,EGLC,55.962500,42.237500,61.877292,79.791667,8.097917,0.0,6.210000,"[header, loose_ball]","[header, distance]"
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,EGLC,54.748936,42.991489,66.053830,191.063830,12.014894,0.0,6.183617,"[shot, shot]",[shot]
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,EGLC,53.982979,46.093617,75.237872,177.659574,11.723404,0.0,6.130851,"[header, shot]",[]
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,EGLC,62.337500,47.862500,60.548958,92.083333,7.114583,0.0,6.210000,[volley],[header]
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,EGLC,62.337500,47.862500,60.548958,92.083333,7.114583,0.0,6.210000,"[shot, shot]",[shot]

In [273]:
def split_shoton_stats(df):
    shoton_list = df['shoton'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],shoton_list):
        home_shots = []
        away_shots = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_shots.append(i[0])
                else:
                    away_shots.append(i[0])
        except:
            home_shots.append('')
            away_shots.append('')
        home_full.append(home_shots)
        away_full.append(away_shots)
    df['home_shoton_types'] = home_full
    df['away_shoton_types'] = away_full
    return df

In [274]:
split_shoton_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,temp (F),dew (F),humidity,wind direction,wind speed (mph),visibility (mi),home_goal_types,away_goal_types,home_shoton_types,away_shoton_types
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,62.920000,48.320000,60.205778,269.333333,12.264444,6.210000,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]"
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,62.920000,48.320000,60.205778,269.333333,12.264444,6.210000,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis..."
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,58.348936,48.429787,70.591064,248.297872,16.000000,6.210000,"[loose_ball, shot]","[shot, shot]","[blocked_shot, blocked_shot]","[deflected, blocked_shot, shot, blocked_shot, ..."
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,57.575000,49.775000,75.937708,246.041667,11.908333,6.210000,[bicycle_kick],"[distance, volley]","[distance, blocked_shot, direct_freekick, head...","[distance, distance, blocked_shot]"
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,60.125000,47.750000,65.895833,276.250000,11.150000,6.210000,[saved_back_into_play],[header],"[deflected, blocked_shot, shot, blocked_shot, ...","[big chance shot, distance, direct_freekick, b..."
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,57.575000,48.800000,73.579583,247.916667,13.200000,6.210000,[],[shot],"[shot, shot, blocked_shot, big chance blocked,...","[blocked_shot, big chance shot]"
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,58.662500,48.087500,68.910833,239.166667,8.700000,6.210000,"[tap_in, shot]",[distance],"[blocked_shot, shot, shot, distance]",[]
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,58.569565,50.547826,75.326957,269.782609,22.876087,6.129130,"[shot, tap_in]",[shot],"[shot, shot, blocked_shot, blocked_shot]","[distance, distance, big chance shot, blocked_..."
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,55.673913,48.513043,77.494130,270.000000,20.752174,6.210000,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b..."
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,53.638298,45.595745,75.293830,302.765957,13.161702,6.210000,[shot],"[loose_ball, tap_in, tap_in]",[shot],"[blocked_shot, shot, blocked_shot]"
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,54.087500,45.162500,72.571250,274.375000,7.472917,6.210000,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[blocked_shot, shot, big chance header, shot]"
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,59.150000,43.775000,57.807708,281.666667,10.300000,6.210000,"[shot, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, big...","[distance, blocked_shot, big chance shot, big ..."
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,58.263636,40.427273,52.702273,278.181818,10.172727,6.210000,[distance],"[volley, distance, shot]","[header, blocked_shot, blocked_shot, blocked_s...","[blocked_shot, blocked_shot, header, shot, blo..."
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,54.575000,47.412500,77.567500,264.375000,10.856250,6.132500,"[header, shot]","[tap_in, header]","[blocked_shot, blocked_shot]","[blocked_shot, blocked_shot, blocked_shot, big..."
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,55.657143,40.948571,60.426571,208.571429,6.365714,6.210000,[],[],"[blocked_shot, shot, shot]","[direct_freekick, blocked_shot, big chance shot]"
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,52.775000,44.150000,74.493333,270.416667,9.708333,6.210000,[shot],[],"[blocked_shot, blocked_shot, shot, distance, b...","[shot, blocked_shot, shot, blocked_shot, block..."
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,53.450000,45.800000,77.648333,241.250000,5.866667,6.210000,[tap_in],[loose_ball],"[blocked_shot, blocked_shot, blocked_shot, dis...","[shot, distance, blocked_shot, volley]"
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,51.917391,44.247826,77.503478,174.565217,4.447826,6.210000,[header],[tap_in],"[blocked_shot, shot, blocked_shot, distance]","[header, blocked_shot, distance, blocked_shot]"
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,58.700000,44.825000,61.875000,219.791667,6.845833,6.210000,"[shot, header, header, tap_in]",[],"[distance, blocked_shot, blocked_shot, blocked...",[distance]
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,56.375000,51.912500,85.085417,100.000000,10.877083,5.955417,"[volley, shot, shot]",[],[shot],"[blocked_shot, blocked_shot, shot, big chance ..."
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,57.353191,52.259574,83.886383,268.085106,14.457447,6.210000,[],[],"[shot, blocked_shot, volley, shot]","[shot, blocked_shot, volley, blocked_shot]"
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,58.920000,55.160000,87.592444,264.888889,14.028889,6.058444,"[shot, header, shot, deflected, shot]","[shot, shot, header, shot]","[blocked_shot, blocked_shot, blocked_shot, sho...","[blocked_shot, blocked_shot, big chance shot, ..."
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,57.950000,55.100000,90.805833,256.041667,10.400000,5.784792,[],[shot],"[shot, blocked_shot, big chance shot, blocked_...","[blocked_shot, shot]"
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,58.914286,49.485714,71.879048,268.571429,15.276190,6.210000,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]"
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,62.225000,52.100000,70.263750,272.500000,11.187500,6.031667,[shot],[],"[header, shot, blocked_shot, shot, shot]","[blocked_shot, shot, shot, shot, header, dista..."
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,60.425000,54.050000,79.656667,275.833333,16.408333,6.210000,"[shot, volley, shot]",[],"[distance, shot, distance, shot, shot, distance]","[shot, blocked_shot, blocked_shot, blocked_sho..."
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,64.720000,52.360000,64.892000,266.000000,13.293333,6.196222,[deflected],"[loose_ball, tap_in, loose_ball]","[blocked_shot, big chance shot]","[header, blocked_shot, distance, blocked_shot,..."
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,60.462500,50.600000,71.602500,245.208333,6.008333,6.023750,"[shot, shot]",[header],"[shot, header]","[distance, volley]"
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,60.378723,51.953191,75.115106,264.255319,10.623404,6.210000,[header],[shot],"[shot, blocked_shot, blocked_shot, blocked_sho...","[shot, header, blocked_shot, shot, blocked_sho..."
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,64.325000,51.087500,63.360208,275.208333,9.708333,6.210000,[],"[shot, shot]","[big chance volley, blocked_shot, blocked_shot]","[header, shot, shot, big chance shot, blocked_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,42.650000,40.137500,90.794375,117.291667,4.666667,4.557083,"[saved_back_into_play, shot, loose_ball]",[],"[blocked_shot, distance, distance, shot, heade...","[blocked_shot, header, direct_freekick, blocke..."
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,37.437500,31.025000,77.522708,78.541667,17.687500,5.460833,[],[],"[distance, blocked_shot, blocked_shot, blocked...","[header, distance]"
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,35.337500,28.962500,77.715625,305.000000,8.308333,6.210000,[],[],"[header, shot, blocked_shot, blocked_shot, vol...","[blocked_shot, distance, shot]"
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,37.556522,31.021739,77.960000,215.652174,5.776087,6.129130,[],[shot],"[shot, blocked_shot, distance, blocked_shot, d...",[shot]
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,37.556522,31.021739,77.960000,215.652174,5.776087,6.129130,[],"[shot, shot]","[shot, shot, deflected, shot, blocked_shot]","[blocked_shot, deflected, blocked_shot, deflec..."
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,47.712500,38.412500,70.323333,252.708333,6.660417,6.210000,[],[],"[distance, header, shot, header, shot, direct_...","[distance, shot]"
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,46.812500,37.400000,70.004583,161.250000,4.691667,6.210000,[],[],"[header, blocked_shot, shot, blocked_shot, sho...","[blocked_shot, shot, shot, blocked_shot]"
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,46.812500,37.400000,70.004583,161.250000,4.691667,6.210000,"[shot, header]",[shot],"[deflected, distance, blocked_shot, header, sh...","[deflected, shot, header, shot, blocked_shot, ..."
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,45.560000,39.080000,78.639778,182.222222,4.797778,4.634222,[loose_ball],[],"[shot, header, blocked_shot, shot, shot, shot,...","[distance, blocked_shot, blocked_shot, deflect..."
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,41.487500,34.025000,75.862292,216.250000,6.272917,6.158333,"[shot, shot, shot, shot]","[shot, header]","[blocked_shot, shot, blocked_shot, distance]","[distance, blocked_shot, shot, distance]"
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,50.787500,40.831250,70.092500,243.750000,11.090625,6.035625,[volley],[shot],"[distance, shot, blocked_shot, shot, blocked_s...","[header, shot, direct_freekick, blocked_shot]"
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,54.800000,38.975000,55.590833,127.083333,2.887500,6.210000,"[shot, shot]",[],"[blocked_shot, shot, blocked_shot, header, shot]","[blocked_shot, blocked_shot, volley]"
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,51.612500,40.737500,68.024792,152.291667,4.231250,5.505417,[],[],"[blocked_shot, header, volley, blocked_shot]","[shot, blocked_shot, blocked_shot]"
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,51.388571,37.708571,61.020571,285.428571,7.022857,4.618571,[shot],[],"[shot, shot, deflected, header, shot, volley]","[distance, shot, blocked_shot, blocked_shot, s..."
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,53.052174,38.691304,61.745435,228.913043,8.869565,4.588043,"[header, shot]",[],"[shot, shot, distance, blocked_shot, shot, sho...","[distance, shot, distance, distance]"
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,53.052174,38.691304,61.745435,228.913043,8.869565,4.588043,"[shot, header]",[],"[deflected, distance, header, header, distance...","[shot, distance, distance, distance, distance,..."
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,52.175000,49.100000,89.423958,214.583333,3.420833,3.468333,"[shot, shot, shot, shot]","[shot, header]","[distance, shot, blocked_shot, direct_freekick...","[direct_freekick, distance, deflected, shot]"
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,52.175000,49.100000,89.423958,214.583333,3.420833,3.468333,[shot],[],"[blocked_shot, distance, shot, header, header,...","[shot, blocked_shot, shot, shot, blocked_shot]"
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,50.412500,42.050000,73.967500,135.208333,6.852083,6.145417,[loose_ball],[],"[blocked_shot, shot, blocked_shot, shot, block...","[blocked_shot, shot, header, blocked_shot, shot]"
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,57.356522,40.765217,57.731522,56.086957,3.039130,6.183043,[],[],"[deflected, blocked_shot, blocked_shot, header...","[header, shot, shot, header, direct_freekick, ..."
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,53.787500,38.750000,57.942708,162.083333,9.991667,6.042083,[saved_back_into_play],[shot],"[blocked_shot, shot, shot, direct_freekick, bl...","[blocked_shot, distance, blocked_shot, distanc..."
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,54.200000,36.125000,53.967917,144.583333,6.110417,6.210000,"[shot, shot]",[],"[blocked_shot, deflected, blocked_shot, blocke...","[shot, distance, shot, volley, shot, blocked_s..."
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,58.362500,42.537500,58.314792,228.958333,7.500000,6.210000,"[shot, shot, shot, shot]",[shot],"[blocked_shot, blocked_shot, direct_freekick, ...","[blocked_shot, distance]"
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,58.362500,42.537500,58.314792,228.958333,7.500000,6.210000,"[distance, shot]",[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_shot, blocked_shot, header, header, s..."
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,54.875000,40.325000,59.913542,234.583333,7.691667,6.210000,[],"[shot, post, shot, loose_ball]","[distance, deflected]","[blocked_shot, blocked_shot, distance, shot, h..."
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,55.962500,42.237500,61.877292,79.791667,8.097917,6.210000,"[header, loose_ball]","[header, distance]","[shot, shot, shot, deflected, header, header, ...","[blocked_shot, blocked_shot, blocked_shot, sho..."
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,54.748936,42.991489,66.053830,191.063830,12.014894,6.183617,"[shot, shot]",[shot],"[blocked_shot, shot, blocked_shot, distance, b...","[shot, distance, blocked_shot, shot]"
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,53.982979,46.093617,75.237872,177.659574,11.723404,6.130851,"[header, shot]",[],"[blocked_shot, shot, shot, blocked_shot, shot,...","[shot, blocked_shot, distance, deflected, dist..."
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,62.337500,47.862500,60.548958,92.083333,7.114583,6.210000,[volley],[header],"[distance, distance, shot, blocked_shot, heade...",[direct_freekick]
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,62.337500,47.862500,60.548958,92.083333,7.114583,6.210000,"[shot, shot]",[shot],"[header, distance, blocked_shot, shot, blocked...","[blocked_shot, distance, distance, direct_free..."

In [275]:
def split_shotoff_stats(df):
    shotoff_list = df['shotoff'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],shotoff_list):
        home_shots = []
        away_shots = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_shots.append(i[0])
                else:
                    away_shots.append(i[0])
        except:
            home_shots.append('')
            away_shots.append('')
        home_full.append(home_shots)
        away_full.append(away_shots)
    df['home_shotoff_types'] = home_full
    df['away_shotoff_types'] = away_full
    return df

In [276]:
split_shotoff_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,humidity,wind direction,wind speed (mph),visibility (mi),home_goal_types,away_goal_types,home_shoton_types,away_shoton_types,home_shotoff_types,away_shotoff_types
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,60.205778,269.333333,12.264444,6.210000,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]","[lob, header, deflected, direct_freekick, shot]",[]
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,60.205778,269.333333,12.264444,6.210000,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis...","[shot, header, header, distance, distance, dis...","[shot, direct_freekick]"
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,70.591064,248.297872,16.000000,6.210000,"[loose_ball, shot]","[shot, shot]","[blocked_shot, blocked_shot]","[deflected, blocked_shot, shot, blocked_shot, ...","[shot, distance, header, header, distance, dir...","[header, shot, distance, header]"
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,75.937708,246.041667,11.908333,6.210000,[bicycle_kick],"[distance, volley]","[distance, blocked_shot, direct_freekick, head...","[distance, distance, blocked_shot]","[header, shot, shot, post, header]",[miss_kick]
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,65.895833,276.250000,11.150000,6.210000,[saved_back_into_play],[header],"[deflected, blocked_shot, shot, blocked_shot, ...","[big chance shot, distance, direct_freekick, b...","[shot, direct_freekick, header, shot]","[header, big chance shot]"
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,73.579583,247.916667,13.200000,6.210000,[],[shot],"[shot, shot, blocked_shot, big chance blocked,...","[blocked_shot, big chance shot]","[shot, shot, deflected, header, shot, shot]","[shot, volley, header, header, shot]"
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,68.910833,239.166667,8.700000,6.210000,"[tap_in, shot]",[distance],"[blocked_shot, shot, shot, distance]",[],"[distance, shot, distance, distance, shot]","[header, volley, deflected]"
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,75.326957,269.782609,22.876087,6.129130,"[shot, tap_in]",[shot],"[shot, shot, blocked_shot, blocked_shot]","[distance, distance, big chance shot, blocked_...","[distance, bad shot, distance, distance, dista...","[bad shot, shot, big chance crossbar, big chan..."
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,77.494130,270.000000,20.752174,6.210000,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b...","[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]"
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,75.293830,302.765957,13.161702,6.210000,[shot],"[loose_ball, tap_in, tap_in]",[shot],"[blocked_shot, shot, blocked_shot]","[shot, shot, volley, distance]","[deflected, bad shot, direct_freekick, volley]"
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,72.571250,274.375000,7.472917,6.210000,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[blocked_shot, shot, big chance header, shot]","[header, direct_freekick, distance, header, he...","[header, direct_freekick, shot, bad shot, shot..."
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,57.807708,281.666667,10.300000,6.210000,"[shot, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, big...","[distance, blocked_shot, big chance shot, big ...","[distance, shot, header, deflected, distance, ...",[deflected]
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,52.702273,278.181818,10.172727,6.210000,[distance],"[volley, distance, shot]","[header, blocked_shot, blocked_shot, blocked_s...","[blocked_shot, blocked_shot, header, shot, blo...","[volley, volley]","[miss_kick, shot, big chance post, shot]"
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,77.567500,264.375000,10.856250,6.132500,"[header, shot]","[tap_in, header]","[blocked_shot, blocked_shot]","[blocked_shot, blocked_shot, blocked_shot, big...","[big chance shot, direct_freekick, lob, shot]","[distance, shot, shot, volley, shot, distance]"
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,60.426571,208.571429,6.365714,6.210000,[],[],"[blocked_shot, shot, shot]","[direct_freekick, blocked_shot, big chance shot]","[header, header, header, distance, post]","[shot, deflected, header, bad shot]"
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,74.493333,270.416667,9.708333,6.210000,[shot],[],"[blocked_shot, blocked_shot, shot, distance, b...","[shot, blocked_shot, shot, blocked_shot, block...","[volley, shot]","[shot, deflected, shot, bad shot, big chance h..."
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,77.648333,241.250000,5.866667,6.210000,[tap_in],[loose_ball],"[blocked_shot, blocked_shot, blocked_shot, dis...","[shot, distance, blocked_shot, volley]","[deflected, shot]","[direct_freekick, shot, volley, deflected, mis..."
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,77.503478,174.565217,4.447826,6.210000,[header],[tap_in],"[blocked_shot, shot, blocked_shot, distance]","[header, blocked_shot, distance, blocked_shot]","[distance, distance, bicycle_kick, volley, def...","[bad shot, direct_freekick, bad shot, distance]"
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,61.875000,219.791667,6.845833,6.210000,"[shot, header, header, tap_in]",[],"[distance, blocked_shot, blocked_shot, blocked...",[distance],"[deflected, header, crossbar, bicycle_kick, de...","[distance, big chance shot, header, bad shot, ..."
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,85.085417,100.000000,10.877083,5.955417,"[volley, shot, shot]",[],[shot],"[blocked_shot, blocked_shot, shot, big chance ...","[shot, volley, header, shot]","[volley, deflected, bad shot, header, header]"
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,83.886383,268.085106,14.457447,6.210000,[],[],"[shot, blocked_shot, volley, shot]","[shot, blocked_shot, volley, blocked_shot]","[crossbar, header, deflected, bad shot, direct...","[miss_kick, header, header, bad shot]"
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,87.592444,264.888889,14.028889,6.058444,"[shot, header, shot, deflected, shot]","[shot, shot, header, shot]","[blocked_shot, blocked_shot, blocked_shot, sho...","[blocked_shot, blocked_shot, big chance shot, ...","[big chance crossbar, distance, shot, big chan...",[shot]
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,90.805833,256.041667,10.400000,5.784792,[],[shot],"[shot, blocked_shot, big chance shot, blocked_...","[blocked_shot, shot]","[shot, distance, big chance crossbar, deflecte...","[distance, shot, distance, big chance header]"
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,71.879048,268.571429,15.276190,6.210000,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]","[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]"
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,70.263750,272.500000,11.187500,6.031667,[shot],[],"[header, shot, blocked_shot, shot, shot]","[blocked_shot, shot, shot, shot, header, dista...","[deflected, crossbar, shot, deflected, deflect...","[shot, shot, header, distance, deflected, shot..."
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,79.656667,275.833333,16.408333,6.210000,"[shot, volley, shot]",[],"[distance, shot, distance, shot, shot, distance]","[shot, blocked_shot, blocked_shot, blocked_sho...","[distance, header, shot, distance, big chance ...","[deflected, bad shot, distance, header, bad sh..."
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,64.892000,266.000000,13.293333,6.196222,[deflected],"[loose_ball, tap_in, loose_ball]","[blocked_shot, big chance shot]","[header, blocked_shot, distance, blocked_shot,...",[bad shot],"[deflected, bad shot, bad shot, volley, header]"
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,71.602500,245.208333,6.008333,6.023750,"[shot, shot]",[header],"[shot, header]","[distance, volley]","[post, distance, post, distance, distance, shot]","[direct_freekick, deflected, shot, header, dis..."
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,75.115106,264.255319,10.623404,6.210000,[header],[shot],"[shot, blocked_shot, blocked_shot, blocked_sho...","[shot, header, blocked_shot, shot, blocked_sho...","[volley, shot, big chance shot, shot]","[deflected, deflected, shot, shot, shot, heade..."
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,63.360208,275.208333,9.708333,6.210000,[],"[shot, shot]","[big chance volley, blocked_shot, blocked_shot]","[header, shot, shot, big chance shot, blocked_...","[header, big chance volley, shot, bad shot]","[big chance shot, shot, header, bad shot, bad ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,90.794375,117.291667,4.666667,4.557083,"[saved_back_into_play, shot, loose_ball]",[],"[blocked_shot, distance, distance, shot, heade...","[blocked_shot, header, direct_freekick, blocke...","[distance, distance, deflected, post, header, ...","[header, distance, header, deflected, header]"
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,77.522708,78.541667,17.687500,5.460833,[],[],"[distance, blocked_shot, blocked_shot, blocked...","[header, distance]","[crossbar, distance, deflected, header, distan...",[]
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,77.715625,305.000000,8.308333,6.210000,[],[],"[header, shot, blocked_shot, blocked_shot, vol...","[blocked_shot, distance, shot]","[direct_freekick, distance, header, direct_fre...","[distance, direct_freekick, distance, post, di..."
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,77.960000,215.652174,5.776087,6.129130,[],[shot],"[shot, blocked_shot, distance, blocked_shot, d...",[shot],"[distance, volley, header, shot, distance, sho...","[shot, shot, shot]"
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,77.960000,215.652174,5.776087,6.129130,[],"[shot, shot]","[shot, shot, deflected, shot, blocked_shot]","[blocked_shot, deflected, blocked_shot, deflec...","[deflected, deflected, distance, deflected, di...","[header, header, deflected, deflected, header,..."
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,70.323333,252.708333,6.660417,6.210000,[],[],"[distance, header, shot, header, shot, direct_...","[distance, shot]","[distance, shot, shot, deflected, distance, de...",[distance]
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,70.004583,161.250000,4.691667,6.210000,[],[],"[header, blocked_shot, shot, blocked_shot, sho...","[blocked_shot, shot, shot, blocked_shot]","[distance, shot, shot, distance, shot, header,...","[shot, shot, shot, distance, distance, distanc..."
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,70.004583,161.250000,4.691667,6.210000,"[shot, header]",[shot],"[deflected, distance, blocked_shot, header, sh...","[deflected, shot, header, shot, blocked_shot, ...","[distance, header, shot, direct_freekick]","[distance, distance, distance, distance, heade..."
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,78.639778,182.222222,4.797778,4.634222,[loose_ball],[],"[shot, header, blocked_shot, shot, shot, shot,...","[distance, blocked_shot, blocked_shot, deflect...","[distance, distance]","[header, shot, header, direct_freekick, shot, ..."
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,75.862292,216.250000,6.272917,6.158333,"[shot, shot, shot, shot]","[shot, header]","[blocked_shot, shot, blocked_shot, distance]","[distance, blocked_shot, shot, distance]","[shot, shot, direct_freekick, shot, header, di...","[header, distance, deflected, header, distance..."
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,70.092500,243.750000,11.090625,6.035625,[volley],[shot],"[distance, shot, blocked_shot, shot, blocked_s...","[header, shot, direct_freekick, blocked_shot]","[crossbar, shot, shot, header, shot, shot]","[shot, distance, distance]"
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,55.590833,127.083333,2.887500,6.210000,"[shot, shot]",[],"[blocked_shot, shot, blocked_shot, header, shot]","[blocked_shot, blocked_shot, volley]","[deflected, header, distance, shot, header, di...","[distance, distance, deflected, distance]"
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,68.024792,152.291667,4.231250,5.505417,[],[],"[blocked_shot, header, volley, blocked_shot]","[shot, blocked_shot, blocked_shot]","[distance, deflected, distance, distance, shot...","[shot, crossbar, deflected, shot, distance]"
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,61.020571,285.428571,7.022857,4.618571,[shot],[],"[shot, shot, deflected, header, shot, volley]","[distance, shot, blocked_shot, blocked_shot, s...","[distance, distance, header, distance]","[header, post, distance, distance, shot, heade..."
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,61.745435,228.913043,8.869565,4.588043,"[header, shot]",[],"[shot, shot, distance, blocked_shot, shot, sho...","[distance, shot, distance, distance]","[shot, header, distance, distance, shot, shot,...","[post, volley, distance, distance, deflected, ..."
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,61.745435,228.913043,8.869565,4.588043,"[shot, header]",[],"[deflected, distance, header, header, distance...","[shot, distance, distance, distance, distance,...","[header, distance, deflected, shot, deflected,...","[shot, header, distance, shot, shot]"
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,89.423958,214.583333,3.420833,3.468333,"[shot, shot, shot, shot]","[shot, header]","[distance, shot, blocked_shot, direct_freekick...","[direct_freekick, distance, deflected, shot]","[distance, distance, header, distance, shot, d...","[shot, distance, header, distance, shot, shot,..."
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,89.423958,214.583333,3.420833,3.468333,[shot],[],"[blocked_shot, distance, shot, header, header,...","[shot, blocked_shot, shot, shot, blocked_shot]","[distance, distance, distance, header, header,...","[shot, deflected, distance]"
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,73.967500,135.208333,6.852083,6.145417,[loose_ball],[],"[blocked_shot, shot, blocked_shot, shot, block...","[blocked_shot, shot, header, blocked_shot, shot]","[distance, header, distance, header, distance]","[shot, header, deflected, distance, shot]"
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,57.731522,56.086957,3.039130,6.183043,[],[],"[deflected, blocked_shot, blocked_shot, header...","[header, shot, shot, header, direct_freekick, ...","[header, distance, distance, direct_freekick, ...","[distance, deflected, shot, distance, distance..."
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,57.942708,162.083333,9.991667,6.042083,[saved_back_into_play],[shot],"[blocked_shot, shot, shot, direct_freekick, bl...","[blocked_shot, distance, blocked_shot, distanc...","[distance, deflected, distance]","[distance, header, shot, shot, distance, direc..."
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,53.967917,144.583333,6.110417,6.210000,"[shot, shot]",[],"[blocked_shot, deflected, blocked_shot, blocke...","[shot, distance, shot, volley, shot, blocked_s...","[header, shot, deflected, deflected, distance,...",[]
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,58.314792,228.958333,7.500000,6.210000,"[shot, shot, shot, shot]",[shot],"[blocked_shot, blocked_shot, direct_freekick, ...","[blocked_shot, distance]","[distance, direct_freekick, distance, shot, he...","[volley, header, deflected, shot, distance, di..."
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,58.314792,228.958333,7.500000,6.210000,"[distance, shot]",[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_shot, blocked_shot, header, header, s...","[direct_freekick, shot, shot, distance, deflec...","[deflected, volley, post, header, header]"
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,59.913542,234.583333,7.691667,6.210000,[],"[shot, post, shot, loose_ball]","[distance, deflected]","[blocked_shot, blocked_shot, distance, shot, h...","[header, header, header, header, shot]","[distance, distance, shot, header, shot, heade..."
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,61.877292,79.791667,8.097917,6.210000,"[header, loose_ball]","[header, distance]","[shot, shot, shot, deflected, header, header, ...","[blocked_shot, blocked_shot, blocked_shot, sho...","[shot, shot, shot, shot, shot, shot, shot, sho...","[distance, shot, distance, distance, shot, dis..."
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,66.053830,191.063830,12.014894,6.183617,"[shot, shot]",[shot],"[blocked_shot, shot, blocked_shot, distance, b...","[shot, distance, blocked_shot, shot]","[header, shot, distance, distance, volley, sho...","[distance, deflected, shot, header, deflected]"
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,75.237872,177.659574,11.723404,6.130851,"[header, shot]",[],"[blocked_shot, shot, shot, blocked_shot, shot,...","[shot, blocked_shot, distance, deflected, dist...","[crossbar, shot, shot, shot, shot, shot, header]","[distance, header, volley, header, distance]"
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,60.548958,92.083333,7.114583,6.210000,[volley],[header],"[distance, distance, shot, blocked_shot, heade...",[direct_freekick],"[distance, crossbar, header, post, distance, h...","[header, header]"
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,60.548958,92.083333,7.114583,6.210000,"[shot, shot]",[shot],"[header, distance, blocked_shot, shot, blocked...","[blocked_shot, distance, distance, direct_free...","[crossbar, distance, distance, deflected, dist...","[shot, shot, distance, shot, distance, header,..."

In [277]:
final_merge.drop(['shoton','shotoff'],axis=1,inplace=True)

In [34]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v5.csv',index=False)

In [278]:
def home_goals(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    for types in df['home_goal_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
    df['home_goal_headers'] = header_list
    df['home_goal_freekicks'] = freekick_list
    df['home_goal_volleys'] = volley_list
    df['home_goal_other'] = other_list
    return df

In [279]:
home_goals(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_goal_types,away_goal_types,home_shoton_types,away_shoton_types,home_shotoff_types,away_shotoff_types,home_goal_headers,home_goal_freekicks,home_goal_volleys,home_goal_other
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]","[lob, header, deflected, direct_freekick, shot]",[],1,0,0,1
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis...","[shot, header, header, distance, distance, dis...","[shot, direct_freekick]",0,0,0,1
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,"[loose_ball, shot]","[shot, shot]","[blocked_shot, blocked_shot]","[deflected, blocked_shot, shot, blocked_shot, ...","[shot, distance, header, header, distance, dir...","[header, shot, distance, header]",0,0,0,2
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,[bicycle_kick],"[distance, volley]","[distance, blocked_shot, direct_freekick, head...","[distance, distance, blocked_shot]","[header, shot, shot, post, header]",[miss_kick],0,0,0,1
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,[saved_back_into_play],[header],"[deflected, blocked_shot, shot, blocked_shot, ...","[big chance shot, distance, direct_freekick, b...","[shot, direct_freekick, header, shot]","[header, big chance shot]",0,0,0,1
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,[],[shot],"[shot, shot, blocked_shot, big chance blocked,...","[blocked_shot, big chance shot]","[shot, shot, deflected, header, shot, shot]","[shot, volley, header, header, shot]",0,0,0,0
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,"[tap_in, shot]",[distance],"[blocked_shot, shot, shot, distance]",[],"[distance, shot, distance, distance, shot]","[header, volley, deflected]",0,0,0,2
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,"[shot, tap_in]",[shot],"[shot, shot, blocked_shot, blocked_shot]","[distance, distance, big chance shot, blocked_...","[distance, bad shot, distance, distance, dista...","[bad shot, shot, big chance crossbar, big chan...",0,0,0,2
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b...","[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]",0,0,0,0
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,[shot],"[loose_ball, tap_in, tap_in]",[shot],"[blocked_shot, shot, blocked_shot]","[shot, shot, volley, distance]","[deflected, bad shot, direct_freekick, volley]",0,0,0,1
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[blocked_shot, shot, big chance header, shot]","[header, direct_freekick, distance, header, he...","[header, direct_freekick, shot, bad shot, shot...",0,0,0,0
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,"[shot, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, big...","[distance, blocked_shot, big chance shot, big ...","[distance, shot, header, deflected, distance, ...",[deflected],0,0,0,2
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,[distance],"[volley, distance, shot]","[header, blocked_shot, blocked_shot, blocked_s...","[blocked_shot, blocked_shot, header, shot, blo...","[volley, volley]","[miss_kick, shot, big chance post, shot]",0,0,0,1
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,"[header, shot]","[tap_in, header]","[blocked_shot, blocked_shot]","[blocked_shot, blocked_shot, blocked_shot, big...","[big chance shot, direct_freekick, lob, shot]","[distance, shot, shot, volley, shot, distance]",1,0,0,1
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,[],[],"[blocked_shot, shot, shot]","[direct_freekick, blocked_shot, big chance shot]","[header, header, header, distance, post]","[shot, deflected, header, bad shot]",0,0,0,0
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,[shot],[],"[blocked_shot, blocked_shot, shot, distance, b...","[shot, blocked_shot, shot, blocked_shot, block...","[volley, shot]","[shot, deflected, shot, bad shot, big chance h...",0,0,0,1
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,[tap_in],[loose_ball],"[blocked_shot, blocked_shot, blocked_shot, dis...","[shot, distance, blocked_shot, volley]","[deflected, shot]","[direct_freekick, shot, volley, deflected, mis...",0,0,0,1
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,[header],[tap_in],"[blocked_shot, shot, blocked_shot, distance]","[header, blocked_shot, distance, blocked_shot]","[distance, distance, bicycle_kick, volley, def...","[bad shot, direct_freekick, bad shot, distance]",1,0,0,0
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,"[shot, header, header, tap_in]",[],"[distance, blocked_shot, blocked_shot, blocked...",[distance],"[deflected, header, crossbar, bicycle_kick, de...","[distance, big chance shot, header, bad shot, ...",2,0,0,2
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,"[volley, shot, shot]",[],[shot],"[blocked_shot, blocked_shot, shot, big chance ...","[shot, volley, header, shot]","[volley, deflected, bad shot, header, header]",0,0,1,2
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,[],[],"[shot, blocked_shot, volley, shot]","[shot, blocked_shot, volley, blocked_shot]","[crossbar, header, deflected, bad shot, direct...","[miss_kick, header, header, bad shot]",0,0,0,0
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,"[shot, header, shot, deflected, shot]","[shot, shot, header, shot]","[blocked_shot, blocked_shot, blocked_shot, sho...","[blocked_shot, blocked_shot, big chance shot, ...","[big chance crossbar, distance, shot, big chan...",[shot],1,0,0,4
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,[],[shot],"[shot, blocked_shot, big chance shot, blocked_...","[blocked_shot, shot]","[shot, distance, big chance crossbar, deflecte...","[distance, shot, distance, big chance header]",0,0,0,0
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]","[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]",1,0,0,2
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,[shot],[],"[header, shot, blocked_shot, shot, shot]","[blocked_shot, shot, shot, shot, header, dista...","[deflected, crossbar, shot, deflected, deflect...","[shot, shot, header, distance, deflected, shot...",0,0,0,1
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,"[shot, volley, shot]",[],"[distance, shot, distance, shot, shot, distance]","[shot, blocked_shot, blocked_shot, blocked_sho...","[distance, header, shot, distance, big chance ...","[deflected, bad shot, distance, header, bad sh...",0,0,1,2
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,[deflected],"[loose_ball, tap_in, loose_ball]","[blocked_shot, big chance shot]","[header, blocked_shot, distance, blocked_shot,...",[bad shot],"[deflected, bad shot, bad shot, volley, header]",0,0,0,1
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,"[shot, shot]",[header],"[shot, header]","[distance, volley]","[post, distance, post, distance, distance, shot]","[direct_freekick, deflected, shot, header, dis...",0,0,0,2
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,[header],[shot],"[shot, blocked_shot, blocked_shot, blocked_sho...","[shot, header, blocked_shot, shot, blocked_sho...","[volley, shot, big chance shot, shot]","[deflected, deflected, shot, shot, shot, heade...",1,0,0,0
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,[],"[shot, shot]","[big chance volley, blocked_shot, blocked_shot]","[header, shot, shot, big chance shot, blocked_...","[header, big chance volley, shot, bad shot]","[big chance shot, shot, header, bad shot, bad ...",0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,"[saved_back_into_play, shot, loose_ball]",[],"[blocked_shot, distance, distance, shot, heade...","[blocked_shot, header, direct_freekick, blocke...","[distance, distance, deflected, post, header, ...","[header, distance, header, deflected, header]",0,0,0,3
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,[],[],"[distance, blocked_shot, blocked_shot, blocked...","[header, distance]","[crossbar, distance, deflected, header, distan...",[],0,0,0,0
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,[],[],"[header, shot, blocked_shot, blocked_shot, vol...","[blocked_shot, distance, shot]","[direct_freekick, distance, header, direct_fre...","[distance, direct_freekick, distance, post, di...",0,0,0,0
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,[],[shot],"[shot, blocked_shot, distance, blocked_shot, d...",[shot],"[distance, volley, header, shot, distance, sho...","[shot, shot, shot]",0,0,0,0
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,[],"[shot, shot]","[shot, shot, deflected, shot, blocked_shot]","[blocked_shot, deflected, blocked_shot, deflec...","[deflected, deflected, distance, deflected, di...","[header, header, deflected, deflected, header,...",0,0,0,0
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,[],[],"[distance, header, shot, header, shot, direct_...","[distance, shot]","[distance, shot, shot, deflected, distance, de...",[distance],0,0,0,0
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,[],[],"[header, blocked_shot, shot, blocked_shot, sho...","[blocked_shot, shot, shot, blocked_shot]","[distance, shot, shot, distance, shot, header,...","[shot, shot, shot, distance, distance, distanc...",0,0,0,0
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,"[shot, header]",[shot],"[deflected, distance, blocked_shot, header, sh...","[deflected, shot, header, shot, blocked_shot, ...","[distance, header, shot, direct_freekick]","[distance, distance, distance, distance, heade...",1,0,0,1
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,[loose_ball],[],"[shot, header, blocked_shot, shot, shot, shot,...","[distance, blocked_shot, blocked_shot, deflect...","[distance, distance]","[header, shot, header, direct_freekick, shot, ...",0,0,0,1
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,"[shot, shot, shot, shot]","[shot, header]","[blocked_shot, shot, blocked_shot, distance]","[distance, blocked_shot, shot, distance]","[shot, shot, direct_freekick, shot, header, di...","[header, distance, deflected, header, distance...",0,0,0,4
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,[volley],[shot],"[distance, shot, blocked_shot, shot, blocked_s...","[header, shot, direct_freekick, blocked_shot]","[crossbar, shot, shot, header, shot, shot]","[shot, distance, distance]",0,0,1,0
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,"[shot, shot]",[],"[blocked_shot, shot, blocked_shot, header, shot]","[blocked_shot, blocked_shot, volley]","[deflected, header, distance, shot, header, di...","[distance, distance, deflected, distance]",0,0,0,2
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,[],[],"[blocked_shot, header, volley, blocked_shot]","[shot, blocked_shot, blocked_shot]","[distance, deflected, distance, distance, shot...","[shot, crossbar, deflected, shot, distance]",0,0,0,0
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,[shot],[],"[shot, shot, deflected, header, shot, volley]","[distance, shot, blocked_shot, blocked_shot, s...","[distance, distance, header, distance]","[header, post, distance, distance, shot, heade...",0,0,0,1
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,"[header, shot]",[],"[shot, shot, distance, blocked_shot, shot, sho...","[distance, shot, distance, distance]","[shot, header, distance, distance, shot, shot,...","[post, volley, distance, distance, deflected, ...",1,0,0,1
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,"[shot, header]",[],"[deflected, distance, header, header, distance...","[shot, distance, distance, distance, distance,...","[header, distance, deflected, shot, deflected,...","[shot, header, distance, shot, shot]",1,0,0,1
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,"[shot, shot, shot, shot]","[shot, header]","[distance, shot, blocked_shot, direct_freekick...","[direct_freekick, distance, deflected, shot]","[distance, distance, header, distance, shot, d...","[shot, distance, header, distance, shot, shot,...",0,0,0,4
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,[shot],[],"[blocked_shot, distance, shot, header, header,...","[shot, blocked_shot, shot, shot, blocked_shot]","[distance, distance, distance, header, header,...","[shot, deflected, distance]",0,0,0,1
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,[loose_ball],[],"[blocked_shot, shot, blocked_shot, shot, block...","[blocked_shot, shot, header, blocked_shot, shot]","[distance, header, distance, header, distance]","[shot, header, deflected, distance, shot]",0,0,0,1
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,[],[],"[deflected, blocked_shot, blocked_shot, header...","[header, shot, shot, header, direct_freekick, ...","[header, distance, distance, direct_freekick, ...","[distance, deflected, shot, distance, distance...",0,0,0,0
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,[saved_back_into_play],[shot],"[blocked_shot, shot, shot, direct_freekick, bl...","[blocked_shot, distance, blocked_shot, distanc...","[distance, deflected, distance]","[distance, header, shot, shot, distance, direc...",0,0,0,1
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,"[shot, shot]",[],"[blocked_shot, deflected, blocked_shot, blocke...","[shot, distance, shot, volley, shot, blocked_s...","[header, shot, deflected, deflected, distance,...",[],0,0,0,2
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,"[shot, shot, shot, shot]",[shot],"[blocked_shot, blocked_shot, direct_freekick, ...","[blocked_shot, distance]","[distance, direct_freekick, distance, shot, he...","[volley, header, deflected, shot, distance, di...",0,0,0,4
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,"[distance, shot]",[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_shot, blocked_shot, header, header, s...","[direct_freekick, shot, shot, distance, deflec...","[deflected, volley, post, header, header]",0,0,0,2
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,[],"[shot, post, shot, loose_ball]","[distance, deflected]","[blocked_shot, blocked_shot, distance, shot, h...","[header, header, header, header, shot]","[distance, distance, shot, header, shot, heade...",0,0,0,0
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,"[header, loose_ball]","[header, distance]","[shot, shot, shot, deflected, header, header, ...","[blocked_shot, blocked_shot, blocked_shot, sho...","[shot, shot, shot, shot, shot, shot, shot, sho...","[distance, shot, distance, distance, shot, dis...",1,0,0,1
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,"[shot, shot]",[shot],"[blocked_shot, shot, blocked_shot, distance, b...","[shot, distance, blocked_shot, shot]","[header, shot, distance, distance, volley, sho...","[distance, deflected, shot, header, deflected]",0,0,0,2
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,"[header, shot]",[],"[blocked_shot, shot, shot, blocked_shot, shot,...","[shot, blocked_shot, distance, deflected, dist...","[crossbar, shot, shot, shot, shot, shot, header]","[distance, header, volley, header, distance]",1,0,0,1
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,[volley],[header],"[distance, distance, shot, blocked_shot, heade...",[direct_freekick],"[distance, crossbar, header, post, distance, h...","[header, header]",0,0,1,0
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,"[shot, shot]",[shot],"[header, distance, blocked_shot, shot, blocked...","[blocked_shot, distance, distance, direct_free...","[crossbar, distance, distance, deflected, dist...","[shot, shot, distance, shot, distance, header,...",0,0,0,2

In [280]:
def away_goals(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    for types in df['away_goal_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
    df['away_goal_headers'] = header_list
    df['away_goal_freekicks'] = freekick_list
    df['away_goal_volleys'] = volley_list
    df['away_goal_other'] = other_list
    return df

In [281]:
away_goals(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_shotoff_types,away_shotoff_types,home_goal_headers,home_goal_freekicks,home_goal_volleys,home_goal_other,away_goal_headers,away_goal_freekicks,away_goal_volleys,away_goal_other
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,"[lob, header, deflected, direct_freekick, shot]",[],1,0,0,1,1,0,0,0
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,"[shot, header, header, distance, distance, dis...","[shot, direct_freekick]",0,0,0,1,0,0,0,1
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,"[shot, distance, header, header, distance, dir...","[header, shot, distance, header]",0,0,0,2,0,0,0,2
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,"[header, shot, shot, post, header]",[miss_kick],0,0,0,1,0,0,1,1
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,"[shot, direct_freekick, header, shot]","[header, big chance shot]",0,0,0,1,1,0,0,0
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,"[shot, shot, deflected, header, shot, shot]","[shot, volley, header, header, shot]",0,0,0,0,0,0,0,1
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,"[distance, shot, distance, distance, shot]","[header, volley, deflected]",0,0,0,2,0,0,0,1
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,"[distance, bad shot, distance, distance, dista...","[bad shot, shot, big chance crossbar, big chan...",0,0,0,2,0,0,0,1
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,"[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]",0,0,0,0,0,0,0,2
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,"[shot, shot, volley, distance]","[deflected, bad shot, direct_freekick, volley]",0,0,0,1,0,0,0,3
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,"[header, direct_freekick, distance, header, he...","[header, direct_freekick, shot, bad shot, shot...",0,0,0,0,0,0,0,0
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,"[distance, shot, header, deflected, distance, ...",[deflected],0,0,0,2,0,0,0,0
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,"[volley, volley]","[miss_kick, shot, big chance post, shot]",0,0,0,1,0,0,1,2
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,"[big chance shot, direct_freekick, lob, shot]","[distance, shot, shot, volley, shot, distance]",1,0,0,1,1,0,0,1
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,"[header, header, header, distance, post]","[shot, deflected, header, bad shot]",0,0,0,0,0,0,0,0
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,"[volley, shot]","[shot, deflected, shot, bad shot, big chance h...",0,0,0,1,0,0,0,0
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,"[deflected, shot]","[direct_freekick, shot, volley, deflected, mis...",0,0,0,1,0,0,0,1
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,"[distance, distance, bicycle_kick, volley, def...","[bad shot, direct_freekick, bad shot, distance]",1,0,0,0,0,0,0,1
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,"[deflected, header, crossbar, bicycle_kick, de...","[distance, big chance shot, header, bad shot, ...",2,0,0,2,0,0,0,0
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,"[shot, volley, header, shot]","[volley, deflected, bad shot, header, header]",0,0,1,2,0,0,0,0
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,"[crossbar, header, deflected, bad shot, direct...","[miss_kick, header, header, bad shot]",0,0,0,0,0,0,0,0
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,"[big chance crossbar, distance, shot, big chan...",[shot],1,0,0,4,1,0,0,3
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,"[shot, distance, big chance crossbar, deflecte...","[distance, shot, distance, big chance header]",0,0,0,0,0,0,0,1
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,"[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]",1,0,0,2,0,0,1,2
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,"[deflected, crossbar, shot, deflected, deflect...","[shot, shot, header, distance, deflected, shot...",0,0,0,1,0,0,0,0
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,"[distance, header, shot, distance, big chance ...","[deflected, bad shot, distance, header, bad sh...",0,0,1,2,0,0,0,0
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,[bad shot],"[deflected, bad shot, bad shot, volley, header]",0,0,0,1,0,0,0,3
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,"[post, distance, post, distance, distance, shot]","[direct_freekick, deflected, shot, header, dis...",0,0,0,2,1,0,0,0
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,"[volley, shot, big chance shot, shot]","[deflected, deflected, shot, shot, shot, heade...",1,0,0,0,0,0,0,1
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,"[header, big chance volley, shot, bad shot]","[big chance shot, shot, header, bad shot, bad ...",0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,"[distance, distance, deflected, post, header, ...","[header, distance, header, deflected, header]",0,0,0,3,0,0,0,0
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,"[crossbar, distance, deflected, header, distan...",[],0,0,0,0,0,0,0,0
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,"[direct_freekick, distance, header, direct_fre...","[distance, direct_freekick, distance, post, di...",0,0,0,0,0,0,0,0
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,"[distance, volley, header, shot, distance, sho...","[shot, shot, shot]",0,0,0,0,0,0,0,1
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,"[deflected, deflected, distance, deflected, di...","[header, header, deflected, deflected, header,...",0,0,0,0,0,0,0,2
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,"[distance, shot, shot, deflected, distance, de...",[distance],0,0,0,0,0,0,0,0
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,"[distance, shot, shot, distance, shot, header,...","[shot, shot, shot, distance, distance, distanc...",0,0,0,0,0,0,0,0
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,"[distance, header, shot, direct_freekick]","[distance, distance, distance, distance, heade...",1,0,0,1,0,0,0,1
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,"[distance, distance]","[header, shot, header, direct_freekick, shot, ...",0,0,0,1,0,0,0,0
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,"[shot, shot, direct_freekick, shot, header, di...","[header, distance, deflected, header, distance...",0,0,0,4,1,0,0,1
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,"[crossbar, shot, shot, header, shot, shot]","[shot, distance, distance]",0,0,1,0,0,0,0,1
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,"[deflected, header, distance, shot, header, di...","[distance, distance, deflected, distance]",0,0,0,2,0,0,0,0
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,"[distance, deflected, distance, distance, shot...","[shot, crossbar, deflected, shot, distance]",0,0,0,0,0,0,0,0
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,"[distance, distance, header, distance]","[header, post, distance, distance, shot, heade...",0,0,0,1,0,0,0,0
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,"[shot, header, distance, distance, shot, shot,...","[post, volley, distance, distance, deflected, ...",1,0,0,1,0,0,0,0
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,"[header, distance, deflected, shot, deflected,...","[shot, header, distance, shot, shot]",1,0,0,1,0,0,0,0
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,"[distance, distance, header, distance, shot, d...","[shot, distance, header, distance, shot, shot,...",0,0,0,4,1,0,0,1
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,"[distance, distance, distance, header, header,...","[shot, deflected, distance]",0,0,0,1,0,0,0,0
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,"[distance, header, distance, header, distance]","[shot, header, deflected, distance, shot]",0,0,0,1,0,0,0,0
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,"[header, distance, distance, direct_freekick, ...","[distance, deflected, shot, distance, distance...",0,0,0,0,0,0,0,0
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,"[distance, deflected, distance]","[distance, header, shot, shot, distance, direc...",0,0,0,1,0,0,0,1
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,"[header, shot, deflected, deflected, distance,...",[],0,0,0,2,0,0,0,0
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,"[distance, direct_freekick, distance, shot, he...","[volley, header, deflected, shot, distance, di...",0,0,0,4,0,0,0,1
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,"[direct_freekick, shot, shot, distance, deflec...","[deflected, volley, post, header, header]",0,0,0,2,0,0,0,0
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,"[header, header, header, header, shot]","[distance, distance, shot, header, shot, heade...",0,0,0,0,0,0,0,4
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,"[shot, shot, shot, shot, shot, shot, shot, sho...","[distance, shot, distance, distance, shot, dis...",1,0,0,1,1,0,0,1
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,"[header, shot, distance, distance, volley, sho...","[distance, deflected, shot, header, deflected]",0,0,0,2,0,0,0,1
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,"[crossbar, shot, shot, shot, shot, shot, header]","[distance, header, volley, header, distance]",1,0,0,1,0,0,0,0
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,"[distance, crossbar, header, post, distance, h...","[header, header]",0,0,1,0,1,0,0,0
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,"[crossbar, distance, distance, deflected, dist...","[shot, shot, distance, shot, distance, header,...",0,0,0,2,0,0,0,1

In [282]:
def home_shots(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['home_shoton_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
    df['home_shoton_headers'] = header_list
    df['home_shoton_freekicks'] = freekick_list
    df['home_shoton_volleys'] = volley_list
    df['home_shoton_other'] = other_list
    df['home_shoton_bigchance'] = big_chances
    return df

In [283]:
home_shots(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_goal_other,away_goal_headers,away_goal_freekicks,away_goal_volleys,away_goal_other,home_shoton_headers,home_shoton_freekicks,home_shoton_volleys,home_shoton_other,home_shoton_bigchance
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,1,1,0,0,0,0,0,0,7,0
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,1,0,0,0,1,1,0,0,5,2
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,2,0,0,0,2,0,0,0,2,0
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,1,0,0,1,1,1,1,0,6,0
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,1,1,0,0,0,2,0,0,9,1
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,0,0,0,0,1,0,0,0,5,1
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,2,0,0,0,1,0,0,0,4,0
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,2,0,0,0,1,0,0,0,4,0
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,0,0,0,0,2,0,0,0,5,0
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,1,0,0,0,3,0,0,0,1,0
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,0,0,0,0,0,0,0,0,4,0
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,2,0,0,0,0,2,0,0,12,2
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,1,0,0,1,2,1,0,0,6,1
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,1,1,0,0,1,0,0,0,2,0
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,0,0,0,0,0,0,0,0,3,0
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,1,0,0,0,0,0,0,0,6,0
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,1,0,0,0,1,0,0,0,5,0
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,0,0,0,0,1,0,0,0,4,0
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,2,0,0,0,0,0,0,1,5,0
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,2,0,0,0,0,0,0,0,1,0
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,0,0,0,0,0,0,0,1,3,0
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,4,1,0,0,3,1,0,0,9,0
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,0,0,0,0,1,0,0,0,11,1
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,2,0,0,1,2,0,0,0,4,1
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,1,0,0,0,0,1,0,0,4,0
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,2,0,0,0,0,0,0,0,6,0
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,1,0,0,0,3,0,0,0,2,1
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,2,1,0,0,0,1,0,0,1,0
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,0,0,0,0,1,0,0,0,5,0
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,0,0,0,0,2,0,0,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,3,0,0,0,0,1,0,0,9,0
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,0,0,0,0,0,1,0,0,8,0
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,0,0,0,0,0,2,0,1,9,0
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,0,0,0,0,1,0,0,0,7,0
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,0,0,0,0,2,0,0,0,5,0
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,0,0,0,0,0,2,1,0,5,0
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,0,0,0,0,0,1,0,0,5,0
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,1,0,0,0,1,2,1,0,9,0
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,1,0,0,0,0,2,0,0,8,0
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,4,1,0,0,1,0,0,0,4,0
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,0,0,0,0,1,0,0,0,9,0
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,2,0,0,0,0,1,0,0,4,0
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,0,0,0,0,0,1,0,1,2,0
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,1,0,0,0,0,1,0,1,4,0
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,1,0,0,0,0,0,0,0,7,0
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,1,0,0,0,0,2,0,0,5,0
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,4,1,0,0,1,0,1,0,9,0
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,1,0,0,0,0,2,0,0,7,0
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,1,0,0,0,0,1,0,0,17,0
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,0,0,0,0,0,3,0,0,7,0
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,1,0,0,0,1,0,1,1,4,0
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,2,0,0,0,0,0,0,0,11,0
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,4,0,0,0,1,0,1,0,3,0
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,2,0,0,0,0,0,0,0,13,0
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,0,0,0,0,4,0,0,0,2,0
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,1,1,0,0,1,2,0,0,7,0
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,2,0,0,0,1,1,1,0,7,0
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,1,0,0,0,0,0,0,0,11,0
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,0,1,0,0,0,1,0,0,8,0
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,2,0,0,0,1,1,0,0,6,0

In [284]:
def away_shots(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['away_shoton_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
    df['away_shoton_headers'] = header_list
    df['away_shoton_freekicks'] = freekick_list
    df['away_shoton_volleys'] = volley_list
    df['away_shoton_other'] = other_list
    df['away_shoton_bigchance'] = big_chances
    return df

In [285]:
away_shots(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,home_shoton_headers,home_shoton_freekicks,home_shoton_volleys,home_shoton_other,home_shoton_bigchance,away_shoton_headers,away_shoton_freekicks,away_shoton_volleys,away_shoton_other,away_shoton_bigchance
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,0,0,0,7,0,0,0,0,3,0
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,1,0,0,5,2,0,0,0,4,1
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,0,0,0,2,0,0,0,0,7,0
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,1,1,0,6,0,0,0,0,3,0
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,2,0,0,9,1,0,1,0,4,1
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,0,0,0,5,1,0,0,0,2,1
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,0,0,0,4,0,0,0,0,0,0
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,0,0,0,4,0,0,0,1,4,1
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,0,0,0,5,0,0,0,0,7,0
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,0,0,0,1,0,0,0,0,3,0
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,0,0,0,4,0,1,0,0,3,1
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,2,0,0,12,2,0,0,0,5,2
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,1,0,0,6,1,2,0,0,5,0
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,0,0,0,2,0,0,0,0,4,1
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,0,0,0,3,0,0,1,0,2,1
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,0,0,0,6,0,1,0,0,6,0
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,0,0,0,5,0,0,0,1,3,0
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,0,0,0,4,0,1,0,0,3,0
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,0,0,1,5,0,0,0,0,1,0
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,0,0,0,1,0,1,0,0,5,2
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,0,0,1,3,0,0,0,1,3,0
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,1,0,0,9,0,1,0,0,4,1
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,0,0,0,11,1,0,0,0,2,0
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,0,0,0,4,1,0,0,1,4,0
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,1,0,0,4,0,1,0,0,7,0
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,0,0,0,6,0,0,0,0,7,0
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,0,0,0,2,1,1,0,0,8,1
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,1,0,0,1,0,0,0,1,1,0
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,0,0,0,5,0,2,0,0,14,0
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,0,0,1,2,1,1,0,0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,1,0,0,9,0,3,1,0,8,0
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,1,0,0,8,0,1,0,0,1,0
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,2,0,1,9,0,0,0,0,3,0
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,0,0,0,7,0,0,0,0,1,0
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,0,0,0,5,0,1,0,0,7,0
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,2,1,0,5,0,0,0,0,2,0
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,1,0,0,5,0,0,0,0,4,0
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,2,1,0,9,0,1,0,0,5,0
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,2,0,0,8,0,0,0,0,5,0
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,0,0,0,4,0,0,0,0,4,0
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,0,0,0,9,0,1,1,0,2,0
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,1,0,0,4,0,0,0,1,2,0
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,1,0,1,2,0,0,0,0,3,0
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,1,0,1,4,0,1,0,0,10,0
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,0,0,0,7,0,0,0,0,4,0
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,2,0,0,5,0,0,0,0,8,0
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,0,1,0,9,0,0,1,0,3,0
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,2,0,0,7,0,0,0,0,5,0
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,1,0,0,17,0,1,0,0,4,0
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,3,0,0,7,0,2,1,0,3,0
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,0,1,1,4,0,0,1,0,10,0
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,0,0,0,11,0,0,0,1,5,0
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,0,1,0,3,0,0,0,0,2,0
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,0,0,0,13,0,3,0,0,4,0
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,0,0,0,2,0,1,0,0,6,0
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,2,0,0,7,0,0,0,0,5,0
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,1,1,0,7,0,0,0,0,4,0
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,0,0,0,11,0,0,0,0,5,0
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,1,0,0,8,0,0,1,0,0,0
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,1,0,0,6,0,0,1,0,3,0

In [107]:
def home_shots_off(df):
    bad_shots = []
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['home_shotoff_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        bad_shot = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            elif 'bad shot' in typ:
                bad_shot += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
        bad_shots.append(bad_shot)
    df['home_shotoff_headers'] = header_list
    df['home_shotoff_freekicks'] = freekick_list
    df['home_shotoff_volleys'] = volley_list
    df['home_shotoff_other'] = other_list
    df['home_shotoff_bigchance'] = big_chances
    df['home_shotoff_bad_shot'] = bad_shots
    return df

In [108]:
home_shots_off(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,away_shoton_freekicks,away_shoton_volleys,away_shoton_other,away_shoton_bigchance,home_shotoff_headers,home_shotoff_freekicks,home_shotoff_volleys,home_shotoff_other,home_shotoff_bigchance,home_shotoff_bad_shot
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,0,0,3,0,1,1,0,3,0,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,0,0,4,1,2,0,0,5,0,0
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,0,0,4,0,0,0,1,1,0,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,0,0,3,0,3,0,1,3,0,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,0,0,5,0,0,0,1,7,0,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,0,0,3,0,4,1,0,5,0,0
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,0,1,4,0,0,1,0,6,0,1
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,0,1,4,0,3,0,0,7,0,1
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,0,0,2,0,0,0,0,0,0,0
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,0,2,0,3,2,0,4,0,1
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,0,0,4,0,0,0,0,7,0,0
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,0,0,5,0,1,1,0,8,2,1
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,0,0,5,1,2,1,1,8,1,0
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,0,0,1,0,0,0,0,8,1,1
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,0,0,8,2,0,1,0,8,0,0
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,0,0,3,0,2,0,0,7,0,0
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,0,0,5,0,0,2,1,3,0,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,0,0,2,1,1,0,1,4,3,0
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,0,0,9,3,1,0,1,4,0,0
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,0,7,0,2,0,0,5,0,1
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,0,0,11,1,2,0,3,1,0,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,0,0,3,0,1,0,0,0,0,0
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,0,4,1,1,0,0,4,0,0
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,0,0,9,1,1,0,0,2,0,0
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,0,0,6,0,1,0,0,3,0,0
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,1,0,3,0,0,0,1,1,0,0
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,0,0,2,0,2,0,0,6,0,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,0,0,4,0,1,0,0,6,1,2
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,0,0,2,0,0,0,0,5,0,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,1,0,5,0,2,0,0,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,0,0,1,0,3,0,0,5,2,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,0,0,2,1,1,0,0,4,2,1
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,0,0,0,0,1,1,2,5,1,0
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,0,0,0,0,0,0,0,4,2,0
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,0,0,2,0,1,0,0,2,0,1
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,1,0,6,0,0,0,1,0,0,0
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,0,0,2,0,0,0,1,3,2,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,0,0,1,0,0,2,0,6,0,1
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,0,0,6,0,2,0,0,2,0,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,0,0,3,0,3,1,0,6,2,0
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,0,0,7,2,0,0,0,6,2,0
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,1,0,0,0,0,1,0,9,0,3
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,0,0,4,1,1,0,1,2,1,0
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,0,0,3,1,3,1,0,4,1,1
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,0,0,5,0,2,1,2,4,2,0
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,0,0,4,0,3,1,0,6,1,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,0,0,1,0,0,1,0,11,4,1
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,0,0,3,0,0,1,1,4,0,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,0,0,7,0,0,0,0,2,1,0
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,0,1,7,1,0,0,0,2,0,0
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,0,1,5,1,1,0,0,5,1,0
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,0,0,7,1,2,1,0,3,2,0
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,0,0,11,1,0,1,0,4,0,0
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,1,1,11,3,0,0,0,5,1,0
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,0,6,0,2,1,0,2,0,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,0,0,8,1,2,0,0,5,1,0
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,0,0,1,0,4,1,2,7,1,2
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,0,0,6,0,1,0,0,4,0,0
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,1,3,0,2,0,0,4,0,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,0,0,1,0,1,1,0,6,3,1

In [286]:
def away_shots_off(df):
    bad_shots = []
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['away_shotoff_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        bad_shot = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            elif 'bad shot' in typ:
                bad_shot += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
        bad_shots.append(bad_shot)
    df['away_shotoff_headers'] = header_list
    df['away_shotoff_freekicks'] = freekick_list
    df['away_shotoff_volleys'] = volley_list
    df['away_shotoff_other'] = other_list
    df['away_shotoff_bigchance'] = big_chances
    df['away_shotoff_bad_shot'] = bad_shots
    return df

In [287]:
away_shots_off(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,away_shoton_freekicks,away_shoton_volleys,away_shoton_other,away_shoton_bigchance,away_shotoff_headers,away_shotoff_freekicks,away_shotoff_volleys,away_shotoff_other,away_shotoff_bigchance,away_shotoff_bad_shot
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,0,0,3,0,0,0,0,0,0,0
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,0,0,4,1,0,1,0,1,0,0
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,0,0,7,0,2,0,0,2,0,0
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,0,0,3,0,0,0,0,1,0,0
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,1,0,4,1,1,0,0,1,1,0
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,0,0,2,1,2,0,1,2,0,0
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,0,0,0,0,1,0,1,1,0,0
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,0,1,4,1,1,0,0,2,2,1
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,0,0,7,0,1,1,0,2,0,0
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,0,0,3,0,0,1,1,1,0,1
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,0,0,3,1,1,1,1,3,0,1
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,0,0,5,2,0,0,0,1,0,0
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,0,0,5,0,0,0,0,4,1,0
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,0,0,4,1,0,0,1,5,0,0
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,1,0,2,1,1,0,0,2,0,1
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,0,0,6,0,1,0,1,3,1,1
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,0,1,3,0,0,1,2,6,0,1
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,0,0,3,0,0,1,0,1,0,2
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,0,0,1,0,2,0,0,4,2,1
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,0,0,5,2,2,0,1,1,0,1
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,0,1,3,0,2,0,0,1,0,1
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,0,0,4,1,0,0,0,1,0,0
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,0,0,2,0,1,0,0,3,1,0
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,0,1,4,0,0,0,0,4,0,0
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,0,0,7,0,1,0,0,6,0,0
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,0,0,7,0,2,0,0,6,0,2
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,0,0,8,1,1,0,1,1,0,2
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,0,1,1,0,1,1,0,3,0,0
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,0,0,14,0,1,0,0,6,0,0
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,0,0,5,1,4,0,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,1,0,8,0,3,0,0,2,0,0
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,0,0,1,0,0,0,0,0,0,0
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,0,0,3,0,0,2,0,7,0,0
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,0,0,1,0,0,0,0,3,0,0
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,0,0,7,0,3,0,0,5,0,0
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,0,0,2,0,0,0,0,1,0,0
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,0,0,4,0,1,0,0,9,0,0
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,0,0,5,0,1,0,0,5,0,0
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,0,0,5,0,2,1,0,4,0,0
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,0,0,4,0,2,0,0,8,0,0
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,1,0,2,0,0,0,0,3,0,0
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,0,1,2,0,0,0,0,4,0,0
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,0,0,3,0,0,0,0,5,0,0
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,0,0,10,0,2,1,0,5,0,0
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,0,0,4,0,0,0,1,5,0,0
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,0,0,8,0,1,0,0,4,0,0
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,1,0,3,0,1,0,1,7,0,0
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,0,0,5,0,0,0,0,3,0,0
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,0,0,4,0,1,0,0,4,0,0
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,1,0,3,0,1,0,0,9,0,0
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,1,0,10,0,1,1,0,9,0,0
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,0,1,5,0,0,0,0,0,0,0
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,0,0,2,0,1,0,1,5,0,0
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,0,0,4,0,2,0,1,2,0,0
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,0,0,6,0,2,0,0,5,0,0
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,0,0,5,0,0,1,0,7,0,0
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,0,0,4,0,1,0,0,4,0,0
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,0,0,5,0,2,0,1,2,0,0
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,1,0,0,0,2,0,0,0,0,0
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,1,0,3,0,3,0,0,8,0,0

In [288]:
def clean_html_cross(element):
    try:
        soup = BeautifulSoup(element)
        text = soup.findAll('team')
        output = {}
        for i in text:
            output[i.get_text()] = 0
        for i in text:
            output[i.get_text()] += 1
        return output
    except:
        return element

In [289]:
def split_cross(df):
    cross_dict = df['cross'].map(clean_html_cross)
    home_crosses = []
    away_crosses = []
    for key, id_ in zip(cross_dict,df['home_team_api_id']):
        try:
            for k,v in key.items():
                if float(k) == id_:
                    home_crosses.append(v)
                else:
                    away_crosses.append(v)
        except:
            home_crosses.append('')
            away_crosses.append('')
    df['home_crosses'] = home_crosses
    df['away_crosses'] = away_crosses
    return df

In [290]:
split_cross(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,away_team,Date,full_time_away_goals,full_time_home_goals,...,away_shoton_other,away_shoton_bigchance,away_shotoff_headers,away_shotoff_freekicks,away_shotoff_volleys,away_shotoff_other,away_shotoff_bigchance,away_shotoff_bad_shot,home_crosses,away_crosses
0,3,19,4,2,2,1,Crystal Palace,2014-08-16,1,2,...,3,0,0,0,0,0,0,0,32,9
1,5,10,10,4,0,1,Tottenham,2014-08-16,1,0,...,4,1,0,1,0,1,0,0,26,10
2,6,10,13,3,1,0,Everton,2014-08-16,2,2,...,7,0,2,0,0,2,0,0,18,12
3,0,20,5,4,4,0,Swansea,2014-08-16,2,1,...,3,0,0,0,0,1,0,0,28,5
4,9,10,11,4,2,0,Hull,2014-08-16,1,0,...,4,1,1,0,0,1,1,0,32,21
5,8,9,7,2,3,0,Aston Villa,2014-08-16,1,0,...,2,1,2,0,1,2,0,0,21,24
6,3,9,7,2,1,0,Sunderland,2014-08-16,2,2,...,0,0,1,0,1,1,0,0,20,11
7,6,11,12,6,2,0,Southampton,2014-08-17,1,2,...,4,1,1,0,0,2,2,1,13,31
8,3,11,13,5,5,0,Manchester City,2014-08-17,2,0,...,7,0,1,1,0,2,0,0,21,13
9,3,7,11,3,1,0,Chelsea,2014-08-18,3,1,...,3,0,0,1,1,1,0,1,21,15
10,7,8,11,4,0,1,Newcastle United,2014-08-23,0,0,...,3,1,1,1,1,3,0,1,26,24
11,7,11,6,4,1,0,Leicester,2014-08-23,0,2,...,5,2,0,0,0,1,0,0,27,25
12,9,11,17,8,3,0,West Ham,2014-08-23,3,1,...,5,0,0,0,0,4,1,0,16,17
13,3,18,13,3,4,0,Arsenal,2014-08-23,2,2,...,4,1,0,0,1,5,0,0,8,17
14,5,15,8,2,2,0,West Bromwich Albion,2014-08-23,0,0,...,2,1,1,0,0,2,0,1,20,20
15,3,13,12,1,1,0,Burnley,2014-08-23,0,1,...,6,0,1,0,1,3,1,1,16,21
16,5,10,19,3,3,0,Stoke,2014-08-24,1,1,...,3,0,0,1,2,6,0,1,12,24
17,4,15,10,3,2,0,Manchester United,2014-08-24,1,1,...,3,0,0,1,0,1,0,2,17,18
18,6,6,9,1,1,0,Queens Park Rangers,2014-08-24,0,4,...,1,0,2,0,0,4,2,1,24,22
19,7,7,11,3,1,0,Liverpool,2014-08-25,1,3,...,5,2,2,0,1,1,0,1,10,22
20,6,14,7,2,2,0,Manchester United,2014-08-30,0,0,...,3,0,2,0,0,1,0,1,11,25
21,2,16,12,8,3,0,Chelsea,2014-08-30,6,3,...,4,1,0,0,0,1,0,0,30,9
22,4,5,7,2,1,0,Stoke,2014-08-30,1,0,...,2,0,1,0,0,3,1,0,28,17
23,4,19,12,7,3,0,Crystal Palace,2014-08-30,3,3,...,4,0,0,0,0,4,0,0,28,12
24,6,9,16,6,2,0,Sunderland,2014-08-30,0,1,...,7,0,1,0,0,6,0,0,15,24
25,7,8,16,2,2,0,West Bromwich Albion,2014-08-30,0,3,...,7,0,2,0,0,6,0,2,12,23
26,9,13,18,8,1,0,Southampton,2014-08-30,3,1,...,8,1,1,0,1,1,0,2,15,28
27,7,10,9,3,4,0,Hull,2014-08-31,1,2,...,1,0,1,1,0,3,0,0,12,29
28,10,6,24,6,1,0,Arsenal,2014-08-31,1,1,...,14,0,1,0,0,6,0,0,21,36
29,3,11,17,8,4,0,Liverpool,2014-08-31,3,0,...,5,1,4,0,0,2,1,2,23,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,5,15,15,12,1,0,Hull,2009-01-28,0,2,...,8,0,3,0,0,2,0,0,21,26
1618,3,12,2,2,2,0,West Ham,2009-01-31,0,0,...,1,0,0,0,0,0,0,0,49,5
1619,3,16,12,4,2,0,Hull,2009-07-02,0,0,...,3,0,0,2,0,7,0,0,25,8
1620,4,14,4,1,2,1,Arsenal,2009-08-02,0,0,...,1,0,0,0,0,3,0,0,15,8
1621,11,8,11,6,1,0,Manchester United,2009-08-02,1,0,...,7,0,3,0,0,5,0,0,25,32
1622,3,12,3,2,2,0,Sunderland,2009-02-21,0,0,...,2,0,0,0,0,1,0,0,35,9
1623,6,14,12,3,0,0,Fulham,2009-02-28,0,0,...,4,0,1,0,0,9,0,0,37,21
1624,8,11,13,7,2,0,Wigan,2009-02-28,1,2,...,5,0,1,0,0,5,0,0,33,19
1625,7,18,9,2,2,0,Manchester City,2009-01-03,0,1,...,5,0,2,1,0,4,0,0,20,20
1626,8,6,15,6,1,0,Middlesbrough,2009-04-03,0,4,...,4,0,2,0,0,8,0,0,13,15
1627,4,14,7,3,4,0,Blackburn,2009-03-14,0,4,...,2,0,0,0,0,3,0,0,24,15
1628,3,8,6,3,2,0,Manchester City,2009-03-15,0,1,...,2,0,0,0,0,4,0,0,19,14
1629,4,10,8,4,1,0,West Bromwich Albion,2009-03-16,0,0,...,3,0,0,0,0,5,0,0,9,15
1630,7,8,15,9,2,0,Chelsea,2009-03-21,0,1,...,10,0,2,1,0,5,0,0,15,14
1631,2,9,9,4,3,0,Manchester City,2009-04-04,0,2,...,4,0,0,0,1,5,0,0,16,3
1632,8,7,14,9,1,0,Sunderland,2009-04-04,0,2,...,8,0,1,0,0,4,0,0,11,21
1633,4,17,14,6,0,0,Bolton,2009-11-04,3,4,...,3,0,1,0,1,7,0,0,9,11
1634,1,12,8,6,4,0,West Ham,2009-11-04,0,1,...,5,0,0,0,0,3,0,0,41,19
1635,7,15,8,3,2,0,Newcastle United,2009-04-19,0,1,...,4,0,1,0,0,4,0,0,18,18
1636,6,10,14,5,1,0,Everton,2009-04-22,0,0,...,3,0,1,0,0,9,0,0,37,12
1637,5,11,20,8,0,0,Chelsea,2009-04-25,1,0,...,10,0,1,1,0,9,0,0,4,12
1638,1,13,5,4,0,0,Middlesbrough,2009-04-26,0,2,...,5,0,0,0,0,0,0,0,13,11
1639,4,7,8,3,1,0,Fulham,2009-02-05,1,3,...,2,0,1,0,1,5,0,0,10,11
1640,7,7,10,7,1,0,West Bromwich Albion,2009-02-05,0,1,...,4,0,2,0,1,2,0,0,16,14
1641,4,17,16,9,2,0,Liverpool,2009-09-05,3,0,...,6,0,2,0,0,5,0,0,19,20
1642,2,12,16,8,0,0,Chelsea,2009-10-05,4,1,...,5,0,0,1,0,7,0,0,37,14
1643,7,7,9,3,1,0,Manchester City,2009-05-16,1,2,...,4,0,1,0,0,4,0,0,23,26
1644,4,6,8,5,2,0,Blackburn,2009-05-17,0,2,...,5,0,2,0,1,2,0,0,24,14
1645,0,11,3,1,0,0,Stoke,2009-05-24,1,4,...,0,0,2,0,0,0,0,0,9,1
1646,5,10,17,6,1,0,Middlesbrough,2009-05-24,1,2,...,3,0,3,0,0,8,0,0,9,32

In [291]:
final_merge.drop(['foulcommit','card','cross','corner','home_goal_types','home_shoton_types','home_shotoff_types',
                 'away_goal_types','away_shoton_types','away_shotoff_types'],axis=1,inplace=True)

In [292]:
final_merge['half_time_result'] = final_merge['half_time_result'].map(lambda x: 3 if x=='H' else 0 if x=='A' else 1)
final_merge['result'] = final_merge['result'].map(lambda x: 3 if x=='H' else 0 if x=='A' else 1)

In [293]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1647 entries, 0 to 1646
Data columns (total 70 columns):
away_corners              1647 non-null int64
away_fouls                1647 non-null int64
away_shots                1647 non-null int64
away_shots_target         1647 non-null int64
away_yellow_cards         1647 non-null int64
away_red_cards            1647 non-null int64
away_team                 1647 non-null object
Date                      1647 non-null datetime64[ns]
full_time_away_goals      1647 non-null int64
full_time_home_goals      1647 non-null int64
home_corners              1647 non-null int64
home_fouls                1647 non-null int64
home_red_cards            1647 non-null int64
home_yellow_cards         1647 non-null int64
home_shots                1647 non-null int64
home_shots_target         1647 non-null int64
half_time_away_goals      1647 non-null int64
half_time_home_goals      1647 non-null int64
half_time_result          1647 non-null int64
home_team                 1647 non-null object
Referee                   1285 non-null object
result                    1647 non-null int64
FDCOUK                    1647 non-null object
City                      1647 non-null object
Stadium                   1647 non-null object
Capacity                  1647 non-null float64
Latitude                  1647 non-null float64
Longitude                 1647 non-null float64
Country                   1647 non-null object
closest_station           1647 non-null object
season                    1647 non-null object
date                      1647 non-null datetime64[ns]
home_team_api_id          1647 non-null int64
away_team_api_id          1647 non-null int64
goal                      1647 non-null object
possession                1647 non-null object
date_flip                 1647 non-null datetime64[ns]
station                   1647 non-null object
temp (F)                  1647 non-null float64
dew (F)                   1647 non-null float64
humidity                  1647 non-null float64
wind direction            1647 non-null float64
wind speed (mph)          1647 non-null float64
visibility (mi)           1647 non-null float64
home_goal_headers         1647 non-null int64
home_goal_freekicks       1647 non-null int64
home_goal_volleys         1647 non-null int64
home_goal_other           1647 non-null int64
away_goal_headers         1647 non-null int64
away_goal_freekicks       1647 non-null int64
away_goal_volleys         1647 non-null int64
away_goal_other           1647 non-null int64
home_shoton_headers       1647 non-null int64
home_shoton_freekicks     1647 non-null int64
home_shoton_volleys       1647 non-null int64
home_shoton_other         1647 non-null int64
home_shoton_bigchance     1647 non-null int64
away_shoton_headers       1647 non-null int64
away_shoton_freekicks     1647 non-null int64
away_shoton_volleys       1647 non-null int64
away_shoton_other         1647 non-null int64
away_shoton_bigchance     1647 non-null int64
away_shotoff_headers      1647 non-null int64
away_shotoff_freekicks    1647 non-null int64
away_shotoff_volleys      1647 non-null int64
away_shotoff_other        1647 non-null int64
away_shotoff_bigchance    1647 non-null int64
away_shotoff_bad_shot     1647 non-null int64
home_crosses              1647 non-null int64
away_crosses              1647 non-null int64
dtypes: datetime64[ns](3), float64(9), int64(46), object(12)
memory usage: 913.6+ KB

In [294]:
final_merge.drop(['Date','date_flip','goal'],axis=1,inplace=True)

In [295]:
final_merge.drop(['FDCOUK','Latitude','Longitude','station','closest_station'],axis=1,inplace=True)

In [296]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v7.csv',index=False)

In [297]:
final_merge['possession'][0]

u'<possession><value><comment>78</comment><event_incident_typefk>352</event_incident_typefk><elapsed>24</elapsed><subtype>possession</subtype><sortorder>1</sortorder><awaypos>22</awaypos><homepos>78</homepos><n>128</n><type>special</type><id>3647521</id></value><value><comment>74</comment><elapsed_plus>1</elapsed_plus><event_incident_typefk>352</event_incident_typefk><elapsed>45</elapsed><subtype>possession</subtype><sortorder>3</sortorder><awaypos>26</awaypos><homepos>74</homepos><n>149</n><type>special</type><id>3647655</id></value><value><comment>75</comment><event_incident_typefk>352</event_incident_typefk><elapsed>66</elapsed><subtype>possession</subtype><sortorder>1</sortorder><awaypos>25</awaypos><homepos>75</homepos><n>93</n><type>special</type><id>3647956</id></value><value><comment>77</comment><elapsed_plus>4</elapsed_plus><event_incident_typefk>352</event_incident_typefk><elapsed>90</elapsed><subtype>possession</subtype><sortorder>11</sortorder><awaypos>23</awaypos><homepos>77</homepos><n>147</n><type>special</type><id>3648227</id></value></possession>'

In [298]:
soup = BeautifulSoup(final_merge['possession'][0])
home_text = soup.findAll('homepos')
home_text

[<homepos>78</homepos>,
 <homepos>74</homepos>,
 <homepos>75</homepos>,
 <homepos>77</homepos>]

In [299]:
def clean_home_possession(element):
    try:
        soup = BeautifulSoup(element)
        home_text = soup.findAll('homepos')
        home_pos = home_text[-1].get_text()
        return int(home_pos)
    except:
        return element

In [300]:
def clean_away_possession(element):
    try:
        soup = BeautifulSoup(element)
        away_text = soup.findAll('awaypos')
        away_pos = away_text[-1].get_text()
        return int(away_pos)
    except:
        return element

In [301]:
final_merge['home_possession'] = final_merge['possession'].map(clean_home_possession)
final_merge['away_possession'] = final_merge['possession'].map(clean_away_possession)

In [302]:
final_merge.isnull().sum()

away_corners                0
away_fouls                  0
away_shots                  0
away_shots_target           0
away_yellow_cards           0
away_red_cards              0
away_team                   0
full_time_away_goals        0
full_time_home_goals        0
home_corners                0
home_fouls                  0
home_red_cards              0
home_yellow_cards           0
home_shots                  0
home_shots_target           0
half_time_away_goals        0
half_time_home_goals        0
half_time_result            0
home_team                   0
Referee                   362
result                      0
City                        0
Stadium                     0
Capacity                    0
Country                     0
season                      0
date                        0
home_team_api_id            0
away_team_api_id            0
possession                  0
                         ...
wind speed (mph)            0
visibility (mi)             0
home_goal_headers           0
home_goal_freekicks         0
home_goal_volleys           0
home_goal_other             0
away_goal_headers           0
away_goal_freekicks         0
away_goal_volleys           0
away_goal_other             0
home_shoton_headers         0
home_shoton_freekicks       0
home_shoton_volleys         0
home_shoton_other           0
home_shoton_bigchance       0
away_shoton_headers         0
away_shoton_freekicks       0
away_shoton_volleys         0
away_shoton_other           0
away_shoton_bigchance       0
away_shotoff_headers        0
away_shotoff_freekicks      0
away_shotoff_volleys        0
away_shotoff_other          0
away_shotoff_bigchance      0
away_shotoff_bad_shot       0
home_crosses                0
away_crosses                0
home_possession             0
away_possession             0
dtype: int64

In [303]:
final_merge.drop(['possession'],axis=1,inplace=True)

In [304]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1647 entries, 0 to 1646
Data columns (total 63 columns):
away_corners              1647 non-null int64
away_fouls                1647 non-null int64
away_shots                1647 non-null int64
away_shots_target         1647 non-null int64
away_yellow_cards         1647 non-null int64
away_red_cards            1647 non-null int64
away_team                 1647 non-null object
full_time_away_goals      1647 non-null int64
full_time_home_goals      1647 non-null int64
home_corners              1647 non-null int64
home_fouls                1647 non-null int64
home_red_cards            1647 non-null int64
home_yellow_cards         1647 non-null int64
home_shots                1647 non-null int64
home_shots_target         1647 non-null int64
half_time_away_goals      1647 non-null int64
half_time_home_goals      1647 non-null int64
half_time_result          1647 non-null int64
home_team                 1647 non-null object
Referee                   1285 non-null object
result                    1647 non-null int64
City                      1647 non-null object
Stadium                   1647 non-null object
Capacity                  1647 non-null float64
Country                   1647 non-null object
season                    1647 non-null object
date                      1647 non-null datetime64[ns]
home_team_api_id          1647 non-null int64
away_team_api_id          1647 non-null int64
temp (F)                  1647 non-null float64
dew (F)                   1647 non-null float64
humidity                  1647 non-null float64
wind direction            1647 non-null float64
wind speed (mph)          1647 non-null float64
visibility (mi)           1647 non-null float64
home_goal_headers         1647 non-null int64
home_goal_freekicks       1647 non-null int64
home_goal_volleys         1647 non-null int64
home_goal_other           1647 non-null int64
away_goal_headers         1647 non-null int64
away_goal_freekicks       1647 non-null int64
away_goal_volleys         1647 non-null int64
away_goal_other           1647 non-null int64
home_shoton_headers       1647 non-null int64
home_shoton_freekicks     1647 non-null int64
home_shoton_volleys       1647 non-null int64
home_shoton_other         1647 non-null int64
home_shoton_bigchance     1647 non-null int64
away_shoton_headers       1647 non-null int64
away_shoton_freekicks     1647 non-null int64
away_shoton_volleys       1647 non-null int64
away_shoton_other         1647 non-null int64
away_shoton_bigchance     1647 non-null int64
away_shotoff_headers      1647 non-null int64
away_shotoff_freekicks    1647 non-null int64
away_shotoff_volleys      1647 non-null int64
away_shotoff_other        1647 non-null int64
away_shotoff_bigchance    1647 non-null int64
away_shotoff_bad_shot     1647 non-null int64
home_crosses              1647 non-null int64
away_crosses              1647 non-null int64
home_possession           1647 non-null int64
away_possession           1647 non-null int64
dtypes: datetime64[ns](1), float64(7), int64(48), object(7)
memory usage: 823.5+ KB

In [317]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_vF3.csv',index=False)

In [320]:
final_merge['Stadium'].value_counts()

Stamford Bridge          133
Emirates Stadium         131
White Hart Lane          131
Boleyn Ground            114
Old Trafford              75
Anfield                   74
The Hawthorns             74
Stadium of Light          74
Goodison Park             73
Sports Direct Arena       73
Etihad Stadium            73
Britannia Stadium         73
Villa Park                73
Liberty Stadium           70
St Mary's Stadium         57
Carrow Road               55
Loftus Road               54
Craven Cottage            54
Selhurst Park             37
KC Stadium                37
Cardiff City Stadium      19
Madejski Stadium          19
King Power Stadium        19
Turf Moor                 19
Molineux Stadium          15
Ewood Park                 8
DW Stadium                 8
Reebok Stadium             5
Name: Stadium, dtype: int64

In [321]:
final_merge = final_merge[~final_merge['Stadium'].isin(['Reebok Stadium ','DW Stadium ','Ewood Park '])]
list(final_merge['Stadium'].unique())

['Emirates Stadium ',
 'Boleyn Ground ',
 'King Power Stadium ',
 'Old Trafford ',
 'Loftus Road ',
 'Britannia Stadium ',
 'The Hawthorns ',
 'Anfield ',
 'Sports Direct Arena',
 'Turf Moor ',
 'Villa Park ',
 'Stamford Bridge ',
 'Selhurst Park ',
 'Goodison Park ',
 "St Mary's Stadium ",
 'Liberty Stadium ',
 'KC Stadium ',
 'Stadium of Light ',
 'White Hart Lane ',
 'Etihad Stadium',
 'Carrow Road ',
 'Craven Cottage ',
 'Cardiff City Stadium ',
 'Madejski Stadium ',
 'Molineux Stadium ']

In [322]:
def stadium_dummy(df):
    stadiums = list(df['Stadium'].unique())
    for stad in stadiums:
        column = str('at_'+str.strip(stad))
        df[column] = df['Stadium'].map(lambda x: 1 if str.strip(x) in column else 0)

In [323]:
stadium_dummy(final_merge)
final_merge.head().T

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,0,1,2,3,4
away_corners,3,5,6,0,9
away_fouls,19,10,10,20,10
away_shots,4,10,13,5,11
away_shots_target,2,4,3,4,4
away_yellow_cards,2,0,1,4,2
away_red_cards,1,1,0,0,0
away_team,Crystal Palace,Tottenham,Everton,Swansea,Hull
full_time_away_goals,1,1,2,2,1
full_time_home_goals,2,0,2,1,0
home_corners,9,8,3,4,8
home_fouls,13,12,16,14,10
home_red_cards,0,1,0,0,0
home_yellow_cards,2,1,1,2,1
home_shots,14,18,11,14,19
home_shots_target,6,4,3,5,6
half_time_away_goals,1,0,2,1,0
half_time_home_goals,1,0,1,0,0
half_time_result,1,1,0,0,1
home_team,Arsenal,West Ham,Leicester,Manchester United,Queens Park Rangers
Referee,J Moss,C Foy,M Jones,M Dean,C Pawson
result,3,0,1,0,0
City,London,London,Leicester,Stretford,London
Stadium,Emirates Stadium,Boleyn Ground,King Power Stadium,Old Trafford,Loftus Road
Capacity,60361,35303,32500,75811,18439
Country,England,England,England,England,England
season,2014/2015,2014/2015,2014/2015,2014/2015,2014/2015
date,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00
home_team_api_id,9825,8654,8197,10260,10172
away_team_api_id,9826,8586,8668,10003,8667
temp (F),62.92,62.92,58.3489,57.575,60.125
...,...,...,...,...,...
away_shotoff_bad_shot,0,0,0,0,0
home_crosses,32,26,18,28,32
away_crosses,9,10,12,5,21
home_possession,77,47,36,58,51
away_possession,23,53,64,42,49
at_Emirates Stadium,1,0,0,0,0
at_Boleyn Ground,0,1,0,0,0
at_King Power Stadium,0,0,1,0,0
at_Old Trafford,0,0,0,1,0
at_Loftus Road,0,0,0,0,1
at_Britannia Stadium,0,0,0,0,0
at_The Hawthorns,0,0,0,0,0
at_Anfield,0,0,0,0,0
at_Sports Direct Arena,0,0,0,0,0
at_Turf Moor,0,0,0,0,0
at_Villa Park,0,0,0,0,0
at_Stamford Bridge,0,0,0,0,0
at_Selhurst Park,0,0,0,0,0
at_Goodison Park,0,0,0,0,0
at_St Mary's Stadium,0,0,0,0,0
at_Liberty Stadium,0,0,0,0,0
at_KC Stadium,0,0,0,0,0
at_Stadium of Light,0,0,0,0,0
at_White Hart Lane,0,0,0,0,0
at_Etihad Stadium,0,0,0,0,0
at_Carrow Road,0,0,0,0,0
at_Craven Cottage,0,0,0,0,0
at_Cardiff City Stadium,0,0,0,0,0
at_Madejski Stadium,0,0,0,0,0
at_Molineux Stadium,0,0,0,0,0

In [325]:
final_merge['at_Emirates Stadium'].value_counts()

0    1495
1     131
Name: at_Emirates Stadium, dtype: int64

In [326]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_vF3.csv',index=False)

In [327]:
final_merge['season'].value_counts()

2013/2014    380
2014/2015    378
2012/2013    359
2011/2012    281
2009/2010     76
2010/2011     76
2008/2009     76
Name: season, dtype: int64

In [328]:
final_merge.drop_duplicates(inplace=True)
final_merge['season'].value_counts()

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/pandas/util/decorators.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)

2013/2014    380
2014/2015    378
2012/2013    359
2011/2012    281
2009/2010     76
2010/2011     76
2008/2009     76
Name: season, dtype: int64