In [1]:
import pandas as pd
from haversine import haversine
import sqlite3
import datetime
from bs4 import BeautifulSoup
sqlite_db = '/home/llevin/Desktop/capstone2/databases/database.sqlite'
conn = sqlite3.connect(sqlite_db) 
c = conn.cursor()

In [5]:
epl_path = []
for i in range(25,9,-1):
    if i < 9:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/199'+str(i)+'-199'+str(i+1)+'/Premier.csv')
    elif i == 9:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/199'+str(i)+'-2000/Premier.csv')
    elif i < 19:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/200'+str(i-10)+'-200'+str(i-9)+'/Premier.csv')
    elif i == 19:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/200'+str(i-10)+'-20'+str(i-9)+'/Premier.csv')
    else:
        epl_path.append('/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/20'+str(i-10)+'-20'+str(i-9)+'/Premier.csv')

In [6]:
epl_path

['/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2015-2016/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2014-2015/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2013-2014/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2012-2013/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2011-2012/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2010-2011/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2009-2010/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2008-2009/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2007-2008/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2006-2007/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2005-2006/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2004-2005/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2003-2004/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2002-2003/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2001-2002/Premier.csv',
 '/home/llevin/Desktop/capstone/databases/football-data.co.uk/england/2000-2001/Premier.csv']

In [7]:
premier_data = pd.DataFrame()
for path in epl_path:
    try:
        temp_df = pd.read_csv(path)
        sequence = [premier_data,temp_df]
        premier_data = pd.concat(sequence)
    except:
        pass

In [8]:
premier_data['HomeTeam'].head()

0       Arsenal
1     Leicester
2    Man United
3           QPR
4         Stoke
Name: HomeTeam, dtype: object

In [9]:
premier_data.shape

(4560, 84)

In [10]:
premier_data.rename(columns={'FTHG':'full_time_home_goals','FTAG':'full_time_away_goals','FTR':'result','HTHG':'half_time_home_goals',
                       'HTAG':'half_time_away_goals','HTR':'half_time_result','HS':'home_shots','AS':'away_shots','HST':'home_shots_target',
                       'AST':'away_shots_target','HHW':'home_post','AHW':'away_post','HC':'home_corners','AC':'away_corners','HF':'home_fouls',
                       'AF':'away_fouls','HO':'home_offside','AO':'away_offside','HY':'home_yellow_cards','AY':'away_yellow_cards',
                       'HR':'home_red_cards','AR':'away_red_cards','HBP':'home_booking_pts','ABP':'away_booking_pts',
                            'Attendance':'attendance','HomeTeam':'home_team','AwayTeam':'away_team'},inplace=True)

In [11]:
premier_data.head()

,away_booking_pts,away_corners,away_fouls,away_post,away_offside,away_red_cards,away_shots,away_shots_target,away_yellow_cards,attendance,...,SJH,SYA,SYD,SYH,VCA,VCD,VCH,WHA,WHD,WHH
0,NaN,3,19,NaN,NaN,1,4,2,2,NaN,...,1.25,NaN,NaN,NaN,10.50,6.25,1.25,12.0,5.5,1.25
1,NaN,6,10,NaN,NaN,0,13,3,1,NaN,...,3.00,NaN,NaN,NaN,2.40,3.40,3.20,2.4,3.1,3.10
2,NaN,0,20,NaN,NaN,0,5,4,4,NaN,...,1.36,NaN,NaN,NaN,10.00,5.20,1.36,9.0,4.5,1.36
3,NaN,9,10,NaN,NaN,0,11,4,2,NaN,...,2.50,NaN,NaN,NaN,3.12,3.20,2.55,2.9,3.0,2.60
4,NaN,8,9,NaN,NaN,0,7,2,3,NaN,...,1.95,NaN,NaN,NaN,4.75,3.30,1.95,4.2,3.2,1.95

In [12]:
for col in premier_data.columns:
    print col, premier_data[col].isnull().sum()

away_booking_pts 3800
away_corners 0
away_fouls 0
away_post 3800
away_offside 3800
away_red_cards 0
away_shots 0
away_shots_target 0
away_yellow_cards 0
attendance 3801
away_team 0
B365A 760
B365D 760
B365H 760
BSA 2280
BSD 2280
BSH 2280
BWA 760
BWD 760
BWH 760
Bb1X2 760
BbAH 770
BbAHh 770
BbAv<2.5 760
BbAv>2.5 760
BbAvA 760
BbAvAHA 770
BbAvAHH 770
BbAvD 760
BbAvH 760
BbMx<2.5 760
BbMx>2.5 760
BbMxA 760
BbMxAHA 770
BbMxAHH 770
BbMxD 760
BbMxH 760
BbOU 760
Date 0
Div 0
full_time_away_goals 0
full_time_home_goals 0
result 0
GBA 844
GBD 844
GBH 844
home_booking_pts 3800
home_corners 0
home_fouls 0
home_post 3800
home_offside 3800
home_red_cards 0
home_shots 0
home_shots_target 0
half_time_away_goals 0
half_time_home_goals 0
half_time_result 0
home_yellow_cards 0
home_team 0
IWA 4
IWD 4
IWH 4
LBA 61
LBD 61
LBH 61
PSA 3421
PSD 3421
PSH 3421
Referee 380
SBA 1196
SBD 1196
SBH 1196
SJA 1101
SJD 1101
SJH 1101
SYA 4187
SYD 4187
SYH 4187
VCA 760
VCD 760
VCH 760
WHA 113
WHD 113
WHH 113

In [13]:
premier_data = premier_data[['away_corners','away_fouls','away_shots','away_shots_target','away_yellow_cards',
                            'away_red_cards','attendance','away_team','Date','full_time_away_goals','full_time_home_goals',
                            'home_corners','home_fouls','home_red_cards','home_yellow_cards','home_shots','home_shots_target',
                            'half_time_away_goals','half_time_home_goals','half_time_result','home_team','Referee','result']]

In [14]:
premier_data.head(3).T

                                   0          1           2
away_corners                       3          6           0
away_fouls                        19         10          20
away_shots                         4         13           5
away_shots_target                  2          3           4
away_yellow_cards                  2          1           4
away_red_cards                     1          0           0
attendance                       NaN        NaN         NaN
away_team             Crystal Palace    Everton     Swansea
Date                        16/08/14   16/08/14    16/08/14
full_time_away_goals               1          2           2
full_time_home_goals               2          2           1
home_corners                       9          3           4
home_fouls                        13         16          14
home_red_cards                     0          0           0
home_yellow_cards                  2          1           2
home_shots                        14         11          14
home_shots_target                  6          3           5
half_time_away_goals               1          2           1
half_time_home_goals               1          1           0
half_time_result                   D          A           A
home_team                    Arsenal  Leicester  Man United
Referee                       J Moss    M Jones      M Dean
result                             H          D           A

In [15]:
premier_data.isnull().sum()

away_corners               0
away_fouls                 0
away_shots                 0
away_shots_target          0
away_yellow_cards          0
away_red_cards             0
attendance              3801
away_team                  0
Date                       0
full_time_away_goals       0
full_time_home_goals       0
home_corners               0
home_fouls                 0
home_red_cards             0
home_yellow_cards          0
home_shots                 0
home_shots_target          0
half_time_away_goals       0
half_time_home_goals       0
half_time_result           0
home_team                  0
Referee                  380
result                     0
dtype: int64

In [16]:
stad = pd.read_csv('/home/llevin/Desktop/capstone/databases/other/stadiums-with-GPS-coordinates.csv')

In [17]:
stad.head()

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England

In [37]:
weather = pd.read_table('/home/llevin/Desktop/capstone2/weather_data/raw_weather.txt')

In [38]:
weather.head()

                      #DEBUG: Format Typ    -> comma
0  #DEBUG: Time Period   -> 2000-01-01 00:00:00+0...
1                   #DEBUG: Time Zone     -> Etc/UTC
2  #DEBUG: Data Contact   -> daryl herzmann akrhe...
3                        #DEBUG: Entries Found -> -1
4  station,valid,lon,lat, tmpf ,  dwpf ,  relh , ...

In [39]:
weather_clean = weather.iloc[4:]

In [40]:
weather_clean.head()

                      #DEBUG: Format Typ    -> comma
4  station,valid,lon,lat, tmpf ,  dwpf ,  relh , ...
5  EGLC,2000-01-01 10:20,0.0553,51.5053,48.20,44....
6  EGLL,2000-01-01 15:20,-0.4614,51.4785,48.20,44...
7  EGKK,2000-01-01 15:20,-0.1903,51.1481,48.20,44...
8  EGLL,2000-01-01 15:50,-0.4614,51.4785,48.20,44...

In [41]:
weather.columns

Index([u'#DEBUG: Format Typ    -> comma'], dtype='object')

In [42]:
len(weather_clean)

6659639

In [ ]:
weather_cl = pd.DataFrame(map(lambda x: x.split(','),weather_clean['#DEBUG: Format Typ    -> comma']),
                          columns=['station','date','long','lat','temp (F)','dew (F)','humidity','wind direction',
                                  'wind speed (mph)','prec (in)','visibility (mi)'])

In [ ]:
weather_cl.drop(0,inplace=True)
weather_cl.head()

In [ ]:
len(weather_cl)

In [ ]:
weather_cl.to_csv('/home/llevin/Desktop/capstone/weather_data/weather_df.csv')

In [18]:
weather_cl = pd.read_csv('/home/llevin/Desktop/capstone/cleaned_data/weather_df.csv')

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (5,6,7,9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
stations = weather_cl[['station','long','lat']]
print len(stations)
stations.drop_duplicates(inplace=True)
print len(stations)
stations.reset_index(inplace=True,drop=True)
stations.head()

6659638
107

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/pandas/util/decorators.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)

  station    long      lat
0    EGLC  0.0553  51.5053
1    EGLL -0.4614  51.4785
2    EGKK -0.1903  51.1481
3    EGDL -1.9924  51.5032
4    EGDM -1.7546  51.1618

In [20]:
def weather_merge(stadiums, stations):
    #for each lat/long stadium, find the minimum haversine distance and append that weather station
    for index1 in stadiums.index:
        haversines = []
        for index2 in stations.index:
            h = haversine([stadiums.ix[index1,'Latitude'],stadiums.ix[index1,'Longitude']],
                                       [stations.ix[index2,'lat'],stations.ix[index2,'long']])
            haversines.append([h, index2])
        haversines = sorted(haversines, key=lambda x: x[0])
        min_hav = haversines[0]
        min_station = stations.ix[min_hav[1],'station']
        stadiums.ix[index1,'closest_station'] = min_station
    return stadiums

In [21]:
stadiums = weather_merge(stad,stations)
stadiums.head()

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England,EGLC
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England,EGBB
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England,EGNO
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England,EGNO
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England,EGLC

In [22]:
premier_stad = premier_data.merge(stadiums.iloc[:,1:10],how='left',left_on='home_team',right_on='FDCOUK')

In [23]:
premier_stad.head()

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,Date,full_time_away_goals,...,Referee,result,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,3,19,4,2,2,1,NaN,Crystal Palace,16/08/14,1,...,J Moss,H,Arsenal,London,Emirates Stadium,60361.0,51.555000,-0.108611,England,EGLC
1,6,10,13,3,1,0,NaN,Everton,16/08/14,2,...,M Jones,D,Leicester,Leicester,King Power Stadium,32500.0,52.620278,-1.142222,England,EGNX
2,0,20,5,4,4,0,NaN,Swansea,16/08/14,2,...,M Dean,A,Man United,Stretford,Old Trafford,75811.0,53.463056,-2.291389,England,EGCC
3,9,10,11,4,2,0,NaN,Hull,16/08/14,1,...,C Pawson,A,QPR,London,Loftus Road,18439.0,51.509167,-0.232222,England,EGWU
4,8,9,7,2,3,0,NaN,Aston Villa,16/08/14,1,...,A Taylor,A,Stoke,Stoke-on-Trent,Britannia Stadium,27740.0,52.988333,-2.175556,England,EGOS

In [24]:
premier_stad[['home_team','FDCOUK']]

           home_team          FDCOUK
0            Arsenal         Arsenal
1          Leicester       Leicester
2         Man United      Man United
3                QPR             QPR
4              Stoke           Stoke
5          West Brom       West Brom
6           West Ham        West Ham
7          Liverpool       Liverpool
8          Newcastle       Newcastle
9            Burnley         Burnley
10       Aston Villa     Aston Villa
11           Chelsea         Chelsea
12    Crystal Palace  Crystal Palace
13           Everton         Everton
14       Southampton     Southampton
15           Swansea         Swansea
16              Hull            Hull
17        Sunderland      Sunderland
18         Tottenham       Tottenham
19          Man City        Man City
20           Burnley         Burnley
21           Everton         Everton
22          Man City        Man City
23         Newcastle       Newcastle
24               QPR             QPR
25           Swansea         Swansea
26          West Ham        West Ham
27       Aston Villa     Aston Villa
28         Leicester       Leicester
29         Tottenham       Tottenham
...              ...             ...
4530       Newcastle       Newcastle
4531     Southampton     Southampton
4532       Tottenham       Tottenham
4533        Charlton             NaN
4534        Bradford             NaN
4535       Newcastle       Newcastle
4536         Arsenal         Arsenal
4537     Aston Villa     Aston Villa
4538        Bradford             NaN
4539         Chelsea         Chelsea
4540       Leicester       Leicester
4541       Liverpool       Liverpool
4542      Man United      Man United
4543      Sunderland      Sunderland
4544        West Ham        West Ham
4545         Ipswich         Ipswich
4546       Liverpool       Liverpool
4547           Leeds           Leeds
4548     Southampton     Southampton
4549       Newcastle       Newcastle
4550        Charlton             NaN
4551        Coventry        Coventry
4552           Derby           Derby
4553         Everton         Everton
4554           Leeds           Leeds
4555        Man City        Man City
4556   Middlesbrough   Middlesbrough
4557       Newcastle       Newcastle
4558     Southampton     Southampton
4559       Tottenham       Tottenham

[4560 rows x 2 columns]

In [25]:
premier_stad.isnull().sum()

away_corners               0
away_fouls                 0
away_shots                 0
away_shots_target          0
away_yellow_cards          0
away_red_cards             0
attendance              3801
away_team                  0
Date                       0
full_time_away_goals       0
full_time_home_goals       0
home_corners               0
home_fouls                 0
home_red_cards             0
home_yellow_cards          0
home_shots                 0
home_shots_target          0
half_time_away_goals       0
half_time_home_goals       0
half_time_result           0
home_team                  0
Referee                  380
result                     0
FDCOUK                   114
City                     114
Stadium                  114
Capacity                 114
Latitude                 114
Longitude                114
Country                  114
closest_station          114
dtype: int64

In [26]:
premier_stad[premier_stad['FDCOUK'].isnull()].head(3).T

                                  3046        3054      3058
away_corners                        12          11         5
away_fouls                          16          11        17
away_shots                          12          21         7
away_shots_target                    7          11         2
away_yellow_cards                    2           1         4
away_red_cards                       0           0         1
attendance                         NaN         NaN       NaN
away_team                    Liverpool  Man United    Bolton
Date                          19/08/06    23/08/06  26/08/06
full_time_away_goals                 1           3         0
full_time_home_goals                 1           0         2
home_corners                         0           4         6
home_fouls                          10          14        11
home_red_cards                       0           0         1
home_yellow_cards                    1           1         1
home_shots                           5           8         9
home_shots_target                    3           2         5
half_time_away_goals                 0           0         0
half_time_home_goals                 0           0         0
half_time_result                     D           D         D
home_team             Sheffield United    Charlton  Charlton
Referee                       R Styles       C Foy    M Dean
result                               D           A         H
FDCOUK                             NaN         NaN       NaN
City                               NaN         NaN       NaN
Stadium                            NaN         NaN       NaN
Capacity                           NaN         NaN       NaN
Latitude                           NaN         NaN       NaN
Longitude                          NaN         NaN       NaN
Country                            NaN         NaN       NaN
closest_station                    NaN         NaN       NaN

In [27]:
stad.sort_values('FDCOUK')

,Team,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
56,Aberdeen and Inverness C.T.,Aberdeen,Aberdeen,Pittodrie Stadium,22199,57.159167,-2.088889,Scotland,EGPD
108,Ajaccio,Ajaccio,Ajaccio,Stade François Coty,10660,41.931081,8.776725,France,EGMD
85,Almería,Almeria,Almería,Estadio del Mediterráneo,22000,36.840000,-2.435278,Spain,EGJJ
0,Arsenal,Arsenal,London,Emirates Stadium,60361,51.555000,-0.108611,England,EGLC
1,Aston Villa,Aston Villa,Birmingham,Villa Park,42785,52.509167,-1.884722,England,EGBB
86,Athletic Bilbao,Ath Bilbao,Bilbao,San Mamés,53332,43.264284,-2.950366,Spain,EGJJ
87,Atlético Madrid,Ath Madrid,Madrid,Vicente Calderón,54851,40.401719,-3.720606,Spain,EGJJ
62,FC Augsburg,Augsburg,Augsburg,SGL arena,30660,48.322500,10.882222,Germany,EGMH
131,Auxerre,Auxerre,Auxerre,Stade de l'Abbé-Deschamps,24493,47.786753,3.588664,France,EGMD
88,Barcelona,Barcelona,Barcelona,Camp Nou,99354,41.380870,2.122802,Spain,EGJJ
20,Barnsley,Barnsley,Barnsley,Oakwell,23009,53.552222,-1.467500,England,EGCN
109,Bastia,Bastia,Bastia,Stade Armand Cesari,16480,42.651400,9.442619,France,EGMD
64,Bayern Munich,Bayern Munich,Munich,Allianz Arena,71000,48.218775,11.624753,Germany,EGMH
89,Betis,Betis,Seville,Benito Villamarín,52500,37.356389,-5.981389,Spain,EGJJ
21,Birmingham City,Birmingham,Birmingham,St Andrew's Stadium,30079,52.475703,-1.868189,England,EGBB
2,Blackburn Rovers,Blackburn,Blackburn,Ewood Park,31154,53.728611,-2.489167,England,EGNO
22,Blackpool,Blackpool,Blackpool,Bloomfield Road,16220,53.804722,-3.048056,England,EGNH
3,Bolton Wanderers,Bolton,Bolton,Reebok Stadium,28100,53.580556,-2.535556,England,EGNO
110,Bordeaux,Bordeaux,Bordeaux,Stade Chaban-Delmas,34462,44.829167,-0.597778,France,EGJJ
67,Eintracht Braunschweig,Braunschweig,Braunschweig,Eintracht-Stadion,23325,52.290000,10.521667,Germany,EGSD
132,Brest,Brest,Brest,Stade Francis-Le Blé,16000,48.402932,-4.461694,France,EGJB
23,Brighton & Hove Albion,Brighton,Brighton,American Express Community Stadium,22374,50.861822,-0.083278,England,EGKA
24,Bristol City,Bristol City,Bristol,Ashton Gate,21497,51.440000,-2.620278,England,EGTG
25,Burnley,Burnley,Burnley,Turf Moor,22546,53.789167,-2.230278,England,EGNM
133,Caen,Caen,Caen,Stade Michel d'Ornano,21500,49.179461,-0.396767,France,EGJJ
26,Cardiff City,Cardiff,Cardiff,Cardiff City Stadium,26828,51.472778,-3.203056,England,EGFF
90,Celta de Vigo,Celta,Vigo,Balaídos,31800,42.211842,-8.739711,Spain,EGHE
46,Celtic,Celtic,Glasgow,Celtic Park,60832,55.849711,-4.205589,Scotland,EGPF
4,Chelsea,Chelsea,London,Stamford Bridge,42449,51.481667,-0.191111,England,EGLC
27,Coventry City,Coventry,Coventry,Ricoh Arena,32609,52.448056,-1.495556,England,EGBE
...,...,...,...,...,...,...,...,...,...
76,Schalke 04,Schalke 04,Gelsenkirchen,Veltins-Arena,61673,51.554503,7.067589,Germany,EGSD
101,Sevilla,Sevilla,Seville,Ramón Sánchez Pizjuán,45500,37.384000,-5.970500,Spain,EGJJ
125,Sochaux,Sochaux,Montbéliard,Stade Auguste Bonal,20005,47.512417,6.811200,France,EGMD
100,Real Sociedad,Sociedad,San Sebastián,Anoeta,32076,43.301378,-1.973617,Spain,EGJJ
41,Southampton,Southampton,Southampton,St Mary's Stadium,32689,50.905833,-1.391111,England,EGHI
134,Sporting de Gijón,Sp Gijon,Gijón,El Molinón,30000,43.536111,-5.637222,Spain,EGJJ
124,Saint-Étienne,St Etienne,Saint-Étienne,Stade Geoffroy-Guichard,26747,45.460833,4.390278,France,EGJJ
54,St. Johnstone,St Johnstone,Perth,McDiarmid Park,10673,56.409686,-3.476928,Scotland,EGPN
58,St. Mirren,St Mirren,Paisley,St. Mirren Park,8016,55.850556,-4.443889,Scotland,EGPF
84,FC St. Pauli,St Pauli,Hamburg,Millerntor-Stadion,24487,53.554444,9.967778,Germany,EGSD
13,Stoke City,Stoke,Stoke-on-Trent,Britannia Stadium,27740,52.988333,-2.175556,England,EGOS
77,VfB Stuttgart,Stuttgart,Stuttgart,Mercedes-Benz Arena,60441,48.792269,9.232031,Germany,EGMH
14,Sunderland,Sunderland,Sunderland,Stadium of Light,48707,54.914400,-1.388200,England,EGNT
15,Swansea City,Swansea,Swansea,Liberty Stadium,20520,51.642200,-3.935100,England,EGOP
16,Tottenham Hotspur,Tottenham,London,White Hart Lane,36230,51.603333,-0.065833,England,EGLC
126,Toulouse,Toulouse,Toulouse,Stadium Municipal,35470,43.583056,1.434167,France,EGJJ
130,Troyes,Troyes,Troyes,Stade de l'Aube,21877,48.307561,4.098458,France,EGMD
102,Valencia,Valencia,Valencia,Mestalla,55000,39.474656,-0.358361,Spain,EGJJ
127,Valenciennes,Valenciennes,Valenciennes,Stade du Hainaut,25172,50.348131,3.533027,France,EGMH
103,Valladolid,Valladolid,Valladolid,Nuevo José Zorrilla,26512,41.644444,-4.761111,Spain,EGJJ
98,Rayo Vallecano,Vallecano,Madrid,Campo de Vallecas,15489,40.391944,-3.658961,Spain,EGJJ
104,Villarreal,Villarreal,Villarreal,El Madrigal,24890,39.944167,-0.103611,Spain,EGJJ
42,Watford,Watford,Watford,Vicarage Road,23500,51.649836,-0.401486,England,EGWU
78,Werder Bremen,Werder Bremen,Bremen,Weserstadion,42100,53.066394,8.837628,Germany,EGSD
17,West Bromwich Albion,West Brom,West Bromwich,The Hawthorns,27877,52.509167,-1.963889,England,EGBB
43,West Ham United,West Ham,London,Boleyn Ground,35303,51.531944,0.039444,England,EGLC
18,Wigan Athletic,Wigan,Wigan,DW Stadium,25133,53.547778,-2.653889,England,EGNO
79,VfL Wolfsburg,Wolfsburg,Wolfsburg,Volkswagen Arena,30000,52.431944,10.803889,Germany,EGSD
19,Wolverhampton Wanderers,Wolves,Wolverhampton,Molineux Stadium,27828,52.590278,-2.130278,England,EGWC
107,Zaragoza,Zaragoza,Zaragoza,La Romareda,34596,41.636592,-0.901822,Spain,EGJJ

In [28]:
premier_stad = premier_stad[~premier_stad['FDCOUK'].isnull()]

In [29]:
premier_stad.isnull().sum()

away_corners               0
away_fouls                 0
away_shots                 0
away_shots_target          0
away_yellow_cards          0
away_red_cards             0
attendance              3744
away_team                  0
Date                       0
full_time_away_goals       0
full_time_home_goals       0
home_corners               0
home_fouls                 0
home_red_cards             0
home_yellow_cards          0
home_shots                 0
home_shots_target          0
half_time_away_goals       0
half_time_home_goals       0
half_time_result           0
home_team                  0
Referee                  380
result                     0
FDCOUK                     0
City                       0
Stadium                    0
Capacity                   0
Latitude                   0
Longitude                  0
Country                    0
closest_station            0
dtype: int64

In [30]:
premier_stad.columns

Index([u'away_corners', u'away_fouls', u'away_shots', u'away_shots_target',
       u'away_yellow_cards', u'away_red_cards', u'attendance', u'away_team',
       u'Date', u'full_time_away_goals', u'full_time_home_goals',
       u'home_corners', u'home_fouls', u'home_red_cards', u'home_yellow_cards',
       u'home_shots', u'home_shots_target', u'half_time_away_goals',
       u'half_time_home_goals', u'half_time_result', u'home_team', u'Referee',
       u'result', u'FDCOUK', u'City', u'Stadium', u'Capacity', u'Latitude',
       u'Longitude', u'Country', u'closest_station'],
      dtype='object')

In [31]:
premier_stad.head()

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,Date,full_time_away_goals,...,Referee,result,FDCOUK,City,Stadium,Capacity,Latitude,Longitude,Country,closest_station
0,3,19,4,2,2,1,NaN,Crystal Palace,16/08/14,1,...,J Moss,H,Arsenal,London,Emirates Stadium,60361.0,51.555000,-0.108611,England,EGLC
1,6,10,13,3,1,0,NaN,Everton,16/08/14,2,...,M Jones,D,Leicester,Leicester,King Power Stadium,32500.0,52.620278,-1.142222,England,EGNX
2,0,20,5,4,4,0,NaN,Swansea,16/08/14,2,...,M Dean,A,Man United,Stretford,Old Trafford,75811.0,53.463056,-2.291389,England,EGCC
3,9,10,11,4,2,0,NaN,Hull,16/08/14,1,...,C Pawson,A,QPR,London,Loftus Road,18439.0,51.509167,-0.232222,England,EGWU
4,8,9,7,2,3,0,NaN,Aston Villa,16/08/14,1,...,A Taylor,A,Stoke,Stoke-on-Trent,Britannia Stadium,27740.0,52.988333,-2.175556,England,EGOS

In [62]:
premier_stad.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v1.csv',index=False)

In [32]:
pd.read_sql('SELECT * FROM Match LIMIT 10', con=conn)

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00

In [33]:
match_data = pd.read_sql('Select * from Match', con=conn)

In [34]:
match_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25945 entries, 0 to 25944
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

In [35]:
match_data['season'].value_counts()

2008/2009    3326
2015/2016    3326
2014/2015    3325
2012/2013    3260
2010/2011    3260
2009/2010    3230
2011/2012    3186
2013/2014    3032
Name: season, dtype: int64

In [36]:
match_data.head(3).T

,0,1,2
id,1,2,3
country_id,1,1,1
league_id,1,1,1
season,2008/2009,2008/2009,2008/2009
stage,1,1,1
date,2008-08-17 00:00:00,2008-08-16 00:00:00,2008-08-16 00:00:00
match_api_id,492473,492474,492475
home_team_api_id,9987,10000,9984
away_team_api_id,9993,9994,8635
home_team_goal,1,0,0
away_team_goal,1,0,3
home_player_X1,NaN,NaN,NaN
home_player_X2,NaN,NaN,NaN
home_player_X3,NaN,NaN,NaN
home_player_X4,NaN,NaN,NaN
home_player_X5,NaN,NaN,NaN
home_player_X6,NaN,NaN,NaN
home_player_X7,NaN,NaN,NaN
home_player_X8,NaN,NaN,NaN
home_player_X9,NaN,NaN,NaN
home_player_X10,NaN,NaN,NaN
home_player_X11,NaN,NaN,NaN
away_player_X1,NaN,NaN,NaN
away_player_X2,NaN,NaN,NaN
away_player_X3,NaN,NaN,NaN
away_player_X4,NaN,NaN,NaN
away_player_X5,NaN,NaN,NaN
away_player_X6,NaN,NaN,NaN
away_player_X7,NaN,NaN,NaN
away_player_X8,NaN,NaN,NaN
...,...,...,...
B365H,1.73,1.95,NaN
B365D,3.4,3.2,NaN
B365A,5,3.6,NaN
BWH,1.75,1.8,NaN
BWD,3.35,3.3,NaN
BWA,4.2,3.95,NaN
IWH,1.85,1.9,NaN
IWD,3.2,3.2,NaN
IWA,3.5,3.5,NaN
LBH,1.8,1.9,NaN
LBD,3.3,3.2,NaN
LBA,3.75,3.5,NaN
PSH,NaN,NaN,NaN
PSD,NaN,NaN,NaN
PSA,NaN,NaN,NaN
WHH,1.7,1.83,NaN
WHD,3.3,3.3,NaN
WHA,4.33,3.6,NaN
SJH,1.9,1.95,NaN
SJD,3.3,3.3,NaN
SJA,4,3.8,NaN
VCH,1.65,2,NaN
VCD,3.4,3.25,NaN
VCA,4.5,3.25,NaN
GBH,1.78,1.85,NaN
GBD,3.25,3.25,NaN
GBA,4,3.75,NaN
BSH,1.73,1.91,NaN
BSD,3.4,3.25,NaN
BSA,4.2,3.6,NaN

In [37]:
for column in match_data.columns:
    print column

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
away_player_5
away_player_6
away_player_7
away_player_8
away_player_9
away_player_10
away_player_11
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
B365H
B365D
B365A
BWH
BWD
BWA
IWH
IWD
IWA
LBH
LBD
LBA
PSH
PSD
PSA
WHH
WHD
WHA
SJH
SJD
SJA
VCH
VCD
VCA
GBH
GBD
GBA
BSH
BSD
BSA

In [8]:
match_data.to_csv('/home/llevin/Desktop/capstone2/raw_data/kaggle_data.csv',index=False)

In [38]:
team_data = pd.read_sql('Select * from Team', con=conn)

In [39]:
team_data.head()

   id  team_api_id team_long_name team_short_name
0   1         9987           Genk             GEN
1   2         9993   Beerschot AC             BAC
2   3        10000  Zulte-Waregem             ZUL
3   4         9994        Lokeren             LOK
4   5         9984  Cercle Bruges             CEB

In [40]:
match_team = match_data.merge(team_data[['team_api_id','team_long_name']],how='inner',\
                                                           left_on='home_team_api_id',right_on='team_api_id')

In [41]:
match_team.rename(columns={'team_long_name':'home_team'},inplace=True)

In [42]:
match_team = match_team.merge(team_data[['team_api_id','team_long_name']],how='inner',\
                                                           left_on='away_team_api_id',right_on='team_api_id')

In [43]:
match_team.rename(columns={'team_long_name':'away_team'},inplace=True)

In [44]:
match_team.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,GBH,GBD,GBA,BSH,BSD,BSA,team_api_id_x,home_team,team_api_id_y,away_team
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,1.78,3.25,4.00,1.73,3.4,4.2,9987,Genk,9993,Beerschot AC
1,483,1,1,2009/2010,5,2009-08-30 00:00:00,665353,9987,9993,1,...,1.90,3.25,3.75,1.83,3.3,3.8,9987,Genk,9993,Beerschot AC
2,524,1,1,2010/2011,1,2010-08-01 00:00:00,838476,9987,9993,2,...,1.95,3.25,3.50,NaN,NaN,NaN,9987,Genk,9993,Beerschot AC
3,759,1,1,2011/2012,1,2011-07-30 00:00:00,1032694,9987,9993,3,...,1.45,4.00,6.25,1.44,4.0,6.5,9987,Genk,9993,Beerschot AC
4,1014,1,1,2012/2013,11,2012-10-20 00:00:00,1224064,9987,9993,3,...,1.50,4.00,5.50,1.53,3.8,5.5,9987,Genk,9993,Beerschot AC

In [45]:
match_team['date'].head()

0    2008-08-17 00:00:00
1    2009-08-30 00:00:00
2    2010-08-01 00:00:00
3    2011-07-30 00:00:00
4    2012-10-20 00:00:00
Name: date, dtype: object

In [46]:
match_team['date'] = pd.to_datetime(match_team['date'])

In [47]:
match_team = match_team[match_team['league_id']==1729]

In [48]:
match_team = match_team[['season','date','home_team_api_id','away_team_api_id','goal','shoton',\
                         'shotoff','foulcommit','card','cross','corner','possession','home_team','away_team']]

In [49]:
match_team.isnull().sum()

season              0
date                0
home_team_api_id    0
away_team_api_id    0
goal                0
shoton              0
shotoff             0
foulcommit          0
card                0
cross               0
corner              0
possession          0
home_team           0
away_team           0
dtype: int64

In [51]:
input_data = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v1.csv')

In [52]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4446 entries, 0 to 4445
Data columns (total 31 columns):
away_corners            4446 non-null int64
away_fouls              4446 non-null int64
away_shots              4446 non-null int64
away_shots_target       4446 non-null int64
away_yellow_cards       4446 non-null int64
away_red_cards          4446 non-null int64
attendance              702 non-null float64
away_team               4446 non-null object
Date                    4446 non-null object
full_time_away_goals    4446 non-null int64
full_time_home_goals    4446 non-null int64
home_corners            4446 non-null int64
home_fouls              4446 non-null int64
home_red_cards          4446 non-null int64
home_yellow_cards       4446 non-null int64
home_shots              4446 non-null int64
home_shots_target       4446 non-null int64
half_time_away_goals    4446 non-null int64
half_time_home_goals    4446 non-null int64
half_time_result        4446 non-null object
home_team               4446 non-null object
Referee                 4066 non-null object
result                  4446 non-null object
FDCOUK                  4446 non-null object
City                    4446 non-null object
Stadium                 4446 non-null object
Capacity                4446 non-null float64
Latitude                4446 non-null float64
Longitude               4446 non-null float64
Country                 4446 non-null object
closest_station         4446 non-null object
dtypes: float64(4), int64(16), object(11)
memory usage: 1.1+ MB

In [53]:
input_data['Date'].head()

0    16/08/14
1    16/08/14
2    16/08/14
3    16/08/14
4    16/08/14
Name: Date, dtype: object

In [54]:
input_data['Date'] = pd.to_datetime(input_data['Date'])

In [55]:
print match_team['home_team'].sort_values().unique()
print input_data['home_team'].sort_values().unique()

[u'Arsenal' u'Aston Villa' u'Birmingham' u'Blackburn' u'Blackpool'
 u'Bolton' u'Bournemouth' u'Burnley' u'Cardiff' u'Chelsea'
 u'Crystal Palace' u'Everton' u'Fulham' u'Hull' u'Leicester' u'Liverpool'
 u'Manchester City' u'Manchester United' u'Middlesbrough'
 u'Newcastle United' u'Norwich' u'Portsmouth' u'Queens Park Rangers'
 u'Reading' u'Southampton' u'Stoke' u'Sunderland' u'Swansea' u'Tottenham'
 u'Watford' u'West Bromwich Albion' u'West Ham' u'Wigan'
 u'Wolverhampton Wanderers']
['Arsenal' 'Aston Villa' 'Birmingham' 'Blackburn' 'Blackpool' 'Bolton'
 'Burnley' 'Cardiff' 'Chelsea' 'Coventry' 'Crystal Palace' 'Derby'
 'Everton' 'Fulham' 'Hull' 'Ipswich' 'Leeds' 'Leicester' 'Liverpool'
 'Man City' 'Man United' 'Middlesbrough' 'Newcastle' 'Norwich' 'Portsmouth'
 'QPR' 'Reading' 'Southampton' 'Stoke' 'Sunderland' 'Swansea' 'Tottenham'
 'Watford' 'West Brom' 'West Ham' 'Wigan' 'Wolves']

In [56]:
input_data['home_team'][input_data['home_team']=='Man United']='Manchester United'
input_data['away_team'][input_data['away_team']=='Man United']='Manchester United'
input_data['home_team'][input_data['home_team']=='Man City']='Manchester City'
input_data['away_team'][input_data['away_team']=='Man City']='Manchester City'
input_data['home_team'][input_data['home_team']=='Newcastle']='Newcastle United'
input_data['away_team'][input_data['away_team']=='Newcastle']='Newcastle United'
input_data['home_team'][input_data['home_team']=='QPR']='Queens Park Rangers'
input_data['away_team'][input_data['away_team']=='QPR']='Queens Park Rangers'
input_data['home_team'][input_data['home_team']=='West Brom']='West Bromwich Albion'
input_data['away_team'][input_data['away_team']=='West Brom']='West Bromwich Albion'
input_data['home_team'][input_data['home_team']=='Wolves']='Wolverhampton Wanderers'
input_data['away_team'][input_data['away_team']=='Wolves']='Wolverhampton Wanderers'

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [57]:
final_input = input_data.merge(match_team,how='inner',left_on=['home_team','away_team','Date'],\
                               right_on=['home_team','away_team','date'])

In [58]:
final_input.head(3).T

,0,1,2
away_corners,3,6,0
away_fouls,19,10,20
away_shots,4,13,5
away_shots_target,2,3,4
away_yellow_cards,2,1,4
away_red_cards,1,0,0
attendance,NaN,NaN,NaN
away_team,Crystal Palace,Everton,Swansea
Date,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00
full_time_away_goals,1,2,2
full_time_home_goals,2,2,1
home_corners,9,3,4
home_fouls,13,16,14
home_red_cards,0,0,0
home_yellow_cards,2,1,2
home_shots,14,11,14
home_shots_target,6,3,5
half_time_away_goals,1,2,1
half_time_home_goals,1,1,0
half_time_result,D,A,A
home_team,Arsenal,Leicester,Manchester United
Referee,J Moss,M Jones,M Dean
result,H,D,A
FDCOUK,Arsenal,Leicester,Man United
City,London,Leicester,Stretford
Stadium,Emirates Stadium,King Power Stadium,Old Trafford
Capacity,60361,32500,75811
Latitude,51.555,52.6203,53.4631
Longitude,-0.108611,-1.14222,-2.29139
Country,England,England,England
closest_station,EGLC,EGNX,EGCC
season,2014/2015,2014/2015,2014/2015
date,2014-08-16 00:00:00,2014-08-16 00:00:00,2014-08-16 00:00:00
home_team_api_id,9825,8197,10260
away_team_api_id,9826,8668,10003
goal,<goal><value><comment>n</comment><stats><goals...,<goal><value><comment>n</comment><stats><goals...,<goal><value><comment>n</comment><stats><goals...
shoton,<shoton><value><stats><blocked>1</blocked></st...,<shoton><value><stats><shoton>1</shoton></stat...,<shoton><value><stats><shoton>1</shoton></stat...
shotoff,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...
foulcommit,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...
card,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...
cross,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...
corner,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...
possession,<possession><value><comment>78</comment><event...,<possession><value><comment>39</comment><event...,<possession><value><comment>60</comment><event...

In [59]:
final_input.isnull().sum()

away_corners               0
away_fouls                 0
away_shots                 0
away_shots_target          0
away_yellow_cards          0
away_red_cards             0
attendance              1763
away_team                  0
Date                       0
full_time_away_goals       0
full_time_home_goals       0
home_corners               0
home_fouls                 0
home_red_cards             0
home_yellow_cards          0
home_shots                 0
home_shots_target          0
half_time_away_goals       0
half_time_home_goals       0
half_time_result           0
home_team                  0
Referee                  254
result                     0
FDCOUK                     0
City                       0
Stadium                    0
Capacity                   0
Latitude                   0
Longitude                  0
Country                    0
closest_station            0
season                     0
date                       0
home_team_api_id           0
away_team_api_id           0
goal                       0
shoton                     0
shotoff                    0
foulcommit                 0
card                       0
cross                      0
corner                     0
possession                 0
dtype: int64

In [60]:
final_input.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1763 entries, 0 to 1762
Data columns (total 43 columns):
away_corners            1763 non-null int64
away_fouls              1763 non-null int64
away_shots              1763 non-null int64
away_shots_target       1763 non-null int64
away_yellow_cards       1763 non-null int64
away_red_cards          1763 non-null int64
attendance              0 non-null float64
away_team               1763 non-null object
Date                    1763 non-null datetime64[ns]
full_time_away_goals    1763 non-null int64
full_time_home_goals    1763 non-null int64
home_corners            1763 non-null int64
home_fouls              1763 non-null int64
home_red_cards          1763 non-null int64
home_yellow_cards       1763 non-null int64
home_shots              1763 non-null int64
home_shots_target       1763 non-null int64
half_time_away_goals    1763 non-null int64
half_time_home_goals    1763 non-null int64
half_time_result        1763 non-null object
home_team               1763 non-null object
Referee                 1509 non-null object
result                  1763 non-null object
FDCOUK                  1763 non-null object
City                    1763 non-null object
Stadium                 1763 non-null object
Capacity                1763 non-null float64
Latitude                1763 non-null float64
Longitude               1763 non-null float64
Country                 1763 non-null object
closest_station         1763 non-null object
season                  1763 non-null object
date                    1763 non-null datetime64[ns]
home_team_api_id        1763 non-null int64
away_team_api_id        1763 non-null int64
goal                    1763 non-null object
shoton                  1763 non-null object
shotoff                 1763 non-null object
foulcommit              1763 non-null object
card                    1763 non-null object
cross                   1763 non-null object
corner                  1763 non-null object
possession              1763 non-null object
dtypes: datetime64[ns](2), float64(4), int64(18), object(19)
memory usage: 606.0+ KB

In [61]:
summary = pd.read_csv('/home/llevin/Desktop/capstone2/scraped_data/whoscored_summary.csv')
defense = pd.read_csv('/home/llevin/Desktop/capstone2/scraped_data/whoscored_defensive.csv')
offense = pd.read_csv('/home/llevin/Desktop/capstone2/scraped_data/whoscored_offensive.csv')

In [62]:
summary.head()

,Unnamed: 0,Team,Possession (%),Pass Accuracy (%),Aerials Won,Season
0,0,Chelsea,56.9,82.5,11.6,2009-2010
1,1,Manchester United,55.6,79.9,13.2,2009-2010
2,2,Tottenham,52.1,76.1,18.2,2009-2010
3,3,Arsenal,57.0,80.8,14.4,2009-2010
4,4,Aston Villa,48.5,71.8,18.8,2009-2010

In [63]:
summary.drop('Unnamed: 0',axis=1,inplace=True)
defense.drop('Unnamed: 0',axis=1,inplace=True)
offense.drop('Unnamed: 0',axis=1,inplace=True)

In [64]:
scraped = summary.merge(defense, how='inner',left_on=['Team','Season'],right_on=['Team','Season'])
scraped = scraped.merge(offense,how='inner',left_on=['Team','Season'],right_on=['Team','Season'])
scraped['Season'] = scraped['Season'].map(lambda x: str(x).replace('-','/'))

In [65]:
scraped.head()

,Team,Possession (%),Pass Accuracy (%),Aerials Won,Season,Shots Conceded,Tackles,Interceptions,Dribbles,Fouls Given
0,Manchester United,55.9,84.8,8.3,2011/2012,13.3,21.1,15.1,8.7,10.2
1,Manchester City,56.6,85.4,9.0,2011/2012,10.4,18.3,16.6,8.6,9.8
2,Tottenham,55.5,84.2,11.0,2011/2012,12.2,19.3,18.8,8.6,10.2
3,Arsenal,57.7,84.1,10.6,2011/2012,10.3,19.7,15.9,9.8,10.8
4,Chelsea,54.2,84.5,8.3,2011/2012,11.8,18.4,16.7,7.5,11.0

In [66]:
final_input = final_input.merge(scraped, how='inner',left_on=['home_team','season'],right_on=['Team','Season'])

In [67]:
final_input.rename(columns={'Possession (%)':'home_possession','Pass Accuracy (%)':'home_passing','Aerials Won':'home_aerials',
                           'Shots Conceded':'home_shots_against','Tackles':'home_tackles','Interceptions':'home_interceptions',
                           'Dribbles':'home_dribbles','Fouls Given':'home_fouls_for'},inplace=True)

In [68]:
final_input = final_input.merge(scraped, how='inner',left_on=['away_team','season'],right_on=['Team','Season'])

In [69]:
final_input.rename(columns={'Possession (%)':'away_possession','Pass Accuracy (%)':'away_passing','Aerials Won':'away_aerials',
                           'Shots Conceded':'away_shots_against','Tackles':'away_tackles','Interceptions':'away_interceptions',
                           'Dribbles':'away_dribbles','Fouls Given':'away_fouls_for'},inplace=True)

In [70]:
for column in final_input.columns:
    print column

away_corners
away_fouls
away_shots
away_shots_target
away_yellow_cards
away_red_cards
attendance
away_team
Date
full_time_away_goals
full_time_home_goals
home_corners
home_fouls
home_red_cards
home_yellow_cards
home_shots
home_shots_target
half_time_away_goals
half_time_home_goals
half_time_result
home_team
Referee
result
FDCOUK
City
Stadium
Capacity
Latitude
Longitude
Country
closest_station
season
date
home_team_api_id
away_team_api_id
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
Team_x
home_possession
home_passing
home_aerials
Season_x
home_shots_against
home_tackles
home_interceptions
home_dribbles
home_fouls_for
Team_y
away_possession
away_passing
away_aerials
Season_y
away_shots_against
away_tackles
away_interceptions
away_dribbles
away_fouls_for

In [71]:
final_input.drop(['Date','Team_x','Season_x','Team_y','Season_y'],axis=1,inplace=True)

In [72]:
final_input.head(3).T

,0,1,2
away_corners,3,4,4
away_fouls,19,17,14
away_shots,4,10,12
away_shots_target,2,3,3
away_yellow_cards,2,1,4
away_red_cards,1,0,0
attendance,NaN,NaN,NaN
away_team,Crystal Palace,Crystal Palace,Crystal Palace
full_time_away_goals,1,0,2
full_time_home_goals,2,0,1
home_corners,9,9,8
home_fouls,13,11,15
home_red_cards,0,0,0
home_yellow_cards,2,2,3
home_shots,14,11,17
home_shots_target,6,3,4
half_time_away_goals,1,0,2
half_time_home_goals,1,0,1
half_time_result,D,D,A
home_team,Arsenal,Queens Park Rangers,Stoke
Referee,J Moss,M Jones,A Marriner
result,H,D,A
FDCOUK,Arsenal,QPR,Stoke
City,London,London,Stoke-on-Trent
Stadium,Emirates Stadium,Loftus Road,Britannia Stadium
Capacity,60361,18439,27740
Latitude,51.555,51.5092,52.9883
Longitude,-0.108611,-0.232222,-2.17556
Country,England,England,England
closest_station,EGLC,EGWU,EGOS
season,2014/2015,2014/2015,2014/2015
date,2014-08-16 00:00:00,2014-12-28 00:00:00,2015-03-21 00:00:00
home_team_api_id,9825,10172,10194
away_team_api_id,9826,9826,9826
goal,<goal><value><comment>n</comment><stats><goals...,<goal />,<goal><value><comment>n</comment><stats><goals...
shoton,<shoton><value><stats><blocked>1</blocked></st...,<shoton><value><stats><blocked>1</blocked></st...,<shoton><value><stats><blocked>1</blocked></st...
shotoff,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...,<shotoff><value><stats><shotoff>1</shotoff></s...
foulcommit,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...,<foulcommit><value><stats><foulscommitted>1</f...
card,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...,<card><value><comment>y</comment><stats><ycard...
cross,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...,<cross><value><stats><crosses>1</crosses></sta...
corner,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...,<corner><value><stats><corners>1</corners></st...
possession,<possession><value><comment>78</comment><event...,<possession><value><comment>51</comment><event...,<possession><value><comment>61</comment><event...
home_possession,55.7,46.3,50.2
home_passing,83.8,70.8,77.5
home_aerials,19.8,21.7,24.4
home_shots_against,10.7,16.4,12
home_tackles,19.4,20.6,19.3
home_interceptions,20.2,14.8,13.2
home_dribbles,15.8,8.1,9.4
home_fouls_for,11,10.3,10.8
away_possession,42.7,42.7,42.7
away_passing,69.4,69.4,69.4
away_aerials,23.7,23.7,23.7
away_shots_against,13.8,13.8,13.8
away_tackles,20.8,20.8,20.8
away_interceptions,15.8,15.8,15.8
away_dribbles,9.4,9.4,9.4
away_fouls_for,11.4,11.4,11.4

In [73]:
final_input.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
attendance              973
away_team                 0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 254
result                    0
FDCOUK                    0
City                      0
Stadium                   0
Capacity                  0
Latitude                  0
Longitude                 0
Country                   0
closest_station           0
season                    0
date                      0
home_team_api_id          0
away_team_api_id          0
goal                      0
shoton                    0
shotoff                   0
foulcommit                0
card                      0
cross                     0
corner                    0
possession                0
home_possession           0
home_passing              0
home_aerials              0
home_shots_against        0
home_tackles              0
home_interceptions        0
home_dribbles             0
home_fouls_for            0
away_possession           0
away_passing              0
away_aerials              0
away_shots_against        0
away_tackles              0
away_interceptions        0
away_dribbles             0
away_fouls_for            0
dtype: int64

In [74]:
final_input.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 973 entries, 0 to 972
Data columns (total 58 columns):
away_corners            973 non-null int64
away_fouls              973 non-null int64
away_shots              973 non-null int64
away_shots_target       973 non-null int64
away_yellow_cards       973 non-null int64
away_red_cards          973 non-null int64
attendance              0 non-null float64
away_team               973 non-null object
full_time_away_goals    973 non-null int64
full_time_home_goals    973 non-null int64
home_corners            973 non-null int64
home_fouls              973 non-null int64
home_red_cards          973 non-null int64
home_yellow_cards       973 non-null int64
home_shots              973 non-null int64
home_shots_target       973 non-null int64
half_time_away_goals    973 non-null int64
half_time_home_goals    973 non-null int64
half_time_result        973 non-null object
home_team               973 non-null object
Referee                 719 non-null object
result                  973 non-null object
FDCOUK                  973 non-null object
City                    973 non-null object
Stadium                 973 non-null object
Capacity                973 non-null float64
Latitude                973 non-null float64
Longitude               973 non-null float64
Country                 973 non-null object
closest_station         973 non-null object
season                  973 non-null object
date                    973 non-null datetime64[ns]
home_team_api_id        973 non-null int64
away_team_api_id        973 non-null int64
goal                    973 non-null object
shoton                  973 non-null object
shotoff                 973 non-null object
foulcommit              973 non-null object
card                    973 non-null object
cross                   973 non-null object
corner                  973 non-null object
possession              973 non-null object
home_possession         973 non-null float64
home_passing            973 non-null float64
home_aerials            973 non-null float64
home_shots_against      973 non-null float64
home_tackles            973 non-null float64
home_interceptions      973 non-null float64
home_dribbles           973 non-null float64
home_fouls_for          973 non-null float64
away_possession         973 non-null float64
away_passing            973 non-null float64
away_aerials            973 non-null float64
away_shots_against      973 non-null float64
away_tackles            973 non-null float64
away_interceptions      973 non-null float64
away_dribbles           973 non-null float64
away_fouls_for          973 non-null float64
dtypes: datetime64[ns](1), float64(20), int64(18), object(19)
memory usage: 448.5+ KB

In [75]:
final_input.shape

(973, 58)

In [125]:
final_input.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v2.csv',index=False)

In [3]:
final_input = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v2.csv')

In [77]:
weather = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/weather_df.csv')

In [78]:
weather.head()

,Unnamed: 0,station,date,long,lat,temp (F),dew (F),humidity,wind direction,wind speed (mph),prec (in),visibility (mi)
0,1,EGLC,2000-01-01 10:20,0.0553,51.5053,48.20,44.60,87.28,310.00,2.3,M,6.21
1,2,EGLL,2000-01-01 15:20,-0.4614,51.4785,48.20,44.60,87.28,180.00,5.8,M,6.21
2,3,EGKK,2000-01-01 15:20,-0.1903,51.1481,48.20,44.60,87.28,M,3.5,M,6.21
3,4,EGLL,2000-01-01 15:50,-0.4614,51.4785,48.20,44.60,87.28,190.00,3.5,M,6.21
4,5,EGKK,2000-01-01 15:50,-0.1903,51.1481,48.20,44.60,87.28,M,2.3,M,6.21

In [79]:
weather.drop(['Unnamed: 0','long','lat'],axis=1,inplace=True)

In [80]:
weather['date'] = pd.to_datetime(weather['date'])
weather['date'] = weather['date'].map(lambda x: datetime.datetime(x.year,x.month,x.day,x.hour))
weather['date'].head()

0   2000-01-01 10:00:00
1   2000-01-01 15:00:00
2   2000-01-01 15:00:00
3   2000-01-01 15:00:00
4   2000-01-01 15:00:00
Name: date, dtype: datetime64[ns]

In [81]:
print weather.shape
weather.drop_duplicates(inplace=True)
print weather.shape

(6659638, 9)
(6233836, 9)

In [82]:
weather = weather.apply(lambda x: x.map(lambda y: 0. if (y=='M' or y==None) else y))

In [83]:
weather[['temp (F)','dew (F)','humidity','wind direction','wind speed (mph)','prec (in)','visibility (mi)']] = weather[['temp (F)','dew (F)','humidity','wind direction','wind speed (mph)','prec (in)','visibility (mi)']].apply(lambda x: x.astype(float))

In [84]:
weather = weather.groupby(['station','date']).mean().reset_index()

In [85]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3919182 entries, 0 to 3919181
Data columns (total 9 columns):
station             object
date                datetime64[ns]
temp (F)            float64
dew (F)             float64
humidity            float64
wind direction      float64
wind speed (mph)    float64
prec (in)           float64
visibility (mi)     float64
dtypes: datetime64[ns](1), float64(7), object(1)
memory usage: 269.1+ MB

In [86]:
final_input['date'] = pd.to_datetime(final_input['date'])
final_input['date'] = final_input['date'].map(lambda x: x + datetime.timedelta(hours=15))
final_input['date'].head()

0   2014-08-16 15:00:00
1   2014-12-28 15:00:00
2   2015-03-21 15:00:00
3   2014-10-25 15:00:00
4   2015-02-28 15:00:00
Name: date, dtype: datetime64[ns]

In [87]:
final_merge = final_input.merge(weather,how='inner',left_on=['date','closest_station'],right_on=['date','station'])

In [88]:
final_merge.isnull().sum()

away_corners              0
away_fouls                0
away_shots                0
away_shots_target         0
away_yellow_cards         0
away_red_cards            0
attendance              912
away_team                 0
full_time_away_goals      0
full_time_home_goals      0
home_corners              0
home_fouls                0
home_red_cards            0
home_yellow_cards         0
home_shots                0
home_shots_target         0
half_time_away_goals      0
half_time_home_goals      0
half_time_result          0
home_team                 0
Referee                 240
result                    0
FDCOUK                    0
City                      0
Stadium                   0
Capacity                  0
Latitude                  0
Longitude                 0
Country                   0
closest_station           0
                       ...
shotoff                   0
foulcommit                0
card                      0
cross                     0
corner                    0
possession                0
home_possession           0
home_passing              0
home_aerials              0
home_shots_against        0
home_tackles              0
home_interceptions        0
home_dribbles             0
home_fouls_for            0
away_possession           0
away_passing              0
away_aerials              0
away_shots_against        0
away_tackles              0
away_interceptions        0
away_dribbles             0
away_fouls_for            0
station                   0
temp (F)                  0
dew (F)                   0
humidity                  0
wind direction            0
wind speed (mph)          0
prec (in)                 0
visibility (mi)           0
dtype: int64

In [21]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v3.csv',index=False)

In [89]:
final_merge.drop_duplicates(inplace=True)

In [90]:
def clean_html_goals_shots(element):
    try:
        soup = BeautifulSoup(element)
        text = zip(soup.findAll('subtype'),soup.findAll('team'))
        output = []
        for i in text:
            output.append((i[0].get_text(),i[1].get_text()))
        return output
    except:
        return element

In [91]:
final_merge['goal'].map(clean_html_goals_shots)

/home/llevin/anaconda2/envs/dsi/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

0       [(header, 9826), (header, 9825), (tap_in, 9825)]
1                         [(missed, 8654), (shot, 8586)]
2                                                     []
3                          [(shot, 10194), (shot, 9826)]
4                         [(shot, 9826), (header, 9826)]
5      [(deflected, 9826), (header, 9826), (header, 9...
6      [(shot, 8650), (direct_freekick, 9826), (tap_i...
7      [(loose_ball, 9826), (deflected, 10261), (voll...
8      [(header, 8191), (shot, 8191), (shot, 9826), (...
9                                                     []
10          [(shot, 8668), (header, 9826), (shot, 9826)]
11                                        [(shot, 8466)]
12                                       [(shot, 10003)]
13     [(deflected, 8456), (shot, 8456), (header, 982...
14     [(shot, 8456), (shot, 9825), (volley, 9825), (...
15     [(header, 8455), (shot, 8455), (shot, 8455), (...
16                                        [(shot, 8456)]
17     [(bicycle_kick, 8456), (shot, 8456), (header, ...
18        [(tap_in, 8654), (header, 8654), (shot, 8456)]
19                          [(shot, 8456), (shot, 8456)]
20                                      [(volley, 8191)]
21                          [(shot, 8455), (shot, 8456)]
22        [(distance, 8456), (shot, 8456), (shot, 8456)]
23     [(deflected, 8456), (shot, 8456), (distance, 1...
24     [(shot, 8456), (shot, 8456), (shot, 8456), (sh...
25                          [(shot, 8586), (shot, 9825)]
26        [(shot, 8455), (header, 8455), (tap_in, 8455)]
27     [(shot, 8586), (backheel, 8197), (direct_freek...
28       [(shot, 10260), (header, 10260), (shot, 10260)]
29               [(direct_freekick, 8586), (shot, 8586)]
                             ...
882                                                   []
883    [(tap_in, 10261), (shot, 10261), (tap_in, 1026...
884                                      [(shot, 10194)]
885       [(shot, 8456), (distance, 8456), (shot, 8456)]
886    [(shot, 9825), (tap_in, 10194), (shot, 9825), ...
887    [(shot, 8472), (deflected, 10194), (direct_fre...
888                                                   []
889                    [(tap_in, 10194), (header, 8586)]
890                                      [(shot, 10261)]
891    [(shot, 10194), (header, 10172), (shot, 10172)...
892                                   [(distance, 8659)]
893    [(shot, 8456), (shot, 10172), (header, 10172),...
894                       [(shot, 10003), (shot, 10172)]
895        [(shot, 9850), (shot, 10172), (tap_in, 9850)]
896    [(shot, 8586), (shot, 8586), (header, 10172), ...
897                                       [(shot, 8659)]
898                    [(deflected, 8455), (shot, 8456)]
899                                                   []
900                                    [(volley, 10003)]
901                                                   []
902    [(header, 10260), (distance, 10260), (shot, 10...
903                       [(shot, 8586), (volley, 8455)]
904    [(bicycle_kick, 8650), (shot, 8650), (header, ...
905                                      [(saved, 8650)]
906                                       [(shot, 8650)]
907                     [(tap_in, 8650), (header, 8650)]
908         [(shot, 8650), (tap_in, 8455), (shot, 8650)]
909                                      [(shot, 10003)]
910       [(shot, 8650), (shot, 8650), (distance, 8650)]
911    [(distance, 8586), (shot, 8650), (shot, 8586),...
Name: goal, dtype: object

In [92]:
def split_goal_stats(df):
    goal_list = df['goal'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],goal_list):
        home_goals = []
        away_goals = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_goals.append(i[0])
                else:
                    away_goals.append(i[0])
        except:
            home_goals.append('')
            away_goals.append('')
        home_full.append(home_goals)
        away_full.append(away_goals)
    df['home_goal_types'] = home_full
    df['away_goal_types'] = away_full
    return df

In [93]:
split_goal_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,station,temp (F),dew (F),humidity,wind direction,wind speed (mph),prec (in),visibility (mi),home_goal_types,away_goal_types
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,EGLC,68.0,47.3,47.490,270.0,16.15,0.0,6.210,"[header, tap_in]",[header]
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,EGLC,68.0,47.3,47.490,270.0,16.15,0.0,6.210,[missed],[shot]
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,EGWU,37.4,28.4,69.670,20.0,4.60,0.0,6.210,[],[]
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,EGOS,50.0,35.6,57.520,10.0,10.40,0.0,6.210,[shot],[shot]
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,EGBB,55.4,49.1,79.325,210.0,8.65,0.0,6.210,[],"[shot, header]"
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,EGLC,50.0,45.5,84.490,215.0,16.10,0.0,6.210,[deflected],"[deflected, header, header]"
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,EGGP,55.4,39.2,54.340,280.0,20.75,0.0,6.210,[shot],"[direct_freekick, tap_in, saved_back_into_play..."
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,EGNT,66.2,50.0,55.880,280.0,18.40,0.0,6.210,"[deflected, header, loose_ball]","[loose_ball, volley, shot]"
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,EGNM,33.8,33.8,100.000,225.0,5.80,0.0,6.210,"[header, shot]","[shot, distance, shot]"
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,EGBB,53.6,50.0,87.560,195.0,17.85,0.0,6.210,[],[]
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,EGGP,64.4,49.1,57.565,5.0,5.20,0.0,6.210,[shot],"[header, shot]"
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,EGHI,44.6,31.1,58.885,275.0,10.95,0.0,6.210,[shot],[]
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,EGOP,51.8,48.2,87.470,150.0,6.90,0.0,6.210,[shot],[]
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,EGCC,46.4,41.0,81.340,290.0,12.70,0.0,6.210,"[deflected, shot, shot]",[header]
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,EGLC,68.9,51.8,54.450,80.0,11.55,0.0,6.210,"[shot, volley]","[shot, header]"
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,EGLC,68.9,51.8,54.450,80.0,11.55,0.0,6.210,"[header, shot, shot, shot, shot]",[]
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,EGNX,39.2,32.9,77.975,220.0,8.10,0.0,6.210,[],[shot]
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,EGBB,36.5,33.8,89.885,145.0,13.25,0.0,3.730,[],"[bicycle_kick, shot, header]"
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,EGLC,59.0,43.7,56.815,230.0,12.10,0.0,6.210,"[tap_in, header]",[shot]
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,EGNT,58.1,47.3,67.375,270.0,25.90,0.0,6.210,[],"[shot, shot]"
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,EGNM,39.2,32.0,75.160,55.0,9.20,0.0,6.210,[volley],[]
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,EGLC,41.0,34.7,78.130,325.0,13.25,0.0,4.660,[shot],[shot]
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,EGHI,49.1,44.6,84.445,340.0,5.75,0.0,6.210,[],"[distance, shot, shot]"
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,EGOP,53.6,42.8,66.700,240.0,21.90,0.0,6.210,"[distance, shot]","[deflected, shot, shot, shot]"
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,EGXV,64.4,53.6,67.950,230.0,11.50,0.0,6.210,[shot],"[shot, shot, shot]"
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,EGLC,69.8,54.5,58.295,65.0,4.05,0.0,6.210,[shot],[shot]
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,EGLC,69.8,54.5,58.295,65.0,4.05,0.0,6.210,"[shot, header, tap_in]",[]
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,EGNX,39.2,35.6,86.790,175.0,14.95,0.0,5.900,[backheel],"[shot, direct_freekick]"
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,EGCC,46.4,35.6,65.830,75.0,16.15,0.0,6.210,"[shot, header, shot]",[]
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,EGBB,40.1,29.3,65.210,325.0,21.30,0.0,6.210,[],"[direct_freekick, shot]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,EGGP,39.2,33.8,80.790,145.0,7.50,0.0,6.210,[],[]
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,EGNT,48.2,42.8,81.470,0.0,1.15,0.0,6.210,"[tap_in, shot, tap_in, distance]",[]
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,EGBB,60.8,46.4,59.145,285.0,13.25,0.0,6.210,[],[shot]
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,EGCC,51.8,48.2,87.470,270.0,10.35,0.0,6.210,"[shot, distance, shot]",[]
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,EGLC,62.6,46.4,55.370,145.0,14.40,0.0,6.210,"[shot, shot, tap_in]",[tap_in]
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,EGNT,56.3,51.8,84.885,355.0,6.90,0.0,6.210,"[shot, direct_freekick]",[deflected]
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,EGCC,35.6,25.7,66.960,80.0,11.55,0.0,5.900,[],[]
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,EGLC,58.1,42.8,56.690,95.0,11.55,0.0,6.210,[header],[tap_in]
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,EGNT,33.8,30.2,86.490,75.0,4.05,0.0,4.970,[shot],[]
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,EGOS,50.0,46.4,87.370,120.0,5.80,0.0,4.970,"[shot, header]","[header, shot, shot]"
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,EGBB,47.3,35.6,63.675,15.0,14.40,0.0,6.210,[distance],[]
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,EGCC,59.9,31.1,33.495,220.0,23.60,0.0,6.210,"[shot, header, shot]","[shot, header]"
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,EGOP,50.0,44.6,81.610,200.0,19.60,0.0,6.210,[shot],[shot]
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,EGSH,53.6,46.4,76.500,230.0,21.30,0.0,6.210,"[shot, tap_in]",[shot]
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,EGLC,60.8,57.2,87.920,200.0,9.80,0.0,6.210,"[shot, shot, shot]",[header]
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,EGBB,53.6,36.5,52.215,225.0,15.00,0.0,6.210,[shot],[]
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,EGCC,53.6,39.2,58.020,180.0,4.60,0.0,6.210,[shot],[deflected]
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,EGLC,55.4,36.5,48.900,250.0,11.55,0.0,6.210,[],[]
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,EGOP,37.4,28.4,69.670,80.0,6.90,0.0,4.970,[volley],[]
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,EGSH,47.3,38.3,70.945,275.0,26.50,0.0,5.900,[],[]
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,EGCC,59.0,48.2,67.330,300.0,11.50,0.0,6.210,"[header, distance, shot, missed]",[shot]
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,EGLC,53.6,46.4,76.500,245.0,10.35,0.0,6.210,[shot],[volley]
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,EGWU,60.8,35.6,38.850,80.0,10.40,0.0,6.210,"[header, header, shot]","[bicycle_kick, shot]"
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,EGNO,49.1,47.3,93.475,270.0,21.30,0.0,6.210,[],[saved]
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,EGBB,55.4,49.1,79.325,190.0,13.25,0.0,6.210,[],[shot]
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,EGBB,35.6,32.0,86.590,315.0,10.95,0.0,6.210,[],"[tap_in, header]"
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,EGLC,46.4,45.5,96.700,100.0,2.90,0.0,0.075,[tap_in],"[shot, shot]"
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,EGOP,53.6,46.4,76.500,230.0,25.30,0.0,6.210,[shot],[]
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,EGSH,44.6,42.8,93.350,50.0,21.30,0.0,5.590,[],"[shot, shot, distance]"
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,EGLC,62.6,47.3,57.315,285.0,8.05,0.0,6.210,"[distance, shot, loose_ball, volley]",[shot]

In [94]:
def split_shoton_stats(df):
    shoton_list = df['shoton'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],shoton_list):
        home_shots = []
        away_shots = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_shots.append(i[0])
                else:
                    away_shots.append(i[0])
        except:
            home_shots.append('')
            away_shots.append('')
        home_full.append(home_shots)
        away_full.append(away_shots)
    df['home_shoton_types'] = home_full
    df['away_shoton_types'] = away_full
    return df

In [95]:
split_shoton_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,dew (F),humidity,wind direction,wind speed (mph),prec (in),visibility (mi),home_goal_types,away_goal_types,home_shoton_types,away_shoton_types
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,47.3,47.490,270.0,16.15,0.0,6.210,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]"
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,47.3,47.490,270.0,16.15,0.0,6.210,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis..."
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,28.4,69.670,20.0,4.60,0.0,6.210,[],[],"[blocked_shot, blocked_shot, volley, blocked_s...","[shot, blocked_shot, shot, shot]"
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,35.6,57.520,10.0,10.40,0.0,6.210,[shot],[shot],"[blocked_shot, shot, big chance shot, lob, blo...","[blocked_shot, blocked_shot, shot]"
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,49.1,79.325,210.0,8.65,0.0,6.210,[],"[shot, header]","[distance, blocked_shot, shot, blocked_shot, b...","[header, blocked_shot, header, blocked_shot, s..."
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,45.5,84.490,215.0,16.10,0.0,6.210,[deflected],"[deflected, header, header]","[blocked_shot, big chance shot, distance, head...","[blocked_header, shot, shot, blocked_shot]"
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,39.2,54.340,280.0,20.75,0.0,6.210,[shot],"[direct_freekick, tap_in, saved_back_into_play...","[blocked_shot, blocked_header, blocked_shot, s...","[deflected, volley, blocked_shot, blocked_shot..."
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,50.0,55.880,280.0,18.40,0.0,6.210,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]"
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,33.8,100.000,225.0,5.80,0.0,6.210,"[header, shot]","[shot, distance, shot]","[shot, blocked_shot]","[distance, blocked_header, blocked_shot]"
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,50.0,87.560,195.0,17.85,0.0,6.210,[],[],"[shot, deflected, big chance shot, blocked_sho...","[blocked_shot, blocked_shot]"
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,49.1,57.565,5.0,5.20,0.0,6.210,[shot],"[header, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[blocked_shot, blocked_shot, blocked_shot, blo..."
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,31.1,58.885,275.0,10.95,0.0,6.210,[shot],[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_header, header, blocked_shot, shot, s..."
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,48.2,87.470,150.0,6.90,0.0,6.210,[shot],[],"[blocked_shot, shot, volley, volley, blocked_s...","[big chance shot, shot, shot, blocked_shot, shot]"
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,41.0,81.340,290.0,12.70,0.0,6.210,"[deflected, shot, shot]",[header],"[shot, blocked_shot, blocked_shot]",[blocked_shot]
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,51.8,54.450,80.0,11.55,0.0,6.210,"[shot, volley]","[shot, header]","[shot, shot, shot, shot]","[blocked_shot, big chance shot, shot, shot, sh..."
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,51.8,54.450,80.0,11.55,0.0,6.210,"[header, shot, shot, shot, shot]",[],"[shot, blocked_shot, header, direct_freekick, ...","[blocked_shot, blocked_shot, shot]"
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,32.9,77.975,220.0,8.10,0.0,6.210,[],[shot],[header],"[blocked_shot, distance, shot, blocked_shot, s..."
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,33.8,89.885,145.0,13.25,0.0,3.730,[],"[bicycle_kick, shot, header]","[volley, big chance shot, blocked_shot, blocke...","[big chance shot, shot]"
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,43.7,56.815,230.0,12.10,0.0,6.210,"[tap_in, header]",[shot],"[big chance shot, deflected, blocked_shot, shot]","[deflected, blocked_shot, blocked_shot, big ch..."
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,47.3,67.375,270.0,25.90,0.0,6.210,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b..."
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,32.0,75.160,55.0,9.20,0.0,6.210,[volley],[],"[shot, shot]","[blocked_shot, big chance shot, shot, blocked_..."
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,34.7,78.130,325.0,13.25,0.0,4.660,[shot],[shot],[shot],"[shot, shot, header, distance]"
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,44.6,84.445,340.0,5.75,0.0,6.210,[],"[distance, shot, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[distance, deflected, blocked_shot, big chance..."
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,42.8,66.700,240.0,21.90,0.0,6.210,"[distance, shot]","[deflected, shot, shot, shot]","[distance, shot, distance, distance, big chanc...","[blocked_shot, blocked_shot, blocked_shot, hea..."
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,53.6,67.950,230.0,11.50,0.0,6.210,[shot],"[shot, shot, shot]","[header, distance, distance, shot]","[shot, blocked_shot, blocked_shot, blocked_hea..."
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,54.5,58.295,65.0,4.05,0.0,6.210,[shot],[shot],"[shot, blocked_shot, blocked_shot, shot, defle...","[header, shot, blocked_shot, header, shot, dir..."
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,54.5,58.295,65.0,4.05,0.0,6.210,"[shot, header, tap_in]",[],"[shot, header, blocked_shot, header, header, b...","[blocked_shot, distance]"
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,35.6,86.790,175.0,14.95,0.0,5.900,[backheel],"[shot, direct_freekick]","[blocked_shot, shot, shot, big chance shot, bl...","[shot, blocked_shot, shot, shot]"
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,35.6,65.830,75.0,16.15,0.0,6.210,"[shot, header, shot]",[],"[blocked_header, blocked_shot]","[blocked_shot, shot]"
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,29.3,65.210,325.0,21.30,0.0,6.210,[],"[direct_freekick, shot]","[blocked_shot, distance, shot, big chance shot...","[blocked_shot, shot, blocked_shot, distance, b..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,33.8,80.790,145.0,7.50,0.0,6.210,[],[],"[blocked_shot, distance, blocked_shot, blocked...",[distance]
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,42.8,81.470,0.0,1.15,0.0,6.210,"[tap_in, shot, tap_in, distance]",[],"[shot, shot, distance, shot, blocked_shot, dis...","[big chance blocked, blocked_shot]"
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,46.4,59.145,285.0,13.25,0.0,6.210,[],[shot],"[header, big chance header, blocked_shot, bloc...",[]
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,48.2,87.470,270.0,10.35,0.0,6.210,"[shot, distance, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, blo...",[header]
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,46.4,55.370,145.0,14.40,0.0,6.210,"[shot, shot, tap_in]",[tap_in],[shot],"[blocked_shot, blocked_shot]"
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,51.8,84.885,355.0,6.90,0.0,6.210,"[shot, direct_freekick]",[deflected],"[shot, shot, blocked_shot, shot]","[blocked_shot, blocked_shot, direct_freekick, ..."
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,25.7,66.960,80.0,11.55,0.0,5.900,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[header, blocked_shot, header, blocked_shot]"
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,42.8,56.690,95.0,11.55,0.0,6.210,[header],[tap_in],"[blocked_shot, blocked_shot, distance, blocked...","[blocked_shot, header]"
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,30.2,86.490,75.0,4.05,0.0,4.970,[shot],[],"[distance, shot]","[distance, distance, shot, blocked_shot, dista..."
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,46.4,87.370,120.0,5.80,0.0,4.970,"[shot, header]","[header, shot, shot]","[blocked_shot, big chance shot, big chance sho...","[distance, blocked_shot, blocked_shot]"
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,35.6,63.675,15.0,14.40,0.0,6.210,[distance],[],"[blocked_shot, deflected, blocked_shot, shot, ...","[big chance shot, blocked_shot, big chance sho..."
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,31.1,33.495,220.0,23.60,0.0,6.210,"[shot, header, shot]","[shot, header]","[shot, blocked_shot, blocked_shot, blocked_sho...",[indirect freekick]
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,44.6,81.610,200.0,19.60,0.0,6.210,[shot],[shot],"[distance, blocked_shot, blocked_shot]","[header, distance, blocked_shot, blocked_shot,..."
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,46.4,76.500,230.0,21.30,0.0,6.210,"[shot, tap_in]",[shot],"[distance, shot, deflected, deflected, blocked...","[blocked_shot, blocked_shot, big chance shot, ..."
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,57.2,87.920,200.0,9.80,0.0,6.210,"[shot, shot, shot]",[header],"[big chance shot, distance, big chance shot, h...","[blocked_shot, blocked_shot, distance, blocked..."
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,36.5,52.215,225.0,15.00,0.0,6.210,[shot],[],"[distance, blocked_shot, blocked_shot, shot, s...","[shot, blocked_shot, blocked_shot, distance]"
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,39.2,58.020,180.0,4.60,0.0,6.210,[shot],[deflected],"[blocked_shot, distance, distance, blocked_shot]",[shot]
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,36.5,48.900,250.0,11.55,0.0,6.210,[],[],"[distance, shot, blocked_shot, blocked_shot, h...","[blocked_shot, deflected, shot]"
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,28.4,69.670,80.0,6.90,0.0,4.970,[volley],[],"[big chance shot, big chance shot, distance]","[shot, blocked_shot, distance, blocked_shot, h..."
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,38.3,70.945,275.0,26.50,0.0,5.900,[],[],"[shot, blocked_shot, header, deflected]","[shot, shot, distance, big chance shot, shot, ..."
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,48.2,67.330,300.0,11.50,0.0,6.210,"[header, distance, shot, missed]",[shot],"[header, blocked_shot, header, big chance shot]","[volley, header, big chance shot, shot, shot, ..."
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,46.4,76.500,245.0,10.35,0.0,6.210,[shot],[volley],"[blocked_shot, blocked_shot, blocked_shot, sho...","[distance, distance, blocked_shot, big chance ..."
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,35.6,38.850,80.0,10.40,0.0,6.210,"[header, header, shot]","[bicycle_kick, shot]","[blocked_shot, shot]","[big chance shot, shot, header, blocked_shot, ..."
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,47.3,93.475,270.0,21.30,0.0,6.210,[],[saved],"[blocked_shot, blocked_shot, blocked_shot, dis...","[blocked_shot, big chance shot, shot, big chan..."
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,49.1,79.325,190.0,13.25,0.0,6.210,[],[shot],"[blocked_shot, distance, blocked_shot, blocked...","[blocked_shot, header, blocked_shot, blocked_s..."
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,32.0,86.590,315.0,10.95,0.0,6.210,[],"[tap_in, header]","[direct_freekick, blocked_shot, blocked_shot, ...","[shot, shot, big chance shot, blocked_shot, sh..."
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,45.5,96.700,100.0,2.90,0.0,0.075,[tap_in],"[shot, shot]","[big chance volley, blocked_shot, big chance h...",[blocked_shot]
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,46.4,76.500,230.0,25.30,0.0,6.210,[shot],[],"[indirect freekick, blocked_shot, blocked_shot...","[blocked_shot, header, shot, bicycle_kick, hea..."
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,42.8,93.350,50.0,21.30,0.0,5.590,[],"[shot, shot, distance]","[distance, blocked_shot]","[blocked_shot, volley, blocked_shot, header, s..."
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,47.3,57.315,285.0,8.05,0.0,6.210,"[distance, shot, loose_ball, volley]",[shot],"[blocked_shot, shot, blocked_shot, blocked_sho...",[distance]

In [96]:
def split_shotoff_stats(df):
    shotoff_list = df['shotoff'].map(clean_html_goals_shots)
    home_full = []
    away_full = []
    for home,lst in zip(df['home_team_api_id'],shotoff_list):
        home_shots = []
        away_shots = []
        try:
            for i in lst:
                if float(i[1])==home:
                    home_shots.append(i[0])
                else:
                    away_shots.append(i[0])
        except:
            home_shots.append('')
            away_shots.append('')
        home_full.append(home_shots)
        away_full.append(away_shots)
    df['home_shotoff_types'] = home_full
    df['away_shotoff_types'] = away_full
    return df

In [97]:
split_shotoff_stats(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,wind direction,wind speed (mph),prec (in),visibility (mi),home_goal_types,away_goal_types,home_shoton_types,away_shoton_types,home_shotoff_types,away_shotoff_types
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,270.0,16.15,0.0,6.210,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]","[lob, header, deflected, direct_freekick, shot]",[]
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,270.0,16.15,0.0,6.210,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis...","[shot, header, header, distance, distance, dis...","[shot, direct_freekick]"
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,20.0,4.60,0.0,6.210,[],[],"[blocked_shot, blocked_shot, volley, blocked_s...","[shot, blocked_shot, shot, shot]","[shot, volley]","[post, distance, shot, shot, shot, header]"
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,10.0,10.40,0.0,6.210,[shot],[shot],"[blocked_shot, shot, big chance shot, lob, blo...","[blocked_shot, blocked_shot, shot]","[distance, volley, header, header, deflected, ...","[indirect freekick, shot, header, distance, ba..."
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,210.0,8.65,0.0,6.210,[],"[shot, header]","[distance, blocked_shot, shot, blocked_shot, b...","[header, blocked_shot, header, blocked_shot, s...","[shot, distance, shot, shot, distance, crossba...","[shot, shot]"
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,215.0,16.10,0.0,6.210,[deflected],"[deflected, header, header]","[blocked_shot, big chance shot, distance, head...","[blocked_header, shot, shot, blocked_shot]","[distance, crossbar, deflected, header, direct...","[header, shot, deflected, direct_freekick]"
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,280.0,20.75,0.0,6.210,[shot],"[direct_freekick, tap_in, saved_back_into_play...","[blocked_shot, blocked_header, blocked_shot, s...","[deflected, volley, blocked_shot, blocked_shot...","[distance, shot, shot, shot, distance, shot, d...","[deflected, big chance shot, shot, volley, dis..."
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,280.0,18.40,0.0,6.210,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]","[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]"
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,225.0,5.80,0.0,6.210,"[header, shot]","[shot, distance, shot]","[shot, blocked_shot]","[distance, blocked_header, blocked_shot]",[],"[bicycle_kick, distance, deflected, distance, ..."
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,195.0,17.85,0.0,6.210,[],[],"[shot, deflected, big chance shot, blocked_sho...","[blocked_shot, blocked_shot]","[bad shot, shot, direct_freekick, distance, de...","[crossbar, shot, shot, shot]"
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,5.0,5.20,0.0,6.210,[shot],"[header, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, miss_kick, shot, shot, deflected, shot,...","[post, distance, shot]"
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,275.0,10.95,0.0,6.210,[shot],[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_header, header, blocked_shot, shot, s...","[bad shot, shot, shot, distance, big chance sh...","[post, shot]"
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,150.0,6.90,0.0,6.210,[shot],[],"[blocked_shot, shot, volley, volley, blocked_s...","[big chance shot, shot, shot, blocked_shot, shot]","[header, direct_freekick, shot, shot, shot, sh...","[deflected, shot, deflected, shot]"
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,290.0,12.70,0.0,6.210,"[deflected, shot, shot]",[header],"[shot, blocked_shot, blocked_shot]",[blocked_shot],"[shot, distance, shot, shot, distance, miss_ki...","[bicycle_kick, header, shot, bad shot, bicycle..."
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,80.0,11.55,0.0,6.210,"[shot, volley]","[shot, header]","[shot, shot, shot, shot]","[blocked_shot, big chance shot, shot, shot, sh...","[distance, shot, post, direct_freekick, shot, ...","[big chance shot, shot, shot, post, post]"
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,80.0,11.55,0.0,6.210,"[header, shot, shot, shot, shot]",[],"[shot, blocked_shot, header, direct_freekick, ...","[blocked_shot, blocked_shot, shot]","[distance, header, header, deflected, deflecte...","[big chance volley, distance, volley, big chan..."
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,220.0,8.10,0.0,6.210,[],[shot],[header],"[blocked_shot, distance, shot, blocked_shot, s...","[distance, deflected, direct_freekick, deflect...","[shot, shot, volley]"
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,145.0,13.25,0.0,3.730,[],"[bicycle_kick, shot, header]","[volley, big chance shot, blocked_shot, blocke...","[big chance shot, shot]","[big chance shot, big chance shot, volley, big...","[shot, big chance shot, deflected, deflected, ..."
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,230.0,12.10,0.0,6.210,"[tap_in, header]",[shot],"[big chance shot, deflected, blocked_shot, shot]","[deflected, blocked_shot, blocked_shot, big ch...","[shot, header, shot, volley, shot, shot]","[direct_freekick, header, volley, shot, distan..."
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,270.0,25.90,0.0,6.210,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b...","[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]"
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,55.0,9.20,0.0,6.210,[volley],[],"[shot, shot]","[blocked_shot, big chance shot, shot, blocked_...","[volley, header, deflected, header, volley, vo...","[volley, shot, volley, volley, header, deflect..."
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,325.0,13.25,0.0,4.660,[shot],[shot],[shot],"[shot, shot, header, distance]",[header],"[deflected, big chance shot, header, header, s..."
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,340.0,5.75,0.0,6.210,[],"[distance, shot, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[distance, deflected, blocked_shot, big chance...","[header, distance, distance, distance, lob]","[bad shot, header, header, distance, shot, dis..."
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,240.0,21.90,0.0,6.210,"[distance, shot]","[deflected, shot, shot, shot]","[distance, shot, distance, distance, big chanc...","[blocked_shot, blocked_shot, blocked_shot, hea...","[shot, header, miss_kick]","[direct_freekick, header, deflected, header, d..."
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,230.0,11.50,0.0,6.210,[shot],"[shot, shot, shot]","[header, distance, distance, shot]","[shot, blocked_shot, blocked_shot, blocked_hea...","[shot, distance, header, deflected]","[shot, distance, header, post, deflected, dist..."
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,65.0,4.05,0.0,6.210,[shot],[shot],"[shot, blocked_shot, blocked_shot, shot, defle...","[header, shot, blocked_shot, header, shot, dir...","[shot, volley]",[shot]
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,65.0,4.05,0.0,6.210,"[shot, header, tap_in]",[],"[shot, header, blocked_shot, header, header, b...","[blocked_shot, distance]","[shot, header, shot, shot, distance, header, d...","[shot, distance, distance, header]"
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,175.0,14.95,0.0,5.900,[backheel],"[shot, direct_freekick]","[blocked_shot, shot, shot, big chance shot, bl...","[shot, blocked_shot, shot, shot]","[distance, bad shot, big chance post, distance...","[header, distance]"
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,75.0,16.15,0.0,6.210,"[shot, header, shot]",[],"[blocked_header, blocked_shot]","[blocked_shot, shot]","[shot, distance, distance, shot, distance]","[distance, distance]"
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,325.0,21.30,0.0,6.210,[],"[direct_freekick, shot]","[blocked_shot, distance, shot, big chance shot...","[blocked_shot, shot, blocked_shot, distance, b...","[header, crossbar, distance, deflected, header...","[bad shot, distance, shot, header, shot, bad s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,145.0,7.50,0.0,6.210,[],[],"[blocked_shot, distance, blocked_shot, blocked...",[distance],"[distance, distance, distance, distance, big c...","[bad shot, bad shot]"
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,0.0,1.15,0.0,6.210,"[tap_in, shot, tap_in, distance]",[],"[shot, shot, distance, shot, blocked_shot, dis...","[big chance blocked, blocked_shot]","[bad shot, big chance crossbar, distance, shot...","[distance, volley, distance, header, shot, shot]"
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,285.0,13.25,0.0,6.210,[],[shot],"[header, big chance header, blocked_shot, bloc...",[],"[header, shot, distance, direct_freekick, shot...","[distance, volley, header, shot]"
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,270.0,10.35,0.0,6.210,"[shot, distance, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, blo...",[header],"[crossbar, big chance shot, big chance shot, d...",[header]
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,145.0,14.40,0.0,6.210,"[shot, shot, tap_in]",[tap_in],[shot],"[blocked_shot, blocked_shot]","[header, distance, shot, bad shot]","[distance, bad shot, distance, volley]"
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,355.0,6.90,0.0,6.210,"[shot, direct_freekick]",[deflected],"[shot, shot, blocked_shot, shot]","[blocked_shot, blocked_shot, direct_freekick, ...",[volley],"[distance, header]"
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,80.0,11.55,0.0,5.900,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[header, blocked_shot, header, blocked_shot]","[deflected, volley, big chance shot, big chanc...","[distance, distance, distance, shot, distance]"
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,95.0,11.55,0.0,6.210,[header],[tap_in],"[blocked_shot, blocked_shot, distance, blocked...","[blocked_shot, header]","[shot, deflected, direct_freekick, bad shot, d...","[distance, shot, header, distance, bad shot, d..."
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,75.0,4.05,0.0,4.970,[shot],[],"[distance, shot]","[distance, distance, shot, blocked_shot, dista...","[header, distance, deflected, header]","[deflected, crossbar, post, volley, shot, defl..."
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,120.0,5.80,0.0,4.970,"[shot, header]","[header, shot, shot]","[blocked_shot, big chance shot, big chance sho...","[distance, blocked_shot, blocked_shot]","[header, shot, distance, direct_freekick, dist...",[post]
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,15.0,14.40,0.0,6.210,[distance],[],"[blocked_shot, deflected, blocked_shot, shot, ...","[big chance shot, blocked_shot, big chance sho...","[big chance shot, shot, shot, shot, crossbar, ...","[shot, shot, big chance header, header, shot, ..."
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,220.0,23.60,0.0,6.210,"[shot, header, shot]","[shot, header]","[shot, blocked_shot, blocked_shot, blocked_sho...",[indirect freekick],"[distance, distance, distance, direct_freekick...",[]
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,200.0,19.60,0.0,6.210,[shot],[shot],"[distance, blocked_shot, blocked_shot]","[header, distance, blocked_shot, blocked_shot,...","[header, distance, big chance shot, volley]","[header, header, deflected, distance, distance..."
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,230.0,21.30,0.0,6.210,"[shot, tap_in]",[shot],"[distance, shot, deflected, deflected, blocked...","[blocked_shot, blocked_shot, big chance shot, ...","[header, shot, shot, big chance shot, distance...","[shot, shot, header, header, shot, shot, heade..."
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,200.0,9.80,0.0,6.210,"[shot, shot, shot]",[header],"[big chance shot, distance, big chance shot, h...","[blocked_shot, blocked_shot, distance, blocked...","[direct_freekick, header, big chance volley, d...","[volley, bad shot, bad shot, deflected, deflec..."
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,225.0,15.00,0.0,6.210,[shot],[],"[distance, blocked_shot, blocked_shot, shot, s...","[shot, blocked_shot, blocked_shot, distance]","[header, big chance shot, shot, distance, dist...","[deflected, big chance shot, deflected, shot, ..."
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,180.0,4.60,0.0,6.210,[shot],[deflected],"[blocked_shot, distance, distance, blocked_shot]",[shot],"[shot, crossbar, distance, big chance shot, bi...","[shot, deflected, deflected, deflected, shot]"
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,250.0,11.55,0.0,6.210,[],[],"[distance, shot, blocked_shot, blocked_shot, h...","[blocked_shot, deflected, shot]","[post, crossbar, deflected, direct_freekick, v...","[header, header, shot, deflected, header, head..."
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,80.0,6.90,0.0,4.970,[volley],[],"[big chance shot, big chance shot, distance]","[shot, blocked_shot, distance, blocked_shot, h...","[big chance shot, shot]","[shot, distance, deflected, volley, shot, dist..."
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,275.0,26.50,0.0,5.900,[],[],"[shot, blocked_shot, header, deflected]","[shot, shot, distance, big chance shot, shot, ...","[distance, shot]","[volley, bad shot, shot, distance, distance, b..."
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,300.0,11.50,0.0,6.210,"[header, distance, shot, missed]",[shot],"[header, blocked_shot, header, big chance shot]","[volley, header, big chance shot, shot, shot, ...","[distance, crossbar, deflected, header, big ch...","[bad shot, shot, deflected, bad shot, shot, bi..."
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,245.0,10.35,0.0,6.210,[shot],[volley],"[blocked_shot, blocked_shot, blocked_shot, sho...","[distance, distance, blocked_shot, big chance ...","[direct_freekick, header, deflected, big chanc...","[bad shot, big chance post, shot, direct_freek..."
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,80.0,10.40,0.0,6.210,"[header, header, shot]","[bicycle_kick, shot]","[blocked_shot, shot]","[big chance shot, shot, header, blocked_shot, ...","[shot, distance, distance, distance, direct_fr...","[header, shot, crossbar, distance, direct_free..."
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,270.0,21.30,0.0,6.210,[],[saved],"[blocked_shot, blocked_shot, blocked_shot, dis...","[blocked_shot, big chance shot, shot, big chan...","[distance, distance, shot, big chance shot, di...","[volley, volley, header, header, big chance sh..."
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,190.0,13.25,0.0,6.210,[],[shot],"[blocked_shot, distance, blocked_shot, blocked...","[blocked_shot, header, blocked_shot, blocked_s...","[distance, header, shot, direct_freekick, header]","[distance, header, direct_freekick, big chance..."
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,315.0,10.95,0.0,6.210,[],"[tap_in, header]","[direct_freekick, blocked_shot, blocked_shot, ...","[shot, shot, big chance shot, blocked_shot, sh...","[distance, shot, big chance header, distance, ...","[header, big chance crossbar, shot, big chance..."
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,100.0,2.90,0.0,0.075,[tap_in],"[shot, shot]","[big chance volley, blocked_shot, big chance h...",[blocked_shot],"[distance, direct_freekick, header, header, sh...","[direct_freekick, deflected, direct_freekick, ..."
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,230.0,25.30,0.0,6.210,[shot],[],"[indirect freekick, blocked_shot, blocked_shot...","[blocked_shot, header, shot, bicycle_kick, hea...","[shot, distance, shot, deflected, header]","[distance, shot, shot, shot, header]"
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,50.0,21.30,0.0,5.590,[],"[shot, shot, distance]","[distance, blocked_shot]","[blocked_shot, volley, blocked_shot, header, s...","[header, deflected, distance, distance, header...","[deflected, direct_freekick, crossbar, volley,..."
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,285.0,8.05,0.0,6.210,"[distance, shot, loose_ball, volley]",[shot],"[blocked_shot, shot, blocked_shot, blocked_sho...",[distance],"[big chance shot, distance, direct_freekick, d...","[shot, bicycle_kick, direct_freekick, header, ..."

In [98]:
final_merge.drop(['shoton','shotoff'],axis=1,inplace=True)

In [34]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v5.csv',index=False)

In [99]:
def home_goals(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    for types in df['home_goal_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
    df['home_goal_headers'] = header_list
    df['home_goal_freekicks'] = freekick_list
    df['home_goal_volleys'] = volley_list
    df['home_goal_other'] = other_list
    return df

In [100]:
home_goals(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_goal_types,away_goal_types,home_shoton_types,away_shoton_types,home_shotoff_types,away_shotoff_types,home_goal_headers,home_goal_freekicks,home_goal_volleys,home_goal_other
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,"[header, tap_in]",[header],"[blocked_shot, distance, shot, blocked_shot, d...","[blocked_shot, blocked_shot, shot]","[lob, header, deflected, direct_freekick, shot]",[],1,0,0,1
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,[missed],[shot],"[blocked_shot, big chance blocked, header, dis...","[big chance shot, deflected, blocked_shot, dis...","[shot, header, header, distance, distance, dis...","[shot, direct_freekick]",0,0,0,1
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,[],[],"[blocked_shot, blocked_shot, volley, blocked_s...","[shot, blocked_shot, shot, shot]","[shot, volley]","[post, distance, shot, shot, shot, header]",0,0,0,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,[shot],[shot],"[blocked_shot, shot, big chance shot, lob, blo...","[blocked_shot, blocked_shot, shot]","[distance, volley, header, header, deflected, ...","[indirect freekick, shot, header, distance, ba...",0,0,0,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,[],"[shot, header]","[distance, blocked_shot, shot, blocked_shot, b...","[header, blocked_shot, header, blocked_shot, s...","[shot, distance, shot, shot, distance, crossba...","[shot, shot]",0,0,0,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,[deflected],"[deflected, header, header]","[blocked_shot, big chance shot, distance, head...","[blocked_header, shot, shot, blocked_shot]","[distance, crossbar, deflected, header, direct...","[header, shot, deflected, direct_freekick]",0,0,0,1
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,[shot],"[direct_freekick, tap_in, saved_back_into_play...","[blocked_shot, blocked_header, blocked_shot, s...","[deflected, volley, blocked_shot, blocked_shot...","[distance, shot, shot, shot, distance, shot, d...","[deflected, big chance shot, shot, volley, dis...",0,0,0,1
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,"[deflected, header, loose_ball]","[loose_ball, volley, shot]","[blocked_shot, blocked_shot, big chance shot, ...","[volley, distance, shot, shot, blocked_shot]","[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]",1,0,0,2
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,"[header, shot]","[shot, distance, shot]","[shot, blocked_shot]","[distance, blocked_header, blocked_shot]",[],"[bicycle_kick, distance, deflected, distance, ...",1,0,0,1
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,[],[],"[shot, deflected, big chance shot, blocked_sho...","[blocked_shot, blocked_shot]","[bad shot, shot, direct_freekick, distance, de...","[crossbar, shot, shot, shot]",0,0,0,0
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,[shot],"[header, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, miss_kick, shot, shot, deflected, shot,...","[post, distance, shot]",0,0,0,1
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,[shot],[],"[blocked_shot, blocked_shot, shot, blocked_sho...","[blocked_header, header, blocked_shot, shot, s...","[bad shot, shot, shot, distance, big chance sh...","[post, shot]",0,0,0,1
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,[shot],[],"[blocked_shot, shot, volley, volley, blocked_s...","[big chance shot, shot, shot, blocked_shot, shot]","[header, direct_freekick, shot, shot, shot, sh...","[deflected, shot, deflected, shot]",0,0,0,1
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,"[deflected, shot, shot]",[header],"[shot, blocked_shot, blocked_shot]",[blocked_shot],"[shot, distance, shot, shot, distance, miss_ki...","[bicycle_kick, header, shot, bad shot, bicycle...",0,0,0,3
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,"[shot, volley]","[shot, header]","[shot, shot, shot, shot]","[blocked_shot, big chance shot, shot, shot, sh...","[distance, shot, post, direct_freekick, shot, ...","[big chance shot, shot, shot, post, post]",0,0,1,1
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,"[header, shot, shot, shot, shot]",[],"[shot, blocked_shot, header, direct_freekick, ...","[blocked_shot, blocked_shot, shot]","[distance, header, header, deflected, deflecte...","[big chance volley, distance, volley, big chan...",1,0,0,4
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,[],[shot],[header],"[blocked_shot, distance, shot, blocked_shot, s...","[distance, deflected, direct_freekick, deflect...","[shot, shot, volley]",0,0,0,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,[],"[bicycle_kick, shot, header]","[volley, big chance shot, blocked_shot, blocke...","[big chance shot, shot]","[big chance shot, big chance shot, volley, big...","[shot, big chance shot, deflected, deflected, ...",0,0,0,0
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,"[tap_in, header]",[shot],"[big chance shot, deflected, blocked_shot, shot]","[deflected, blocked_shot, blocked_shot, big ch...","[shot, header, shot, volley, shot, shot]","[direct_freekick, header, volley, shot, distan...",1,0,0,1
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,[],"[shot, shot]","[blocked_shot, blocked_shot, blocked_shot, blo...","[shot, blocked_shot, distance, blocked_shot, b...","[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]",0,0,0,0
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,[volley],[],"[shot, shot]","[blocked_shot, big chance shot, shot, blocked_...","[volley, header, deflected, header, volley, vo...","[volley, shot, volley, volley, header, deflect...",0,0,1,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,[shot],[shot],[shot],"[shot, shot, header, distance]",[header],"[deflected, big chance shot, header, header, s...",0,0,0,1
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,[],"[distance, shot, shot]","[shot, blocked_shot, blocked_shot, blocked_sho...","[distance, deflected, blocked_shot, big chance...","[header, distance, distance, distance, lob]","[bad shot, header, header, distance, shot, dis...",0,0,0,0
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,"[distance, shot]","[deflected, shot, shot, shot]","[distance, shot, distance, distance, big chanc...","[blocked_shot, blocked_shot, blocked_shot, hea...","[shot, header, miss_kick]","[direct_freekick, header, deflected, header, d...",0,0,0,2
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,[shot],"[shot, shot, shot]","[header, distance, distance, shot]","[shot, blocked_shot, blocked_shot, blocked_hea...","[shot, distance, header, deflected]","[shot, distance, header, post, deflected, dist...",0,0,0,1
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,[shot],[shot],"[shot, blocked_shot, blocked_shot, shot, defle...","[header, shot, blocked_shot, header, shot, dir...","[shot, volley]",[shot],0,0,0,1
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,"[shot, header, tap_in]",[],"[shot, header, blocked_shot, header, header, b...","[blocked_shot, distance]","[shot, header, shot, shot, distance, header, d...","[shot, distance, distance, header]",1,0,0,2
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,[backheel],"[shot, direct_freekick]","[blocked_shot, shot, shot, big chance shot, bl...","[shot, blocked_shot, shot, shot]","[distance, bad shot, big chance post, distance...","[header, distance]",0,0,0,1
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,"[shot, header, shot]",[],"[blocked_header, blocked_shot]","[blocked_shot, shot]","[shot, distance, distance, shot, distance]","[distance, distance]",1,0,0,2
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,[],"[direct_freekick, shot]","[blocked_shot, distance, shot, big chance shot...","[blocked_shot, shot, blocked_shot, distance, b...","[header, crossbar, distance, deflected, header...","[bad shot, distance, shot, header, shot, bad s...",0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,[],[],"[blocked_shot, distance, blocked_shot, blocked...",[distance],"[distance, distance, distance, distance, big c...","[bad shot, bad shot]",0,0,0,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,"[tap_in, shot, tap_in, distance]",[],"[shot, shot, distance, shot, blocked_shot, dis...","[big chance blocked, blocked_shot]","[bad shot, big chance crossbar, distance, shot...","[distance, volley, distance, header, shot, shot]",0,0,0,4
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,[],[shot],"[header, big chance header, blocked_shot, bloc...",[],"[header, shot, distance, direct_freekick, shot...","[distance, volley, header, shot]",0,0,0,0
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,"[shot, distance, shot]",[],"[blocked_shot, blocked_shot, blocked_shot, blo...",[header],"[crossbar, big chance shot, big chance shot, d...",[header],0,0,0,3
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,"[shot, shot, tap_in]",[tap_in],[shot],"[blocked_shot, blocked_shot]","[header, distance, shot, bad shot]","[distance, bad shot, distance, volley]",0,0,0,3
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,"[shot, direct_freekick]",[deflected],"[shot, shot, blocked_shot, shot]","[blocked_shot, blocked_shot, direct_freekick, ...",[volley],"[distance, header]",0,1,0,1
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,[],[],"[blocked_shot, blocked_shot, blocked_shot, blo...","[header, blocked_shot, header, blocked_shot]","[deflected, volley, big chance shot, big chanc...","[distance, distance, distance, shot, distance]",0,0,0,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,[header],[tap_in],"[blocked_shot, blocked_shot, distance, blocked...","[blocked_shot, header]","[shot, deflected, direct_freekick, bad shot, d...","[distance, shot, header, distance, bad shot, d...",1,0,0,0
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,[shot],[],"[distance, shot]","[distance, distance, shot, blocked_shot, dista...","[header, distance, deflected, header]","[deflected, crossbar, post, volley, shot, defl...",0,0,0,1
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,"[shot, header]","[header, shot, shot]","[blocked_shot, big chance shot, big chance sho...","[distance, blocked_shot, blocked_shot]","[header, shot, distance, direct_freekick, dist...",[post],1,0,0,1
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,[distance],[],"[blocked_shot, deflected, blocked_shot, shot, ...","[big chance shot, blocked_shot, big chance sho...","[big chance shot, shot, shot, shot, crossbar, ...","[shot, shot, big chance header, header, shot, ...",0,0,0,1
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,"[shot, header, shot]","[shot, header]","[shot, blocked_shot, blocked_shot, blocked_sho...",[indirect freekick],"[distance, distance, distance, direct_freekick...",[],1,0,0,2
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,[shot],[shot],"[distance, blocked_shot, blocked_shot]","[header, distance, blocked_shot, blocked_shot,...","[header, distance, big chance shot, volley]","[header, header, deflected, distance, distance...",0,0,0,1
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,"[shot, tap_in]",[shot],"[distance, shot, deflected, deflected, blocked...","[blocked_shot, blocked_shot, big chance shot, ...","[header, shot, shot, big chance shot, distance...","[shot, shot, header, header, shot, shot, heade...",0,0,0,2
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,"[shot, shot, shot]",[header],"[big chance shot, distance, big chance shot, h...","[blocked_shot, blocked_shot, distance, blocked...","[direct_freekick, header, big chance volley, d...","[volley, bad shot, bad shot, deflected, deflec...",0,0,0,3
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,[shot],[],"[distance, blocked_shot, blocked_shot, shot, s...","[shot, blocked_shot, blocked_shot, distance]","[header, big chance shot, shot, distance, dist...","[deflected, big chance shot, deflected, shot, ...",0,0,0,1
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,[shot],[deflected],"[blocked_shot, distance, distance, blocked_shot]",[shot],"[shot, crossbar, distance, big chance shot, bi...","[shot, deflected, deflected, deflected, shot]",0,0,0,1
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,[],[],"[distance, shot, blocked_shot, blocked_shot, h...","[blocked_shot, deflected, shot]","[post, crossbar, deflected, direct_freekick, v...","[header, header, shot, deflected, header, head...",0,0,0,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,[volley],[],"[big chance shot, big chance shot, distance]","[shot, blocked_shot, distance, blocked_shot, h...","[big chance shot, shot]","[shot, distance, deflected, volley, shot, dist...",0,0,1,0
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,[],[],"[shot, blocked_shot, header, deflected]","[shot, shot, distance, big chance shot, shot, ...","[distance, shot]","[volley, bad shot, shot, distance, distance, b...",0,0,0,0
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,"[header, distance, shot, missed]",[shot],"[header, blocked_shot, header, big chance shot]","[volley, header, big chance shot, shot, shot, ...","[distance, crossbar, deflected, header, big ch...","[bad shot, shot, deflected, bad shot, shot, bi...",1,0,0,3
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,[shot],[volley],"[blocked_shot, blocked_shot, blocked_shot, sho...","[distance, distance, blocked_shot, big chance ...","[direct_freekick, header, deflected, big chanc...","[bad shot, big chance post, shot, direct_freek...",0,0,0,1
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,"[header, header, shot]","[bicycle_kick, shot]","[blocked_shot, shot]","[big chance shot, shot, header, blocked_shot, ...","[shot, distance, distance, distance, direct_fr...","[header, shot, crossbar, distance, direct_free...",2,0,0,1
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,[],[saved],"[blocked_shot, blocked_shot, blocked_shot, dis...","[blocked_shot, big chance shot, shot, big chan...","[distance, distance, shot, big chance shot, di...","[volley, volley, header, header, big chance sh...",0,0,0,0
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,[],[shot],"[blocked_shot, distance, blocked_shot, blocked...","[blocked_shot, header, blocked_shot, blocked_s...","[distance, header, shot, direct_freekick, header]","[distance, header, direct_freekick, big chance...",0,0,0,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,[],"[tap_in, header]","[direct_freekick, blocked_shot, blocked_shot, ...","[shot, shot, big chance shot, blocked_shot, sh...","[distance, shot, big chance header, distance, ...","[header, big chance crossbar, shot, big chance...",0,0,0,0
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,[tap_in],"[shot, shot]","[big chance volley, blocked_shot, big chance h...",[blocked_shot],"[distance, direct_freekick, header, header, sh...","[direct_freekick, deflected, direct_freekick, ...",0,0,0,1
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,[shot],[],"[indirect freekick, blocked_shot, blocked_shot...","[blocked_shot, header, shot, bicycle_kick, hea...","[shot, distance, shot, deflected, header]","[distance, shot, shot, shot, header]",0,0,0,1
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,[],"[shot, shot, distance]","[distance, blocked_shot]","[blocked_shot, volley, blocked_shot, header, s...","[header, deflected, distance, distance, header...","[deflected, direct_freekick, crossbar, volley,...",0,0,0,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,"[distance, shot, loose_ball, volley]",[shot],"[blocked_shot, shot, blocked_shot, blocked_sho...",[distance],"[big chance shot, distance, direct_freekick, d...","[shot, bicycle_kick, direct_freekick, header, ...",0,0,1,3

In [101]:
def away_goals(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    for types in df['away_goal_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
    df['away_goal_headers'] = header_list
    df['away_goal_freekicks'] = freekick_list
    df['away_goal_volleys'] = volley_list
    df['away_goal_other'] = other_list
    return df

In [102]:
away_goals(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_shotoff_types,away_shotoff_types,home_goal_headers,home_goal_freekicks,home_goal_volleys,home_goal_other,away_goal_headers,away_goal_freekicks,away_goal_volleys,away_goal_other
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,"[lob, header, deflected, direct_freekick, shot]",[],1,0,0,1,1,0,0,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,"[shot, header, header, distance, distance, dis...","[shot, direct_freekick]",0,0,0,1,0,0,0,1
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,"[shot, volley]","[post, distance, shot, shot, shot, header]",0,0,0,0,0,0,0,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,"[distance, volley, header, header, deflected, ...","[indirect freekick, shot, header, distance, ba...",0,0,0,1,0,0,0,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,"[shot, distance, shot, shot, distance, crossba...","[shot, shot]",0,0,0,0,1,0,0,1
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,"[distance, crossbar, deflected, header, direct...","[header, shot, deflected, direct_freekick]",0,0,0,1,2,0,0,1
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,"[distance, shot, shot, shot, distance, shot, d...","[deflected, big chance shot, shot, volley, dis...",0,0,0,1,0,1,0,3
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,"[header, deflected, bad shot, shot, shot, shot...","[shot, distance, shot, distance]",1,0,0,2,0,0,1,2
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,[],"[bicycle_kick, distance, deflected, distance, ...",1,0,0,1,0,0,0,3
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,"[bad shot, shot, direct_freekick, distance, de...","[crossbar, shot, shot, shot]",0,0,0,0,0,0,0,0
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,"[shot, miss_kick, shot, shot, deflected, shot,...","[post, distance, shot]",0,0,0,1,1,0,0,1
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,"[bad shot, shot, shot, distance, big chance sh...","[post, shot]",0,0,0,1,0,0,0,0
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,"[header, direct_freekick, shot, shot, shot, sh...","[deflected, shot, deflected, shot]",0,0,0,1,0,0,0,0
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,"[shot, distance, shot, shot, distance, miss_ki...","[bicycle_kick, header, shot, bad shot, bicycle...",0,0,0,3,1,0,0,0
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,"[distance, shot, post, direct_freekick, shot, ...","[big chance shot, shot, shot, post, post]",0,0,1,1,1,0,0,1
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,"[distance, header, header, deflected, deflecte...","[big chance volley, distance, volley, big chan...",1,0,0,4,0,0,0,0
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,"[distance, deflected, direct_freekick, deflect...","[shot, shot, volley]",0,0,0,0,0,0,0,1
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,"[big chance shot, big chance shot, volley, big...","[shot, big chance shot, deflected, deflected, ...",0,0,0,0,1,0,0,2
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,"[shot, header, shot, volley, shot, shot]","[direct_freekick, header, volley, shot, distan...",1,0,0,1,0,0,0,1
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,"[lob, distance, shot, bad shot, header, header...","[shot, distance, header, direct_freekick]",0,0,0,0,0,0,0,2
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,"[volley, header, deflected, header, volley, vo...","[volley, shot, volley, volley, header, deflect...",0,0,1,0,0,0,0,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,[header],"[deflected, big chance shot, header, header, s...",0,0,0,1,0,0,0,1
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,"[header, distance, distance, distance, lob]","[bad shot, header, header, distance, shot, dis...",0,0,0,0,0,0,0,3
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,"[shot, header, miss_kick]","[direct_freekick, header, deflected, header, d...",0,0,0,2,0,0,0,4
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,"[shot, distance, header, deflected]","[shot, distance, header, post, deflected, dist...",0,0,0,1,0,0,0,3
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,"[shot, volley]",[shot],0,0,0,1,0,0,0,1
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,"[shot, header, shot, shot, distance, header, d...","[shot, distance, distance, header]",1,0,0,2,0,0,0,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,"[distance, bad shot, big chance post, distance...","[header, distance]",0,0,0,1,0,1,0,1
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,"[shot, distance, distance, shot, distance]","[distance, distance]",1,0,0,2,0,0,0,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,"[header, crossbar, distance, deflected, header...","[bad shot, distance, shot, header, shot, bad s...",0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,"[distance, distance, distance, distance, big c...","[bad shot, bad shot]",0,0,0,0,0,0,0,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,"[bad shot, big chance crossbar, distance, shot...","[distance, volley, distance, header, shot, shot]",0,0,0,4,0,0,0,0
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,"[header, shot, distance, direct_freekick, shot...","[distance, volley, header, shot]",0,0,0,0,0,0,0,1
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,"[crossbar, big chance shot, big chance shot, d...",[header],0,0,0,3,0,0,0,0
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,"[header, distance, shot, bad shot]","[distance, bad shot, distance, volley]",0,0,0,3,0,0,0,1
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,[volley],"[distance, header]",0,1,0,1,0,0,0,1
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,"[deflected, volley, big chance shot, big chanc...","[distance, distance, distance, shot, distance]",0,0,0,0,0,0,0,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,"[shot, deflected, direct_freekick, bad shot, d...","[distance, shot, header, distance, bad shot, d...",1,0,0,0,0,0,0,1
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,"[header, distance, deflected, header]","[deflected, crossbar, post, volley, shot, defl...",0,0,0,1,0,0,0,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,"[header, shot, distance, direct_freekick, dist...",[post],1,0,0,1,1,0,0,2
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,"[big chance shot, shot, shot, shot, crossbar, ...","[shot, shot, big chance header, header, shot, ...",0,0,0,1,0,0,0,0
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,"[distance, distance, distance, direct_freekick...",[],1,0,0,2,1,0,0,1
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,"[header, distance, big chance shot, volley]","[header, header, deflected, distance, distance...",0,0,0,1,0,0,0,1
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,"[header, shot, shot, big chance shot, distance...","[shot, shot, header, header, shot, shot, heade...",0,0,0,2,0,0,0,1
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,"[direct_freekick, header, big chance volley, d...","[volley, bad shot, bad shot, deflected, deflec...",0,0,0,3,1,0,0,0
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,"[header, big chance shot, shot, distance, dist...","[deflected, big chance shot, deflected, shot, ...",0,0,0,1,0,0,0,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,"[shot, crossbar, distance, big chance shot, bi...","[shot, deflected, deflected, deflected, shot]",0,0,0,1,0,0,0,1
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,"[post, crossbar, deflected, direct_freekick, v...","[header, header, shot, deflected, header, head...",0,0,0,0,0,0,0,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,"[big chance shot, shot]","[shot, distance, deflected, volley, shot, dist...",0,0,1,0,0,0,0,0
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,"[distance, shot]","[volley, bad shot, shot, distance, distance, b...",0,0,0,0,0,0,0,0
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,"[distance, crossbar, deflected, header, big ch...","[bad shot, shot, deflected, bad shot, shot, bi...",1,0,0,3,0,0,0,1
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,"[direct_freekick, header, deflected, big chanc...","[bad shot, big chance post, shot, direct_freek...",0,0,0,1,0,0,1,0
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,"[shot, distance, distance, distance, direct_fr...","[header, shot, crossbar, distance, direct_free...",2,0,0,1,0,0,0,2
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,"[distance, distance, shot, big chance shot, di...","[volley, volley, header, header, big chance sh...",0,0,0,0,0,0,0,1
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,"[distance, header, shot, direct_freekick, header]","[distance, header, direct_freekick, big chance...",0,0,0,0,0,0,0,1
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,"[distance, shot, big chance header, distance, ...","[header, big chance crossbar, shot, big chance...",0,0,0,0,1,0,0,1
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,"[distance, direct_freekick, header, header, sh...","[direct_freekick, deflected, direct_freekick, ...",0,0,0,1,0,0,0,2
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,"[shot, distance, shot, deflected, header]","[distance, shot, shot, shot, header]",0,0,0,1,0,0,0,0
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,"[header, deflected, distance, distance, header...","[deflected, direct_freekick, crossbar, volley,...",0,0,0,0,0,0,0,3
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,"[big chance shot, distance, direct_freekick, d...","[shot, bicycle_kick, direct_freekick, header, ...",0,0,1,3,0,0,0,1

In [103]:
def home_shots(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['home_shoton_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
    df['home_shoton_headers'] = header_list
    df['home_shoton_freekicks'] = freekick_list
    df['home_shoton_volleys'] = volley_list
    df['home_shoton_other'] = other_list
    df['home_shoton_bigchance'] = big_chances
    return df

In [104]:
home_shots(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_goal_other,away_goal_headers,away_goal_freekicks,away_goal_volleys,away_goal_other,home_shoton_headers,home_shoton_freekicks,home_shoton_volleys,home_shoton_other,home_shoton_bigchance
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,1,1,0,0,0,0,0,0,7,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,1,0,0,0,1,1,0,0,5,2
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,0,0,0,0,0,2,0,1,5,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,1,0,0,0,1,1,0,0,5,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,0,1,0,0,1,0,0,0,7,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,1,2,0,0,1,1,0,0,4,1
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,1,0,1,0,3,1,0,0,7,0
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,2,0,0,1,2,0,0,0,4,1
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,1,0,0,0,3,0,0,0,2,0
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,0,0,0,0,0,1,0,6,1
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,1,1,0,0,1,0,0,0,6,0
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,1,0,0,0,0,0,0,0,7,0
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,1,0,0,0,0,0,0,2,3,0
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,3,1,0,0,0,0,0,0,3,0
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,1,1,0,0,1,0,0,0,4,0
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,4,0,0,0,0,1,1,0,11,1
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,0,0,0,0,1,1,0,0,0,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,0,1,0,0,2,0,0,1,8,1
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,1,0,0,0,1,0,0,0,4,1
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,0,0,0,2,0,0,0,5,0
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,0,0,0,0,0,0,0,0,2,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,1,0,0,0,1,0,0,0,1,0
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,0,0,0,3,0,0,0,8,0
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,2,0,0,0,4,2,0,0,5,2
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,1,0,0,0,3,1,0,0,3,0
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,1,0,0,0,1,2,0,0,13,2
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,2,0,0,0,0,3,0,0,5,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,1,0,1,0,1,1,1,0,9,1
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,2,0,0,0,0,1,0,0,1,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,0,0,1,0,1,0,0,0,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,0,0,0,0,0,0,0,0,7,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,4,0,0,0,0,0,0,0,7,0
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,0,0,0,0,1,2,0,0,5,1
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,3,0,0,0,0,0,1,1,12,1
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,3,0,0,0,1,0,0,0,1,0
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,1,0,0,0,1,0,0,0,4,0
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,0,0,0,0,0,0,0,0,10,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,0,0,0,0,1,1,0,0,15,0
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,1,0,0,0,0,0,0,0,2,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,1,1,0,0,2,1,1,0,4,2
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,1,0,0,0,0,1,1,0,7,0
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,2,1,0,0,1,3,0,0,23,5
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,1,0,0,0,1,0,0,0,3,0
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,2,0,0,0,1,1,0,0,7,1
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,3,1,0,0,0,1,1,0,7,3
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,1,0,0,0,0,0,0,0,8,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,1,0,0,0,1,0,0,0,4,0
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,0,0,0,0,0,1,0,0,4,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,0,0,0,0,0,0,0,0,3,2
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,0,0,0,0,0,1,0,0,3,0
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,3,0,0,0,1,2,0,0,2,1
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,1,0,0,1,0,0,0,0,9,1
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,1,0,0,0,2,0,0,0,2,0
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,0,0,0,0,1,0,0,0,14,0
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,0,0,0,1,0,0,0,4,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,0,1,0,0,1,1,1,0,7,0
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,1,0,0,0,2,1,0,1,4,2
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,1,0,0,0,0,0,2,0,6,1
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,0,0,0,3,0,0,0,2,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,3,0,0,0,1,0,0,0,10,0

In [105]:
def away_shots(df):
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['away_shoton_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
    df['away_shoton_headers'] = header_list
    df['away_shoton_freekicks'] = freekick_list
    df['away_shoton_volleys'] = volley_list
    df['away_shoton_other'] = other_list
    df['away_shoton_bigchance'] = big_chances
    return df

In [106]:
away_shots(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_shoton_headers,home_shoton_freekicks,home_shoton_volleys,home_shoton_other,home_shoton_bigchance,away_shoton_headers,away_shoton_freekicks,away_shoton_volleys,away_shoton_other,away_shoton_bigchance
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,0,0,0,7,0,0,0,0,3,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,1,0,0,5,2,0,0,0,4,1
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,2,0,1,5,0,0,0,0,4,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,1,0,0,5,1,0,0,0,3,0
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,0,0,0,7,0,2,0,0,5,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,1,0,0,4,1,1,0,0,3,0
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,1,0,0,7,0,0,0,1,4,0
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,0,0,0,4,1,0,0,1,4,0
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,0,0,0,2,0,1,0,0,2,0
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,1,0,6,1,0,0,0,2,0
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,0,0,0,6,0,0,0,0,4,0
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,0,0,0,7,0,2,0,0,5,0
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,0,0,2,3,0,0,0,0,5,1
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,0,0,0,3,0,0,0,0,1,0
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,0,0,0,4,0,0,0,0,8,2
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,1,1,0,11,1,0,0,0,3,0
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,1,0,0,0,0,0,0,0,5,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,0,0,1,8,1,0,0,0,2,1
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,0,0,0,4,1,0,0,0,9,3
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,0,0,5,0,0,0,0,7,0
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,0,0,0,2,0,1,0,0,11,1
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,0,0,0,1,0,1,0,0,3,0
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,0,0,8,0,0,0,0,4,1
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,2,0,0,5,2,2,0,0,9,1
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,1,0,0,3,0,1,0,0,6,0
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,2,0,0,13,2,2,1,0,3,0
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,3,0,0,5,0,0,0,0,2,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,1,1,0,9,1,0,0,0,4,0
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,1,0,0,1,0,0,0,0,2,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,0,0,0,7,3,0,1,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,0,0,0,7,0,0,0,0,1,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,0,0,0,7,0,0,0,0,2,1
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,2,0,0,5,1,0,0,0,0,0
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,0,1,1,12,1,1,0,0,0,0
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,0,0,0,1,0,0,0,0,2,0
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,0,0,0,4,0,1,1,0,6,0
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,0,0,0,10,0,2,0,0,2,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,1,0,0,15,0,1,0,0,1,0
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,0,0,0,2,0,0,0,0,6,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,1,1,0,4,2,0,0,0,3,0
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,1,1,0,7,0,1,0,0,7,2
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,3,0,0,23,5,0,1,0,0,0
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,0,0,0,3,0,1,0,0,4,1
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,1,0,0,7,1,2,0,0,3,1
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,1,1,0,7,3,0,0,0,5,0
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,0,0,0,8,0,0,0,0,4,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,0,0,0,4,0,0,0,0,1,0
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,1,0,0,4,0,0,0,0,3,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,0,0,0,3,2,1,0,0,7,0
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,1,0,0,3,0,0,0,1,7,1
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,2,0,0,2,1,2,0,1,5,1
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,0,0,0,9,1,1,0,0,7,1
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,0,0,0,2,0,1,0,0,11,1
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,0,0,0,14,0,0,1,1,11,3
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,0,0,4,0,1,0,0,6,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,1,1,0,7,0,0,0,0,8,1
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,1,0,1,4,2,0,0,0,1,0
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,0,2,0,6,1,2,0,0,6,0
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,0,0,2,0,2,0,1,3,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,0,0,0,10,0,0,0,0,1,0

In [107]:
def home_shots_off(df):
    bad_shots = []
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['home_shotoff_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        bad_shot = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            elif 'bad shot' in typ:
                bad_shot += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
        bad_shots.append(bad_shot)
    df['home_shotoff_headers'] = header_list
    df['home_shotoff_freekicks'] = freekick_list
    df['home_shotoff_volleys'] = volley_list
    df['home_shotoff_other'] = other_list
    df['home_shotoff_bigchance'] = big_chances
    df['home_shotoff_bad_shot'] = bad_shots
    return df

In [108]:
home_shots_off(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,away_shoton_freekicks,away_shoton_volleys,away_shoton_other,away_shoton_bigchance,home_shotoff_headers,home_shotoff_freekicks,home_shotoff_volleys,home_shotoff_other,home_shotoff_bigchance,home_shotoff_bad_shot
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,0,0,3,0,1,1,0,3,0,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,0,0,4,1,2,0,0,5,0,0
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,0,0,4,0,0,0,1,1,0,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,0,0,3,0,3,0,1,3,0,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,0,0,5,0,0,0,1,7,0,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,0,0,3,0,4,1,0,5,0,0
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,0,1,4,0,0,1,0,6,0,1
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,0,1,4,0,3,0,0,7,0,1
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,0,0,2,0,0,0,0,0,0,0
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,0,2,0,3,2,0,4,0,1
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,0,0,4,0,0,0,0,7,0,0
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,0,0,5,0,1,1,0,8,2,1
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,0,0,5,1,2,1,1,8,1,0
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,0,0,1,0,0,0,0,8,1,1
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,0,0,8,2,0,1,0,8,0,0
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,0,0,3,0,2,0,0,7,0,0
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,0,0,5,0,0,2,1,3,0,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,0,0,2,1,1,0,1,4,3,0
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,0,0,9,3,1,0,1,4,0,0
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,0,7,0,2,0,0,5,0,1
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,0,0,11,1,2,0,3,1,0,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,0,0,3,0,1,0,0,0,0,0
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,0,4,1,1,0,0,4,0,0
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,0,0,9,1,1,0,0,2,0,0
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,0,0,6,0,1,0,0,3,0,0
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,1,0,3,0,0,0,1,1,0,0
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,0,0,2,0,2,0,0,6,0,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,0,0,4,0,1,0,0,6,1,2
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,0,0,2,0,0,0,0,5,0,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,1,0,5,0,2,0,0,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,0,0,1,0,3,0,0,5,2,0
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,0,0,2,1,1,0,0,4,2,1
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,0,0,0,0,1,1,2,5,1,0
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,0,0,0,0,0,0,0,4,2,0
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,0,0,2,0,1,0,0,2,0,1
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,1,0,6,0,0,0,1,0,0,0
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,0,0,2,0,0,0,1,3,2,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,0,0,1,0,0,2,0,6,0,1
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,0,0,6,0,2,0,0,2,0,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,0,0,3,0,3,1,0,6,2,0
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,0,0,7,2,0,0,0,6,2,0
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,1,0,0,0,0,1,0,9,0,3
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,0,0,4,1,1,0,1,2,1,0
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,0,0,3,1,3,1,0,4,1,1
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,0,0,5,0,2,1,2,4,2,0
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,0,0,4,0,3,1,0,6,1,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,0,0,1,0,0,1,0,11,4,1
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,0,0,3,0,0,1,1,4,0,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,0,0,7,0,0,0,0,2,1,0
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,0,1,7,1,0,0,0,2,0,0
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,0,1,5,1,1,0,0,5,1,0
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,0,0,7,1,2,1,0,3,2,0
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,0,0,11,1,0,1,0,4,0,0
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,1,1,11,3,0,0,0,5,1,0
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,0,6,0,2,1,0,2,0,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,0,0,8,1,2,0,0,5,1,0
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,0,0,1,0,4,1,2,7,1,2
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,0,0,6,0,1,0,0,4,0,0
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,1,3,0,2,0,0,4,0,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,0,0,1,0,1,1,0,6,3,1

In [109]:
def away_shots_off(df):
    bad_shots = []
    header_list = []
    freekick_list = []
    volley_list = []
    other_list = []
    big_chances = []
    for types in df['away_shotoff_types']:
        headers = 0
        freekicks = 0
        volleys = 0
        others = 0
        big_chance = 0
        bad_shot = 0
        for typ in types:
            if 'header' in typ:
                headers += 1
            elif 'freekick' in typ:
                freekicks += 1
            elif 'volley' in typ:
                volleys += 1
            elif 'bad shot' in typ:
                bad_shot += 1
            else:
                others += 1
            if 'big chance' in typ:
                big_chance += 1
        header_list.append(headers)
        freekick_list.append(freekicks)
        volley_list.append(volleys)
        other_list.append(others)
        big_chances.append(big_chance)
        bad_shots.append(bad_shot)
    df['away_shotoff_headers'] = header_list
    df['away_shotoff_freekicks'] = freekick_list
    df['away_shotoff_volleys'] = volley_list
    df['away_shotoff_other'] = other_list
    df['away_shotoff_bigchance'] = big_chances
    df['away_shotoff_bad_shot'] = bad_shots
    return df

In [110]:
away_shots_off(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_shotoff_volleys,home_shotoff_other,home_shotoff_bigchance,home_shotoff_bad_shot,away_shotoff_headers,away_shotoff_freekicks,away_shotoff_volleys,away_shotoff_other,away_shotoff_bigchance,away_shotoff_bad_shot
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,0,3,0,0,0,0,0,0,0,0
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,0,5,0,0,0,1,0,1,0,0
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,1,1,0,0,1,0,0,5,0,0
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,1,3,0,1,1,1,0,3,0,1
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,1,7,0,0,0,0,0,2,0,0
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,0,5,0,0,1,1,0,2,0,0
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,0,6,0,1,0,0,1,6,2,0
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,0,7,0,1,0,0,0,4,0,0
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,0,0,0,0,0,0,0,6,0,0
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,4,0,1,0,0,0,4,0,0
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,0,7,0,0,0,0,0,3,0,0
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,0,8,2,1,0,0,0,2,0,0
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,1,8,1,0,0,0,0,4,0,0
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,0,8,1,1,1,0,0,3,0,1
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,0,8,0,0,0,0,0,5,1,0
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,0,7,0,0,0,0,2,6,2,0
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,1,3,0,0,0,0,1,2,0,0
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,1,4,3,0,0,0,0,5,1,0
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,1,4,0,0,2,1,2,8,0,0
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,5,0,1,1,1,0,2,0,0
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,3,1,0,0,2,0,4,3,0,0
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,0,0,0,0,2,0,0,3,1,0
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,4,0,0,2,0,0,4,0,1
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,0,2,0,0,2,1,0,3,0,0
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,0,3,0,0,1,0,0,5,0,2
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,1,1,0,0,0,0,0,1,0,0
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,0,6,0,0,1,0,0,3,0,0
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,0,6,1,2,1,0,0,1,0,0
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,0,5,0,0,0,0,0,2,0,0
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,0,4,0,0,1,0,0,3,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,0,5,2,0,0,0,0,0,0,2
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,0,4,2,1,1,0,1,4,0,0
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,2,5,1,0,1,0,1,2,0,0
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,0,4,2,0,1,0,0,0,0,0
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,0,2,0,1,0,0,1,2,0,1
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,1,0,0,0,1,0,0,1,0,0
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,1,3,2,0,0,0,0,5,0,0
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,0,6,0,1,1,0,0,4,0,1
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,0,2,0,0,0,0,1,6,0,0
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,0,6,2,0,0,0,0,1,0,0
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,0,6,2,0,3,0,0,7,1,0
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,0,9,0,3,0,0,0,0,0,0
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,1,2,1,0,3,0,0,3,0,0
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,0,4,1,1,4,0,0,7,0,0
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,2,4,2,0,0,1,1,3,0,2
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,0,6,1,0,0,0,1,5,1,0
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,0,11,4,1,0,0,0,5,0,0
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,1,4,0,0,4,0,0,5,0,0
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,0,2,1,0,0,0,1,9,0,1
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,0,2,0,0,0,0,2,8,2,1
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,0,5,1,0,2,0,1,7,1,3
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,0,3,2,0,3,1,0,6,2,1
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,0,4,0,0,1,1,0,3,0,0
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,0,5,1,0,2,0,2,3,1,0
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,2,0,0,1,1,0,8,1,0
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,0,5,1,0,1,0,1,5,2,0
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,2,7,1,2,0,2,0,3,0,2
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,0,4,0,0,1,0,0,4,0,0
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,4,0,0,0,1,1,5,2,0
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,0,6,3,1,1,1,0,3,0,0

In [111]:
def clean_html_cross(element):
    try:
        soup = BeautifulSoup(element)
        text = soup.findAll('team')
        output = {}
        for i in text:
            output[i.get_text()] = 0
        for i in text:
            output[i.get_text()] += 1
        return output
    except:
        return element

In [112]:
def split_cross(df):
    cross_dict = df['cross'].map(clean_html_cross)
    home_crosses = []
    away_crosses = []
    for key, id_ in zip(cross_dict,df['home_team_api_id']):
        try:
            for k,v in key.items():
                if float(k) == id_:
                    home_crosses.append(v)
                else:
                    away_crosses.append(v)
        except:
            home_crosses.append('')
            away_crosses.append('')
    df['home_crosses'] = home_crosses
    df['away_crosses'] = away_crosses
    return df

In [113]:
split_cross(final_merge)

,away_corners,away_fouls,away_shots,away_shots_target,away_yellow_cards,away_red_cards,attendance,away_team,full_time_away_goals,full_time_home_goals,...,home_shotoff_bigchance,home_shotoff_bad_shot,away_shotoff_headers,away_shotoff_freekicks,away_shotoff_volleys,away_shotoff_other,away_shotoff_bigchance,away_shotoff_bad_shot,home_crosses,away_crosses
0,3,19,4,2,2,1,NaN,Crystal Palace,1,2,...,0,0,0,0,0,0,0,0,32,9
1,5,10,10,4,0,1,NaN,Tottenham,1,0,...,0,0,0,1,0,1,0,0,26,10
2,4,17,10,3,1,0,NaN,Crystal Palace,0,0,...,0,0,1,0,0,5,0,0,28,19
3,4,14,12,3,4,0,NaN,Crystal Palace,2,1,...,0,1,1,1,0,3,0,1,29,11
4,3,8,8,6,1,0,NaN,Crystal Palace,2,2,...,0,0,0,0,0,2,0,0,27,7
5,7,19,12,5,2,1,NaN,Crystal Palace,3,1,...,0,0,1,1,0,2,0,0,21,13
6,5,17,15,6,3,0,NaN,Crystal Palace,3,1,...,0,1,0,0,1,6,2,0,12,12
7,4,19,12,7,3,0,NaN,Crystal Palace,3,3,...,0,1,0,0,0,4,0,0,28,12
8,7,20,11,4,3,0,NaN,Crystal Palace,3,2,...,0,0,0,0,0,6,0,0,10,12
9,2,12,6,0,1,0,NaN,Crystal Palace,0,0,...,0,1,0,0,0,4,0,0,21,13
10,1,13,10,3,2,0,NaN,Crystal Palace,3,2,...,0,0,0,0,0,3,0,0,16,12
11,2,10,9,3,2,0,NaN,Crystal Palace,0,1,...,2,1,0,0,0,2,0,0,17,17
12,6,12,11,5,2,0,NaN,Crystal Palace,1,1,...,1,0,0,0,0,4,0,0,30,7
13,6,5,6,1,1,0,NaN,Crystal Palace,0,3,...,1,1,1,0,0,3,0,1,16,16
14,3,15,15,8,4,0,NaN,Manchester City,2,2,...,0,0,0,0,0,5,1,0,22,16
15,4,11,11,2,3,0,NaN,Swansea,2,4,...,0,0,0,0,2,6,2,0,20,11
16,2,13,9,4,2,0,NaN,Manchester City,1,0,...,0,0,0,0,1,2,0,0,19,7
17,6,9,9,5,1,0,NaN,Manchester City,3,1,...,3,0,0,0,0,5,1,0,13,7
18,8,14,21,5,1,0,NaN,Manchester City,1,2,...,0,0,2,1,2,8,0,0,26,17
19,3,11,13,5,5,0,NaN,Manchester City,2,0,...,0,1,1,1,0,2,0,0,21,13
20,6,9,21,5,1,0,NaN,Manchester City,0,1,...,0,0,2,0,4,3,0,0,13,28
21,4,14,10,5,2,0,NaN,Manchester City,1,1,...,0,0,2,0,0,3,1,0,9,17
22,6,13,15,6,2,1,NaN,Manchester City,3,0,...,0,0,2,0,0,4,0,1,19,9
23,7,8,22,11,3,0,NaN,Manchester City,4,2,...,0,0,2,1,0,3,0,0,11,9
24,8,6,20,6,2,0,NaN,Manchester City,4,2,...,0,0,1,0,0,5,0,2,23,8
25,5,16,6,4,6,0,NaN,Tottenham,1,1,...,0,0,0,0,0,1,0,0,30,6
26,2,9,7,1,2,0,NaN,Aston Villa,0,3,...,0,0,1,0,0,3,0,0,17,12
27,1,14,8,3,2,0,NaN,Tottenham,2,1,...,1,2,1,0,0,1,0,0,5,4
28,2,10,5,1,1,0,NaN,Tottenham,0,3,...,0,0,0,0,0,2,0,0,12,9
29,3,13,14,4,1,0,NaN,Tottenham,3,0,...,0,0,1,0,0,3,0,2,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,1,11,3,1,3,0,NaN,Stoke,0,0,...,2,0,0,0,0,0,0,2,30,4
883,5,10,7,2,2,0,NaN,Stoke,0,3,...,2,1,1,0,1,4,0,0,9,14
884,1,12,7,1,0,0,NaN,Stoke,1,0,...,1,0,1,0,1,2,0,0,22,11
885,2,5,2,0,1,0,NaN,Stoke,0,3,...,2,0,1,0,0,0,0,0,8,10
886,1,13,5,2,2,0,NaN,Stoke,1,3,...,0,1,0,0,1,2,0,1,18,9
887,5,12,9,5,2,0,NaN,Stoke,0,4,...,0,0,1,0,0,1,0,0,18,25
888,2,14,8,3,3,0,NaN,Stoke,0,2,...,2,0,0,0,0,5,0,0,17,12
889,1,10,8,2,1,0,NaN,Stoke,1,1,...,0,1,1,0,0,4,0,1,31,8
890,2,9,15,9,4,0,NaN,Queens Park Rangers,0,1,...,0,0,0,0,1,6,0,0,13,7
891,5,10,9,8,2,0,NaN,Queens Park Rangers,3,2,...,2,0,0,0,0,1,0,0,35,13
892,8,11,16,6,1,0,NaN,Queens Park Rangers,0,1,...,2,0,3,0,0,7,1,0,12,18
893,0,6,3,3,1,1,NaN,Queens Park Rangers,2,3,...,0,3,0,0,0,0,0,0,61,3
894,11,12,12,7,3,0,NaN,Queens Park Rangers,1,1,...,1,0,3,0,0,3,0,0,11,22
895,4,7,13,4,0,0,NaN,Queens Park Rangers,1,2,...,1,1,4,0,0,7,0,0,16,14
896,8,14,12,8,0,0,NaN,Queens Park Rangers,1,3,...,2,0,0,1,1,3,0,2,15,18
897,5,10,13,6,1,0,NaN,Chelsea,0,1,...,1,0,0,0,1,5,1,0,21,17
898,4,7,6,5,2,0,NaN,Chelsea,1,2,...,4,1,0,0,0,5,0,0,23,13
899,7,11,13,7,4,0,NaN,Chelsea,0,0,...,0,0,4,0,0,5,0,0,14,18
900,11,19,20,10,3,1,NaN,Chelsea,1,1,...,1,0,0,0,1,9,0,1,2,31
901,11,4,19,9,0,0,NaN,Chelsea,0,0,...,0,0,0,0,2,8,2,1,14,34
902,10,12,20,9,3,0,NaN,Chelsea,1,3,...,1,0,2,0,1,7,1,3,18,24
903,4,8,20,10,2,0,NaN,Chelsea,1,1,...,2,0,3,1,0,6,2,1,17,11
904,17,6,18,11,0,0,NaN,Liverpool,2,3,...,0,0,1,1,0,3,0,0,21,26
905,14,12,18,10,2,0,NaN,Liverpool,0,0,...,1,0,2,0,2,3,1,0,20,29
906,10,9,17,7,0,0,NaN,Liverpool,2,0,...,0,0,1,1,0,8,1,0,12,25
907,10,14,19,12,2,0,NaN,Liverpool,2,0,...,1,0,1,0,1,5,2,0,13,18
908,5,11,9,3,2,0,NaN,Liverpool,2,1,...,1,2,0,2,0,3,0,2,23,11
909,5,5,14,9,1,0,NaN,Liverpool,0,1,...,0,0,1,0,0,4,0,0,11,12
910,7,4,15,9,0,0,NaN,Liverpool,3,0,...,0,0,0,1,1,5,2,0,13,11
911,1,9,5,2,4,2,NaN,Liverpool,0,4,...,3,1,1,1,0,3,0,0,21,5

In [114]:
final_merge.drop(['foulcommit','card','cross','corner','home_goal_types','home_shoton_types','home_shotoff_types',
                 'away_goal_types','away_shoton_types','away_shotoff_types'],axis=1,inplace=True)

In [115]:
final_merge['half_time_result'] = final_merge['half_time_result'].map(lambda x: 3 if x=='H' else 0 if x=='A' else 1)
final_merge['result'] = final_merge['result'].map(lambda x: 3 if x=='H' else 0 if x=='A' else 1)

In [116]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 912 entries, 0 to 911
Data columns (total 92 columns):
away_corners              912 non-null int64
away_fouls                912 non-null int64
away_shots                912 non-null int64
away_shots_target         912 non-null int64
away_yellow_cards         912 non-null int64
away_red_cards            912 non-null int64
attendance                0 non-null float64
away_team                 912 non-null object
full_time_away_goals      912 non-null int64
full_time_home_goals      912 non-null int64
home_corners              912 non-null int64
home_fouls                912 non-null int64
home_red_cards            912 non-null int64
home_yellow_cards         912 non-null int64
home_shots                912 non-null int64
home_shots_target         912 non-null int64
half_time_away_goals      912 non-null int64
half_time_home_goals      912 non-null int64
half_time_result          912 non-null int64
home_team                 912 non-null object
Referee                   672 non-null object
result                    912 non-null int64
FDCOUK                    912 non-null object
City                      912 non-null object
Stadium                   912 non-null object
Capacity                  912 non-null float64
Latitude                  912 non-null float64
Longitude                 912 non-null float64
Country                   912 non-null object
closest_station           912 non-null object
season                    912 non-null object
date                      912 non-null datetime64[ns]
home_team_api_id          912 non-null int64
away_team_api_id          912 non-null int64
goal                      912 non-null object
possession                912 non-null object
home_possession           912 non-null float64
home_passing              912 non-null float64
home_aerials              912 non-null float64
home_shots_against        912 non-null float64
home_tackles              912 non-null float64
home_interceptions        912 non-null float64
home_dribbles             912 non-null float64
home_fouls_for            912 non-null float64
away_possession           912 non-null float64
away_passing              912 non-null float64
away_aerials              912 non-null float64
away_shots_against        912 non-null float64
away_tackles              912 non-null float64
away_interceptions        912 non-null float64
away_dribbles             912 non-null float64
away_fouls_for            912 non-null float64
station                   912 non-null object
temp (F)                  912 non-null float64
dew (F)                   912 non-null float64
humidity                  912 non-null float64
wind direction            912 non-null float64
wind speed (mph)          912 non-null float64
prec (in)                 912 non-null float64
visibility (mi)           912 non-null float64
home_goal_headers         912 non-null int64
home_goal_freekicks       912 non-null int64
home_goal_volleys         912 non-null int64
home_goal_other           912 non-null int64
away_goal_headers         912 non-null int64
away_goal_freekicks       912 non-null int64
away_goal_volleys         912 non-null int64
away_goal_other           912 non-null int64
home_shoton_headers       912 non-null int64
home_shoton_freekicks     912 non-null int64
home_shoton_volleys       912 non-null int64
home_shoton_other         912 non-null int64
home_shoton_bigchance     912 non-null int64
away_shoton_headers       912 non-null int64
away_shoton_freekicks     912 non-null int64
away_shoton_volleys       912 non-null int64
away_shoton_other         912 non-null int64
away_shoton_bigchance     912 non-null int64
home_shotoff_headers      912 non-null int64
home_shotoff_freekicks    912 non-null int64
home_shotoff_volleys      912 non-null int64
home_shotoff_other        912 non-null int64
home_shotoff_bigchance    912 non-null int64
home_shotoff_bad_shot     912 non-null int64
away_shotoff_headers      912 non-null int64
away_shotoff_freekicks    912 non-null int64
away_shotoff_volleys      912 non-null int64
away_shotoff_other        912 non-null int64
away_shotoff_bigchance    912 non-null int64
away_shotoff_bad_shot     912 non-null int64
home_crosses              912 non-null int64
away_crosses              912 non-null int64
dtypes: datetime64[ns](1), float64(27), int64(52), object(12)
memory usage: 662.6+ KB

In [120]:
final_merge.drop(['attendance','goal'],axis=1,inplace=True)

ValueError: labels ['attendance' 'goal'] not contained in axis

In [ ]:
final_merge.drop(['FDCOUK','Latitude','Longitude','station','closest_station'],axis=1,inplace=True)

In [121]:
final_merge.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_v6.csv',index=False)

In [124]:
final_merge['possession'][0]

u'<possession><value><comment>78</comment><event_incident_typefk>352</event_incident_typefk><elapsed>24</elapsed><subtype>possession</subtype><sortorder>1</sortorder><awaypos>22</awaypos><homepos>78</homepos><n>128</n><type>special</type><id>3647521</id></value><value><comment>74</comment><elapsed_plus>1</elapsed_plus><event_incident_typefk>352</event_incident_typefk><elapsed>45</elapsed><subtype>possession</subtype><sortorder>3</sortorder><awaypos>26</awaypos><homepos>74</homepos><n>149</n><type>special</type><id>3647655</id></value><value><comment>75</comment><event_incident_typefk>352</event_incident_typefk><elapsed>66</elapsed><subtype>possession</subtype><sortorder>1</sortorder><awaypos>25</awaypos><homepos>75</homepos><n>93</n><type>special</type><id>3647956</id></value><value><comment>77</comment><elapsed_plus>4</elapsed_plus><event_incident_typefk>352</event_incident_typefk><elapsed>90</elapsed><subtype>possession</subtype><sortorder>11</sortorder><awaypos>23</awaypos><homepos>77</homepos><n>147</n><type>special</type><id>3648227</id></value></possession>'

In [128]:
soup = BeautifulSoup(final_merge['possession'][0])
home_text = soup.findAll('homepos')
home_text

[<homepos>78</homepos>,
 <homepos>74</homepos>,
 <homepos>75</homepos>,
 <homepos>77</homepos>]

In [138]:
def clean_home_possession(element):
    try:
        soup = BeautifulSoup(element)
        home_text = soup.findAll('homepos')
        home_pos = home_text[-1].get_text()
        return int(home_pos)
    except:
        return element

In [139]:
def clean_away_possession(element):
    try:
        soup = BeautifulSoup(element)
        away_text = soup.findAll('awaypos')
        away_pos = away_text[-1].get_text()
        return int(away_pos)
    except:
        return element

In [140]:
final_merge['home_possession'] = final_merge['possession'].map(clean_home_possession)
final_merge['away_possession'] = final_merge['possession'].map(clean_away_possession)

KeyError: 'possession'

In [135]:
final_merge.isnull().sum()

away_corners                0
away_fouls                  0
away_shots                  0
away_shots_target           0
away_yellow_cards           0
away_red_cards              0
away_team                   0
full_time_away_goals        0
full_time_home_goals        0
home_corners                0
home_fouls                  0
home_red_cards              0
home_yellow_cards           0
home_shots                  0
home_shots_target           0
half_time_away_goals        0
half_time_home_goals        0
half_time_result            0
home_team                   0
Referee                   240
result                      0
City                        0
Stadium                     0
Capacity                    0
Country                     0
season                      0
date                        0
home_team_api_id            0
away_team_api_id            0
possession                  0
                         ...
away_goal_headers           0
away_goal_freekicks         0
away_goal_volleys           0
away_goal_other             0
home_shoton_headers         0
home_shoton_freekicks       0
home_shoton_volleys         0
home_shoton_other           0
home_shoton_bigchance       0
away_shoton_headers         0
away_shoton_freekicks       0
away_shoton_volleys         0
away_shoton_other           0
away_shoton_bigchance       0
home_shotoff_headers        0
home_shotoff_freekicks      0
home_shotoff_volleys        0
home_shotoff_other          0
home_shotoff_bigchance      0
home_shotoff_bad_shot       0
away_shotoff_headers        0
away_shotoff_freekicks      0
away_shotoff_volleys        0
away_shotoff_other          0
away_shotoff_bigchance      0
away_shotoff_bad_shot       0
home_crosses                0
away_crosses                0
home_possession_sql         0
away_possession_sql         0
dtype: int64

In [136]:
final_merge.drop(['possession'],axis=1,inplace=True)

In [143]:
final_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 912 entries, 0 to 911
Data columns (total 84 columns):
away_corners              912 non-null int64
away_fouls                912 non-null int64
away_shots                912 non-null int64
away_shots_target         912 non-null int64
away_yellow_cards         912 non-null int64
away_red_cards            912 non-null int64
away_team                 912 non-null object
full_time_away_goals      912 non-null int64
full_time_home_goals      912 non-null int64
home_corners              912 non-null int64
home_fouls                912 non-null int64
home_red_cards            912 non-null int64
home_yellow_cards         912 non-null int64
home_shots                912 non-null int64
home_shots_target         912 non-null int64
half_time_away_goals      912 non-null int64
half_time_home_goals      912 non-null int64
half_time_result          912 non-null int64
home_team                 912 non-null object
Referee                   672 non-null object
result                    912 non-null int64
City                      912 non-null object
Stadium                   912 non-null object
Capacity                  912 non-null float64
Country                   912 non-null object
season                    912 non-null object
date                      912 non-null datetime64[ns]
home_team_api_id          912 non-null int64
away_team_api_id          912 non-null int64
home_possession           912 non-null int64
home_passing              912 non-null float64
home_aerials              912 non-null float64
home_shots_against        912 non-null float64
home_tackles              912 non-null float64
home_interceptions        912 non-null float64
home_dribbles             912 non-null float64
home_fouls_for            912 non-null float64
away_possession           912 non-null int64
away_passing              912 non-null float64
away_aerials              912 non-null float64
away_shots_against        912 non-null float64
away_tackles              912 non-null float64
away_interceptions        912 non-null float64
away_dribbles             912 non-null float64
away_fouls_for            912 non-null float64
temp (F)                  912 non-null float64
dew (F)                   912 non-null float64
humidity                  912 non-null float64
wind direction            912 non-null float64
wind speed (mph)          912 non-null float64
prec (in)                 912 non-null float64
visibility (mi)           912 non-null float64
home_goal_headers         912 non-null int64
home_goal_freekicks       912 non-null int64
home_goal_volleys         912 non-null int64
home_goal_other           912 non-null int64
away_goal_headers         912 non-null int64
away_goal_freekicks       912 non-null int64
away_goal_volleys         912 non-null int64
away_goal_other           912 non-null int64
home_shoton_headers       912 non-null int64
home_shoton_freekicks     912 non-null int64
home_shoton_volleys       912 non-null int64
home_shoton_other         912 non-null int64
home_shoton_bigchance     912 non-null int64
away_shoton_headers       912 non-null int64
away_shoton_freekicks     912 non-null int64
away_shoton_volleys       912 non-null int64
away_shoton_other         912 non-null int64
away_shoton_bigchance     912 non-null int64
home_shotoff_headers      912 non-null int64
home_shotoff_freekicks    912 non-null int64
home_shotoff_volleys      912 non-null int64
home_shotoff_other        912 non-null int64
home_shotoff_bigchance    912 non-null int64
home_shotoff_bad_shot     912 non-null int64
away_shotoff_headers      912 non-null int64
away_shotoff_freekicks    912 non-null int64
away_shotoff_volleys      912 non-null int64
away_shotoff_other        912 non-null int64
away_shotoff_bigchance    912 non-null int64
away_shotoff_bad_shot     912 non-null int64
home_crosses              912 non-null int64
away_crosses              912 non-null int64
dtypes: datetime64[ns](1), float64(22), int64(54), object(7)
memory usage: 605.6+ KB

In [8]:
input_data = pd.read_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_vF.csv')

In [9]:
input_data['Stadium'].unique()

array(['Emirates Stadium ', 'Boleyn Ground ', 'Loftus Road ',
       'Britannia Stadium ', 'The Hawthorns ', 'Anfield ',
       'Sports Direct Arena', 'Turf Moor ', 'Villa Park ',
       'Goodison Park ', "St Mary's Stadium ", 'Liberty Stadium ',
       'Etihad Stadium', 'Stamford Bridge ', 'King Power Stadium ',
       'KC Stadium ', 'Old Trafford ', 'Stadium of Light ',
       'Selhurst Park ', 'White Hart Lane ', 'Carrow Road ',
       'Cardiff City Stadium ', 'Craven Cottage ', 'Madejski Stadium ',
       'DW Stadium ', 'Reebok Stadium ', 'Ewood Park '], dtype=object)

In [15]:
input_data = input_data[~input_data['Stadium'].isin(['Reebok Stadium ','DW Stadium ','Ewood Park '])]
list(input_data['Stadium'].unique())

['Emirates Stadium ',
 'Boleyn Ground ',
 'Loftus Road ',
 'Britannia Stadium ',
 'The Hawthorns ',
 'Anfield ',
 'Sports Direct Arena',
 'Turf Moor ',
 'Villa Park ',
 'Goodison Park ',
 "St Mary's Stadium ",
 'Liberty Stadium ',
 'Etihad Stadium',
 'Stamford Bridge ',
 'King Power Stadium ',
 'KC Stadium ',
 'Old Trafford ',
 'Stadium of Light ',
 'Selhurst Park ',
 'White Hart Lane ',
 'Carrow Road ',
 'Cardiff City Stadium ',
 'Craven Cottage ',
 'Madejski Stadium ']

In [18]:
def stadium_dummy(df):
    stadiums = list(df['Stadium'].unique())
    for stad in stadiums:
        column = str('at_'+str.strip(stad))
        df[column] = df['Stadium'].map(lambda x: 1 if str.strip(x) in column else 0)

In [21]:
stadium_dummy(input_data)
input_data.head().T

,0,1,2,3,4
away_corners,3,5,4,4,3
away_fouls,19,10,17,14,8
away_shots,4,10,10,12,8
away_shots_target,2,4,3,3,6
away_yellow_cards,2,0,1,4,1
away_red_cards,1,1,0,0,0
away_team,Crystal Palace,Tottenham,Crystal Palace,Crystal Palace,Crystal Palace
full_time_away_goals,1,1,0,2,2
full_time_home_goals,2,0,0,1,2
home_corners,9,8,9,8,6
home_fouls,13,12,11,15,14
home_red_cards,0,1,0,0,0
home_yellow_cards,2,1,2,3,3
home_shots,14,18,11,17,17
home_shots_target,6,4,3,4,4
half_time_away_goals,1,0,0,2,2
half_time_home_goals,1,0,0,1,0
half_time_result,1,1,1,0,0
home_team,Arsenal,West Ham,Queens Park Rangers,Stoke,West Bromwich Albion
Referee,J Moss,C Foy,M Jones,A Marriner,M Clattenburg
result,3,0,1,0,1
City,London,London,London,Stoke-on-Trent,West Bromwich
Stadium,Emirates Stadium,Boleyn Ground,Loftus Road,Britannia Stadium,The Hawthorns
Capacity,60361,35303,18439,27740,27877
Country,England,England,England,England,England
season,2014/2015,2014/2015,2014/2015,2014/2015,2014/2015
date,2014-08-16 15:00:00,2014-08-16 15:00:00,2014-12-28 15:00:00,2015-03-21 15:00:00,2014-10-25 15:00:00
home_team_api_id,9825,8654,10172,10194,8659
away_team_api_id,9826,8586,9826,9826,9826
home_possession,77,47,54,57,69
...,...,...,...,...,...
away_shotoff_volleys,0,0,0,0,0
away_shotoff_other,0,1,5,3,2
away_shotoff_bigchance,0,0,0,0,0
away_shotoff_bad_shot,0,0,0,1,0
home_crosses,32,26,28,29,27
away_crosses,9,10,19,11,7
at_Emirates Stadium,1,0,0,0,0
at_Boleyn Ground,0,1,0,0,0
at_Loftus Road,0,0,1,0,0
at_Britannia Stadium,0,0,0,1,0
at_The Hawthorns,0,0,0,0,1
at_Anfield,0,0,0,0,0
at_Sports Direct Arena,0,0,0,0,0
at_Turf Moor,0,0,0,0,0
at_Villa Park,0,0,0,0,0
at_Goodison Park,0,0,0,0,0
at_St Mary's Stadium,0,0,0,0,0
at_Liberty Stadium,0,0,0,0,0
at_Etihad Stadium,0,0,0,0,0
at_Stamford Bridge,0,0,0,0,0
at_King Power Stadium,0,0,0,0,0
at_KC Stadium,0,0,0,0,0
at_Old Trafford,0,0,0,0,0
at_Stadium of Light,0,0,0,0,0
at_Selhurst Park,0,0,0,0,0
at_White Hart Lane,0,0,0,0,0
at_Carrow Road,0,0,0,0,0
at_Cardiff City Stadium,0,0,0,0,0
at_Craven Cottage,0,0,0,0,0
at_Madejski Stadium,0,0,0,0,0

In [22]:
input_data['at_Emirates Stadium'].value_counts()

0    850
1     52
Name: at_Emirates Stadium, dtype: int64

In [23]:
input_data.to_csv('/home/llevin/Desktop/capstone2/cleaned_data/input_data_vF2.csv',index=False)